// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/unstable/xdg-shell/xdg-shell-unstable-v5.xml
//
// xdg_shell_unstable_v5 Protocol Copyright:
//
// Copyright © 2008-2013 Kristian Høgsberg
// Copyright © 2013      Rafael Antognolli
// Copyright © 2013      Jasper St. Pierre
// Copyright © 2010-2013 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdg_shell

import "github.com/SpinningVinyl/go-wayland/wayland/client"

// Shell : create desktop-style surfaces
//
// xdg_shell allows clients to turn a wl_surface into a "real window"
// which can be dragged, resized, stacked, and moved around by the
// user. Everything about this interface is suited towards traditional
// desktop environments.
type Shell struct {
	client.BaseProxy
	pingHandler ShellPingHandlerFunc
}

// NewShell : create desktop-style surfaces
//
// xdg_shell allows clients to turn a wl_surface into a "real window"
// which can be dragged, resized, stacked, and moved around by the
// user. Everything about this interface is suited towards traditional
// desktop environments.
func NewShell(ctx *client.Context) *Shell {
	xdgShell := &Shell{}
	ctx.Register(xdgShell)
	return xdgShell
}

// Destroy : destroy xdg_shell
//
// Destroy this xdg_shell object.
//
// Destroying a bound xdg_shell object while there are surfaces
// still alive created by this xdg_shell object instance is illegal
// and will result in a protocol error.
func (i *Shell) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// UseUnstableVersion : enable use of this unstable version
//
// Negotiate the unstable version of the interface.  This
// mechanism is in place to ensure client and server agree on the
// unstable versions of the protocol that they speak or exit
// cleanly if they don't agree.  This request will go away once
// the xdg-shell protocol is stable.
func (i *Shell) UseUnstableVersion(version int32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(version))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetXdgSurface : create a shell surface from a surface
//
// This creates an xdg_surface for the given surface and gives it the
// xdg_surface role. A wl_surface can only be given an xdg_surface role
// once. If get_xdg_surface is called with a wl_surface that already has
// an active xdg_surface associated with it, or if it had any other role,
// an error is raised.
//
// See the documentation of xdg_surface for more details about what an
// xdg_surface is and how it is used.
func (i *Shell) GetXdgSurface(surface *client.Surface) (*Surface, error) {
	id := NewSurface(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GetXdgPopup : create a popup for a surface
//
// This creates an xdg_popup for the given surface and gives it the
// xdg_popup role. A wl_surface can only be given an xdg_popup role
// once. If get_xdg_popup is called with a wl_surface that already has
// an active xdg_popup associated with it, or if it had any other role,
// an error is raised.
//
// This request must be used in response to some sort of user action
// like a button press, key press, or touch down event.
//
// See the documentation of xdg_popup for more details about what an
// xdg_popup is and how it is used.
//
//	seat: the wl_seat of the user event
//	serial: the serial of the user event
func (i *Shell) GetXdgPopup(surface, parent *client.Surface, seat *client.Seat, serial uint32, x, y int32) (*Popup, error) {
	id := NewPopup(i.Context())
	const opcode = 3
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], parent.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// Pong : respond to a ping event
//
// A client must respond to a ping event with a pong request or
// the client may be deemed unresponsive.
//
//	serial: serial of the ping event
func (i *Shell) Pong(serial uint32) error {
	const opcode = 4
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ShellVersion uint32

// ShellVersion : latest protocol version
//
// The 'current' member of this enum gives the version of the
// protocol.  Implementations can compare this to the version
// they implement using static_assert to ensure the protocol and
// implementation versions match.
const (
	// ShellVersionCurrent : Always the latest version
	ShellVersionCurrent ShellVersion = 5
)

func (e ShellVersion) Name() string {
	switch e {
	case ShellVersionCurrent:
		return "current"
	default:
		return ""
	}
}

func (e ShellVersion) Value() string {
	switch e {
	case ShellVersionCurrent:
		return "5"
	default:
		return ""
	}
}

func (e ShellVersion) String() string {
	return e.Name() + "=" + e.Value()
}

type ShellError uint32

// ShellError :
const (
	// ShellErrorRole : given wl_surface has another role
	ShellErrorRole ShellError = 0
	// ShellErrorDefunctSurfaces : xdg_shell was destroyed before children
	ShellErrorDefunctSurfaces ShellError = 1
	// ShellErrorNotTheTopmostPopup : the client tried to map or destroy a non-topmost popup
	ShellErrorNotTheTopmostPopup ShellError = 2
	// ShellErrorInvalidPopupParent : the client specified an invalid popup parent surface
	ShellErrorInvalidPopupParent ShellError = 3
)

func (e ShellError) Name() string {
	switch e {
	case ShellErrorRole:
		return "role"
	case ShellErrorDefunctSurfaces:
		return "defunct_surfaces"
	case ShellErrorNotTheTopmostPopup:
		return "not_the_topmost_popup"
	case ShellErrorInvalidPopupParent:
		return "invalid_popup_parent"
	default:
		return ""
	}
}

func (e ShellError) Value() string {
	switch e {
	case ShellErrorRole:
		return "0"
	case ShellErrorDefunctSurfaces:
		return "1"
	case ShellErrorNotTheTopmostPopup:
		return "2"
	case ShellErrorInvalidPopupParent:
		return "3"
	default:
		return ""
	}
}

func (e ShellError) String() string {
	return e.Name() + "=" + e.Value()
}

// ShellPingEvent : check if the client is alive
//
// The ping event asks the client if it's still alive. Pass the
// serial specified in the event back to the compositor by sending
// a "pong" request back with the specified serial.
//
// Compositors can use this to determine if the client is still
// alive. It's unspecified what will happen if the client doesn't
// respond to the ping request, or in what timeframe. Clients should
// try to respond in a reasonable amount of time.
//
// A compositor is free to ping in any way it wants, but a client must
// always respond to any xdg_shell object it created.
type ShellPingEvent struct {
	Serial uint32
}
type ShellPingHandlerFunc func(ShellPingEvent)

// SetPingHandler : sets handler for ShellPingEvent
func (i *Shell) SetPingHandler(f ShellPingHandlerFunc) {
	i.pingHandler = f
}

func (i *Shell) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.pingHandler == nil {
			return
		}
		var e ShellPingEvent
		l := 0
		e.Serial = client.Uint32(data[l : l+4])
		l += 4

		i.pingHandler(e)
	}
}

// Surface : A desktop window
//
// An interface that may be implemented by a wl_surface, for
// implementations that provide a desktop-style user interface.
//
// It provides requests to treat surfaces like windows, allowing to set
// properties like maximized, fullscreen, minimized, and to move and resize
// them, and associate metadata like title and app id.
//
// The client must call wl_surface.commit on the corresponding wl_surface
// for the xdg_surface state to take effect. Prior to committing the new
// state, it can set up initial configuration, such as maximizing or setting
// a window geometry.
//
// Even without attaching a buffer the compositor must respond to initial
// committed configuration, for instance sending a configure event with
// expected window geometry if the client maximized its surface during
// initialization.
//
// For a surface to be mapped by the compositor the client must have
// committed both an xdg_surface state and a buffer.
type Surface struct {
	client.BaseProxy
	configureHandler SurfaceConfigureHandlerFunc
	closeHandler     SurfaceCloseHandlerFunc
}

// NewSurface : A desktop window
//
// An interface that may be implemented by a wl_surface, for
// implementations that provide a desktop-style user interface.
//
// It provides requests to treat surfaces like windows, allowing to set
// properties like maximized, fullscreen, minimized, and to move and resize
// them, and associate metadata like title and app id.
//
// The client must call wl_surface.commit on the corresponding wl_surface
// for the xdg_surface state to take effect. Prior to committing the new
// state, it can set up initial configuration, such as maximizing or setting
// a window geometry.
//
// Even without attaching a buffer the compositor must respond to initial
// committed configuration, for instance sending a configure event with
// expected window geometry if the client maximized its surface during
// initialization.
//
// For a surface to be mapped by the compositor the client must have
// committed both an xdg_surface state and a buffer.
func NewSurface(ctx *client.Context) *Surface {
	xdgSurface := &Surface{}
	ctx.Register(xdgSurface)
	return xdgSurface
}

// Destroy : Destroy the xdg_surface
//
// Unmap and destroy the window. The window will be effectively
// hidden from the user's point of view, and all state like
// maximization, fullscreen, and so on, will be lost.
func (i *Surface) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetParent : set the parent of this surface
//
// Set the "parent" of this surface. This window should be stacked
// above a parent. The parent surface must be mapped as long as this
// surface is mapped.
//
// Parent windows should be set on dialogs, toolboxes, or other
// "auxiliary" surfaces, so that the parent is raised when the dialog
// is raised.
func (i *Surface) SetParent(parent *Surface) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if parent == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], parent.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetTitle : set surface title
//
// Set a short title for the surface.
//
// This string may be used to identify the surface in a task bar,
// window list, or other user interface elements provided by the
// compositor.
//
// The string must be encoded in UTF-8.
func (i *Surface) SetTitle(title string) error {
	const opcode = 2
	titleLen := client.PaddedLen(len(title) + 1)
	_reqBufLen := 8 + (4 + titleLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+titleLen)], title, titleLen)
	l += (4 + titleLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// SetAppId : set application ID
//
// Set an application identifier for the surface.
//
// The app ID identifies the general class of applications to which
// the surface belongs. The compositor can use this to group multiple
// surfaces together, or to determine how to launch a new application.
//
// For D-Bus activatable applications, the app ID is used as the D-Bus
// service name.
//
// The compositor shell will try to group application surfaces together
// by their app ID.  As a best practice, it is suggested to select app
// ID's that match the basename of the application's .desktop file.
// For example, "org.freedesktop.FooViewer" where the .desktop file is
// "org.freedesktop.FooViewer.desktop".
//
// See the desktop-entry specification [0] for more details on
// application identifiers and how they relate to well-known D-Bus
// names and .desktop files.
//
// [0] http://standards.freedesktop.org/desktop-entry-spec/
func (i *Surface) SetAppId(appId string) error {
	const opcode = 3
	appIdLen := client.PaddedLen(len(appId) + 1)
	_reqBufLen := 8 + (4 + appIdLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+appIdLen)], appId, appIdLen)
	l += (4 + appIdLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// ShowWindowMenu : show the window menu
//
// Clients implementing client-side decorations might want to show
// a context menu when right-clicking on the decorations, giving the
// user a menu that they can use to maximize or minimize the window.
//
// This request asks the compositor to pop up such a window menu at
// the given position, relative to the local surface coordinates of
// the parent surface. There are no guarantees as to what menu items
// the window menu contains.
//
// This request must be used in response to some sort of user action
// like a button press, key press, or touch down event.
//
//	seat: the wl_seat of the user event
//	serial: the serial of the user event
//	x: the x position to pop up the window menu at
//	y: the y position to pop up the window menu at
func (i *Surface) ShowWindowMenu(seat *client.Seat, serial uint32, x, y int32) error {
	const opcode = 4
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Move : start an interactive move
//
// Start an interactive, user-driven move of the surface.
//
// This request must be used in response to some sort of user action
// like a button press, key press, or touch down event. The passed
// serial is used to determine the type of interactive move (touch,
// pointer, etc).
//
// The server may ignore move requests depending on the state of
// the surface (e.g. fullscreen or maximized), or if the passed serial
// is no longer valid.
//
// If triggered, the surface will lose the focus of the device
// (wl_pointer, wl_touch, etc) used for the move. It is up to the
// compositor to visually indicate that the move is taking place, such as
// updating a pointer cursor, during the move. There is no guarantee
// that the device focus will return when the move is completed.
//
//	seat: the wl_seat of the user event
//	serial: the serial of the user event
func (i *Surface) Move(seat *client.Seat, serial uint32) error {
	const opcode = 5
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Resize : start an interactive resize
//
// Start a user-driven, interactive resize of the surface.
//
// This request must be used in response to some sort of user action
// like a button press, key press, or touch down event. The passed
// serial is used to determine the type of interactive resize (touch,
// pointer, etc).
//
// The server may ignore resize requests depending on the state of
// the surface (e.g. fullscreen or maximized).
//
// If triggered, the client will receive configure events with the
// "resize" state enum value and the expected sizes. See the "resize"
// enum value for more details about what is required. The client
// must also acknowledge configure events using "ack_configure". After
// the resize is completed, the client will receive another "configure"
// event without the resize state.
//
// If triggered, the surface also will lose the focus of the device
// (wl_pointer, wl_touch, etc) used for the resize. It is up to the
// compositor to visually indicate that the resize is taking place,
// such as updating a pointer cursor, during the resize. There is no
// guarantee that the device focus will return when the resize is
// completed.
//
// The edges parameter specifies how the surface should be resized,
// and is one of the values of the resize_edge enum. The compositor
// may use this information to update the surface position for
// example when dragging the top left corner. The compositor may also
// use this information to adapt its behavior, e.g. choose an
// appropriate cursor image.
//
//	seat: the wl_seat of the user event
//	serial: the serial of the user event
//	edges: which edge or corner is being dragged
func (i *Surface) Resize(seat *client.Seat, serial, edges uint32) error {
	const opcode = 6
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(edges))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// AckConfigure : ack a configure event
//
// When a configure event is received, if a client commits the
// surface in response to the configure event, then the client
// must make an ack_configure request sometime before the commit
// request, passing along the serial of the configure event.
//
// For instance, the compositor might use this information to move
// a surface to the top left only when the client has drawn itself
// for the maximized or fullscreen state.
//
// If the client receives multiple configure events before it
// can respond to one, it only has to ack the last configure event.
//
// A client is not required to commit immediately after sending
// an ack_configure request - it may even ack_configure several times
// before its next surface commit.
//
// The compositor expects that the most recently received
// ack_configure request at the time of a commit indicates which
// configure event the client is responding to.
//
//	serial: the serial from the configure event
func (i *Surface) AckConfigure(serial uint32) error {
	const opcode = 7
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetWindowGeometry : set the new window geometry
//
// The window geometry of a window is its "visible bounds" from the
// user's perspective. Client-side decorations often have invisible
// portions like drop-shadows which should be ignored for the
// purposes of aligning, placing and constraining windows.
//
// The window geometry is double-buffered state, see wl_surface.commit.
//
// Once the window geometry of the surface is set once, it is not
// possible to unset it, and it will remain the same until
// set_window_geometry is called again, even if a new subsurface or
// buffer is attached.
//
// If never set, the value is the full bounds of the surface,
// including any subsurfaces. This updates dynamically on every
// commit. This unset mode is meant for extremely simple clients.
//
// If responding to a configure event, the window geometry in here
// must respect the sizing negotiations specified by the states in
// the configure event.
//
// The arguments are given in the surface local coordinate space of
// the wl_surface associated with this xdg_surface.
//
// The width and height must be greater than zero.
func (i *Surface) SetWindowGeometry(x, y, width, height int32) error {
	const opcode = 8
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMaximized : maximize the window
//
// Maximize the surface.
//
// After requesting that the surface should be maximized, the compositor
// will respond by emitting a configure event with the "maximized" state
// and the required window geometry. The client should then update its
// content, drawing it in a maximized state, i.e. without shadow or other
// decoration outside of the window geometry. The client must also
// acknowledge the configure when committing the new content (see
// ack_configure).
//
// It is up to the compositor to decide how and where to maximize the
// surface, for example which output and what region of the screen should
// be used.
//
// If the surface was already maximized, the compositor will still emit
// a configure event with the "maximized" state.
//
// Note that unrelated compositor side state changes may cause
// configure events to be emitted at any time, meaning trying to
// match this request to a specific future configure event is
// futile.
func (i *Surface) SetMaximized() error {
	const opcode = 9
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// UnsetMaximized : unmaximize the window
//
// Unmaximize the surface.
//
// After requesting that the surface should be unmaximized, the compositor
// will respond by emitting a configure event without the "maximized"
// state. If available, the compositor will include the window geometry
// dimensions the window had prior to being maximized in the configure
// request. The client must then update its content, drawing it in a
// regular state, i.e. potentially with shadow, etc. The client must also
// acknowledge the configure when committing the new content (see
// ack_configure).
//
// It is up to the compositor to position the surface after it was
// unmaximized; usually the position the surface had before maximizing, if
// applicable.
//
// If the surface was already not maximized, the compositor will still
// emit a configure event without the "maximized" state.
//
// Note that unrelated compositor side state changes may cause
// configure events to be emitted at any time, meaning trying to
// match this request to a specific future configure event is
// futile.
func (i *Surface) UnsetMaximized() error {
	const opcode = 10
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetFullscreen : set the window as fullscreen on a monitor
//
// Make the surface fullscreen.
//
// You can specify an output that you would prefer to be fullscreen.
// If this value is NULL, it's up to the compositor to choose which
// display will be used to map this surface.
//
// If the surface doesn't cover the whole output, the compositor will
// position the surface in the center of the output and compensate with
// black borders filling the rest of the output.
func (i *Surface) SetFullscreen(output *client.Output) error {
	const opcode = 11
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if output == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], output.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// UnsetFullscreen :
func (i *Surface) UnsetFullscreen() error {
	const opcode = 12
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMinimized : set the window as minimized
//
// Request that the compositor minimize your surface. There is no
// way to know if the surface is currently minimized, nor is there
// any way to unset minimization on this surface.
//
// If you are looking to throttle redrawing when minimized, please
// instead use the wl_surface.frame event for this, as this will
// also work with live previews on windows in Alt-Tab, Expose or
// similar compositor features.
func (i *Surface) SetMinimized() error {
	const opcode = 13
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type SurfaceResizeEdge uint32

// SurfaceResizeEdge : edge values for resizing
//
// These values are used to indicate which edge of a surface
// is being dragged in a resize operation.
const (
	SurfaceResizeEdgeNone        SurfaceResizeEdge = 0
	SurfaceResizeEdgeTop         SurfaceResizeEdge = 1
	SurfaceResizeEdgeBottom      SurfaceResizeEdge = 2
	SurfaceResizeEdgeLeft        SurfaceResizeEdge = 4
	SurfaceResizeEdgeTopLeft     SurfaceResizeEdge = 5
	SurfaceResizeEdgeBottomLeft  SurfaceResizeEdge = 6
	SurfaceResizeEdgeRight       SurfaceResizeEdge = 8
	SurfaceResizeEdgeTopRight    SurfaceResizeEdge = 9
	SurfaceResizeEdgeBottomRight SurfaceResizeEdge = 10
)

func (e SurfaceResizeEdge) Name() string {
	switch e {
	case SurfaceResizeEdgeNone:
		return "none"
	case SurfaceResizeEdgeTop:
		return "top"
	case SurfaceResizeEdgeBottom:
		return "bottom"
	case SurfaceResizeEdgeLeft:
		return "left"
	case SurfaceResizeEdgeTopLeft:
		return "top_left"
	case SurfaceResizeEdgeBottomLeft:
		return "bottom_left"
	case SurfaceResizeEdgeRight:
		return "right"
	case SurfaceResizeEdgeTopRight:
		return "top_right"
	case SurfaceResizeEdgeBottomRight:
		return "bottom_right"
	default:
		return ""
	}
}

func (e SurfaceResizeEdge) Value() string {
	switch e {
	case SurfaceResizeEdgeNone:
		return "0"
	case SurfaceResizeEdgeTop:
		return "1"
	case SurfaceResizeEdgeBottom:
		return "2"
	case SurfaceResizeEdgeLeft:
		return "4"
	case SurfaceResizeEdgeTopLeft:
		return "5"
	case SurfaceResizeEdgeBottomLeft:
		return "6"
	case SurfaceResizeEdgeRight:
		return "8"
	case SurfaceResizeEdgeTopRight:
		return "9"
	case SurfaceResizeEdgeBottomRight:
		return "10"
	default:
		return ""
	}
}

func (e SurfaceResizeEdge) String() string {
	return e.Name() + "=" + e.Value()
}

type SurfaceState uint32

// SurfaceState : types of state on the surface
//
// The different state values used on the surface. This is designed for
// state values like maximized, fullscreen. It is paired with the
// configure event to ensure that both the client and the compositor
// setting the state can be synchronized.
//
// States set in this way are double-buffered, see wl_surface.commit.
//
// Desktop environments may extend this enum by taking up a range of
// values and documenting the range they chose in this description.
// They are not required to document the values for the range that they
// chose. Ideally, any good extensions from a desktop environment should
// make its way into standardization into this enum.
//
// The current reserved ranges are:
//
// 0x0000 - 0x0FFF: xdg-shell core values, documented below.
// 0x1000 - 0x1FFF: GNOME
// 0x2000 - 0x2FFF: EFL
const (
	// SurfaceStateMaximized : the surface is maximized
	SurfaceStateMaximized SurfaceState = 1
	// SurfaceStateFullscreen : the surface is fullscreen
	SurfaceStateFullscreen SurfaceState = 2
	// SurfaceStateResizing : the surface is being resized
	SurfaceStateResizing SurfaceState = 3
	// SurfaceStateActivated : the surface is now activated
	SurfaceStateActivated SurfaceState = 4
)

func (e SurfaceState) Name() string {
	switch e {
	case SurfaceStateMaximized:
		return "maximized"
	case SurfaceStateFullscreen:
		return "fullscreen"
	case SurfaceStateResizing:
		return "resizing"
	case SurfaceStateActivated:
		return "activated"
	default:
		return ""
	}
}

func (e SurfaceState) Value() string {
	switch e {
	case SurfaceStateMaximized:
		return "1"
	case SurfaceStateFullscreen:
		return "2"
	case SurfaceStateResizing:
		return "3"
	case SurfaceStateActivated:
		return "4"
	default:
		return ""
	}
}

func (e SurfaceState) String() string {
	return e.Name() + "=" + e.Value()
}

// SurfaceConfigureEvent : suggest a surface change
//
// The configure event asks the client to resize its surface or to
// change its state.
//
// The width and height arguments specify a hint to the window
// about how its surface should be resized in window geometry
// coordinates. See set_window_geometry.
//
// If the width or height arguments are zero, it means the client
// should decide its own window dimension. This may happen when the
// compositor need to configure the state of the surface but doesn't
// have any information about any previous or expected dimension.
//
// The states listed in the event specify how the width/height
// arguments should be interpreted, and possibly how it should be
// drawn.
//
// Clients should arrange their surface for the new size and
// states, and then send a ack_configure request with the serial
// sent in this configure event at some point before committing
// the new surface.
//
// If the client receives multiple configure events before it
// can respond to one, it is free to discard all but the last
// event it received.
type SurfaceConfigureEvent struct {
	Width  int32
	Height int32
	States []byte
	Serial uint32
}
type SurfaceConfigureHandlerFunc func(SurfaceConfigureEvent)

// SetConfigureHandler : sets handler for SurfaceConfigureEvent
func (i *Surface) SetConfigureHandler(f SurfaceConfigureHandlerFunc) {
	i.configureHandler = f
}

// SurfaceCloseEvent : surface wants to be closed
//
// The close event is sent by the compositor when the user
// wants the surface to be closed. This should be equivalent to
// the user clicking the close button in client-side decorations,
// if your application has any...
//
// This is only a request that the user intends to close your
// window. The client may choose to ignore this request, or show
// a dialog to ask the user to save their data...
type SurfaceCloseEvent struct{}
type SurfaceCloseHandlerFunc func(SurfaceCloseEvent)

// SetCloseHandler : sets handler for SurfaceCloseEvent
func (i *Surface) SetCloseHandler(f SurfaceCloseHandlerFunc) {
	i.closeHandler = f
}

func (i *Surface) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.configureHandler == nil {
			return
		}
		var e SurfaceConfigureEvent
		l := 0
		e.Width = int32(client.Uint32(data[l : l+4]))
		l += 4
		e.Height = int32(client.Uint32(data[l : l+4]))
		l += 4
		statesLen := int(client.Uint32(data[l : l+4]))
		l += 4
		e.States = make([]byte, statesLen)
		copy(e.States, data[l:l+statesLen])
		l += statesLen
		e.Serial = client.Uint32(data[l : l+4])
		l += 4

		i.configureHandler(e)
	case 1:
		if i.closeHandler == nil {
			return
		}
		var e SurfaceCloseEvent

		i.closeHandler(e)
	}
}

// Popup : short-lived, popup surfaces for menus
//
// A popup surface is a short-lived, temporary surface that can be
// used to implement menus. It takes an explicit grab on the surface
// that will be dismissed when the user dismisses the popup. This can
// be done by the user clicking outside the surface, using the keyboard,
// or even locking the screen through closing the lid or a timeout.
//
// When the popup is dismissed, a popup_done event will be sent out,
// and at the same time the surface will be unmapped. The xdg_popup
// object is now inert and cannot be reactivated, so clients should
// destroy it. Explicitly destroying the xdg_popup object will also
// dismiss the popup and unmap the surface.
//
// Clients will receive events for all their surfaces during this
// grab (which is an "owner-events" grab in X11 parlance). This is
// done so that users can navigate through submenus and other
// "nested" popup windows without having to dismiss the topmost
// popup.
//
// Clients that want to dismiss the popup when another surface of
// their own is clicked should dismiss the popup using the destroy
// request.
//
// The parent surface must have either an xdg_surface or xdg_popup
// role.
//
// Specifying an xdg_popup for the parent means that the popups are
// nested, with this popup now being the topmost popup. Nested
// popups must be destroyed in the reverse order they were created
// in, e.g. the only popup you are allowed to destroy at all times
// is the topmost one.
//
// If there is an existing popup when creating a new popup, the
// parent must be the current topmost popup.
//
// A parent surface must be mapped before the new popup is mapped.
//
// When compositors choose to dismiss a popup, they will likely
// dismiss every nested popup as well. When a compositor dismisses
// popups, it will follow the same dismissing order as required
// from the client.
//
// The x and y arguments passed when creating the popup object specify
// where the top left of the popup should be placed, relative to the
// local surface coordinates of the parent surface. See
// xdg_shell.get_xdg_popup.
//
// The client must call wl_surface.commit on the corresponding wl_surface
// for the xdg_popup state to take effect.
//
// For a surface to be mapped by the compositor the client must have
// committed both the xdg_popup state and a buffer.
type Popup struct {
	client.BaseProxy
	popupDoneHandler PopupPopupDoneHandlerFunc
}

// NewPopup : short-lived, popup surfaces for menus
//
// A popup surface is a short-lived, temporary surface that can be
// used to implement menus. It takes an explicit grab on the surface
// that will be dismissed when the user dismisses the popup. This can
// be done by the user clicking outside the surface, using the keyboard,
// or even locking the screen through closing the lid or a timeout.
//
// When the popup is dismissed, a popup_done event will be sent out,
// and at the same time the surface will be unmapped. The xdg_popup
// object is now inert and cannot be reactivated, so clients should
// destroy it. Explicitly destroying the xdg_popup object will also
// dismiss the popup and unmap the surface.
//
// Clients will receive events for all their surfaces during this
// grab (which is an "owner-events" grab in X11 parlance). This is
// done so that users can navigate through submenus and other
// "nested" popup windows without having to dismiss the topmost
// popup.
//
// Clients that want to dismiss the popup when another surface of
// their own is clicked should dismiss the popup using the destroy
// request.
//
// The parent surface must have either an xdg_surface or xdg_popup
// role.
//
// Specifying an xdg_popup for the parent means that the popups are
// nested, with this popup now being the topmost popup. Nested
// popups must be destroyed in the reverse order they were created
// in, e.g. the only popup you are allowed to destroy at all times
// is the topmost one.
//
// If there is an existing popup when creating a new popup, the
// parent must be the current topmost popup.
//
// A parent surface must be mapped before the new popup is mapped.
//
// When compositors choose to dismiss a popup, they will likely
// dismiss every nested popup as well. When a compositor dismisses
// popups, it will follow the same dismissing order as required
// from the client.
//
// The x and y arguments passed when creating the popup object specify
// where the top left of the popup should be placed, relative to the
// local surface coordinates of the parent surface. See
// xdg_shell.get_xdg_popup.
//
// The client must call wl_surface.commit on the corresponding wl_surface
// for the xdg_popup state to take effect.
//
// For a surface to be mapped by the compositor the client must have
// committed both the xdg_popup state and a buffer.
func NewPopup(ctx *client.Context) *Popup {
	xdgPopup := &Popup{}
	ctx.Register(xdgPopup)
	return xdgPopup
}

// Destroy : remove xdg_popup interface
//
// This destroys the popup. Explicitly destroying the xdg_popup
// object will also dismiss the popup, and unmap the surface.
//
// If this xdg_popup is not the "topmost" popup, a protocol error
// will be sent.
func (i *Popup) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// PopupPopupDoneEvent : popup interaction is done
//
// The popup_done event is sent out when a popup is dismissed by the
// compositor. The client should destroy the xdg_popup object at this
// point.
type PopupPopupDoneEvent struct{}
type PopupPopupDoneHandlerFunc func(PopupPopupDoneEvent)

// SetPopupDoneHandler : sets handler for PopupPopupDoneEvent
func (i *Popup) SetPopupDoneHandler(f PopupPopupDoneHandlerFunc) {
	i.popupDoneHandler = f
}

func (i *Popup) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.popupDoneHandler == nil {
			return
		}
		var e PopupPopupDoneEvent

		i.popupDoneHandler(e)
	}
}
