// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/alpha-modifier/alpha-modifier-v1.xml
//
// alpha_modifier_v1 Protocol Copyright:
//
// Copyright © 2024 Xaver Hugl
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package alpha_modifier

import "github.com/SpinningVinyl/go-wayland/wayland/client"

// AlphaModifier : surface alpha modifier manager
//
// This interface allows a client to set a factor for the alpha values on a
// surface, which can be used to offload such operations to the compositor,
// which can in turn for example offload them to KMS.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type AlphaModifier struct {
	client.BaseProxy
}

// NewAlphaModifier : surface alpha modifier manager
//
// This interface allows a client to set a factor for the alpha values on a
// surface, which can be used to offload such operations to the compositor,
// which can in turn for example offload them to KMS.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
func NewAlphaModifier(ctx *client.Context) *AlphaModifier {
	wpAlphaModifierV1 := &AlphaModifier{}
	ctx.Register(wpAlphaModifierV1)
	return wpAlphaModifierV1
}

// Destroy : destroy the alpha modifier manager object
//
// Destroy the alpha modifier manager. This doesn't destroy objects
// created with the manager.
func (i *AlphaModifier) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetSurface : create a new alpha modifier surface object
//
// Create a new alpha modifier surface object associated with the
// given wl_surface. If there is already such an object associated with
// the wl_surface, the already_constructed error will be raised.
func (i *AlphaModifier) GetSurface(surface *client.Surface) (*AlphaModifierSurface, error) {
	id := NewAlphaModifierSurface(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

type AlphaModifierError uint32

// AlphaModifierError :
const (
	// AlphaModifierErrorAlreadyConstructed : wl_surface already has a alpha modifier object
	AlphaModifierErrorAlreadyConstructed AlphaModifierError = 0
)

func (e AlphaModifierError) Name() string {
	switch e {
	case AlphaModifierErrorAlreadyConstructed:
		return "already_constructed"
	default:
		return ""
	}
}

func (e AlphaModifierError) Value() string {
	switch e {
	case AlphaModifierErrorAlreadyConstructed:
		return "0"
	default:
		return ""
	}
}

func (e AlphaModifierError) String() string {
	return e.Name() + "=" + e.Value()
}

// AlphaModifierSurface : alpha modifier object for a surface
//
// This interface allows the client to set a factor for the alpha values on
// a surface, which can be used to offload such operations to the compositor.
// The default factor is UINT32_MAX.
//
// This object has to be destroyed before the associated wl_surface. Once the
// wl_surface is destroyed, all request on this object will raise the
// no_surface error.
type AlphaModifierSurface struct {
	client.BaseProxy
}

// NewAlphaModifierSurface : alpha modifier object for a surface
//
// This interface allows the client to set a factor for the alpha values on
// a surface, which can be used to offload such operations to the compositor.
// The default factor is UINT32_MAX.
//
// This object has to be destroyed before the associated wl_surface. Once the
// wl_surface is destroyed, all request on this object will raise the
// no_surface error.
func NewAlphaModifierSurface(ctx *client.Context) *AlphaModifierSurface {
	wpAlphaModifierSurfaceV1 := &AlphaModifierSurface{}
	ctx.Register(wpAlphaModifierSurfaceV1)
	return wpAlphaModifierSurfaceV1
}

// Destroy : destroy the alpha modifier object
//
// This destroys the object, and is equivalent to set_multiplier with
// a value of UINT32_MAX, with the same double-buffered semantics as
// set_multiplier.
func (i *AlphaModifierSurface) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMultiplier : specify the alpha multiplier
//
// Sets the alpha multiplier for the surface. The alpha multiplier is
// double-buffered state, see wl_surface.commit for details.
//
// This factor is applied in the compositor's blending space, as an
// additional step after the processing of per-pixel alpha values for the
// wl_surface. The exact meaning of the factor is thus undefined, unless
// the blending space is specified in a different extension.
//
// This multiplier is applied even if the buffer attached to the
// wl_surface doesn't have an alpha channel; in that case an alpha value
// of one is used instead.
//
// Zero means completely transparent, UINT32_MAX means completely opaque.
func (i *AlphaModifierSurface) SetMultiplier(factor uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(factor))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type AlphaModifierSurfaceError uint32

// AlphaModifierSurfaceError :
const (
	// AlphaModifierSurfaceErrorNoSurface : wl_surface was destroyed
	AlphaModifierSurfaceErrorNoSurface AlphaModifierSurfaceError = 0
)

func (e AlphaModifierSurfaceError) Name() string {
	switch e {
	case AlphaModifierSurfaceErrorNoSurface:
		return "no_surface"
	default:
		return ""
	}
}

func (e AlphaModifierSurfaceError) Value() string {
	switch e {
	case AlphaModifierSurfaceErrorNoSurface:
		return "0"
	default:
		return ""
	}
}

func (e AlphaModifierSurfaceError) String() string {
	return e.Name() + "=" + e.Value()
}
