// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/ext-workspace/ext-workspace-v1.xml
//
// ext_workspace_v1 Protocol Copyright:
//
// Copyright © 2019 Christopher Billington
// Copyright © 2020 Ilia Bozhinov
// Copyright © 2022 Victoria Brekenfeld
//
// Permission to use, copy, modify, distribute, and sell this
// software and its documentation for any purpose is hereby granted
// without fee, provided that the above copyright notice appear in
// all copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// the copyright holders not be used in advertising or publicity
// pertaining to distribution of the software without specific,
// written prior permission.  The copyright holders make no
// representations about the suitability of this software for any
// purpose.  It is provided "as is" without express or implied
// warranty.
//
// THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
// SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
// SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
// AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
// THIS SOFTWARE.

package ext_workspace

import "github.com/SpinningVinyl/go-wayland/wayland/client"

// WorkspaceManager : list and control workspaces
//
// Workspaces, also called virtual desktops, are groups of surfaces. A
// compositor with a concept of workspaces may only show some such groups of
// surfaces (those of 'active' workspaces) at a time. 'Activating' a
// workspace is a request for the compositor to display that workspace's
// surfaces as normal, whereas the compositor may hide or otherwise
// de-emphasise surfaces that are associated only with 'inactive' workspaces.
// Workspaces are grouped by which sets of outputs they correspond to, and
// may contain surfaces only from those outputs. In this way, it is possible
// for each output to have its own set of workspaces, or for all outputs (or
// any other arbitrary grouping) to share workspaces. Compositors may
// optionally conceptually arrange each group of workspaces in an
// N-dimensional grid.
//
// The purpose of this protocol is to enable the creation of taskbars and
// docks by providing them with a list of workspaces and their properties,
// and allowing them to activate and deactivate workspaces.
//
// After a client binds the ext_workspace_manager_v1, each workspace will be
// sent via the workspace event.
type WorkspaceManager struct {
	client.BaseProxy
	workspaceGroupHandler WorkspaceManagerWorkspaceGroupHandlerFunc
	workspaceHandler      WorkspaceManagerWorkspaceHandlerFunc
	doneHandler           WorkspaceManagerDoneHandlerFunc
	finishedHandler       WorkspaceManagerFinishedHandlerFunc
}

// NewWorkspaceManager : list and control workspaces
//
// Workspaces, also called virtual desktops, are groups of surfaces. A
// compositor with a concept of workspaces may only show some such groups of
// surfaces (those of 'active' workspaces) at a time. 'Activating' a
// workspace is a request for the compositor to display that workspace's
// surfaces as normal, whereas the compositor may hide or otherwise
// de-emphasise surfaces that are associated only with 'inactive' workspaces.
// Workspaces are grouped by which sets of outputs they correspond to, and
// may contain surfaces only from those outputs. In this way, it is possible
// for each output to have its own set of workspaces, or for all outputs (or
// any other arbitrary grouping) to share workspaces. Compositors may
// optionally conceptually arrange each group of workspaces in an
// N-dimensional grid.
//
// The purpose of this protocol is to enable the creation of taskbars and
// docks by providing them with a list of workspaces and their properties,
// and allowing them to activate and deactivate workspaces.
//
// After a client binds the ext_workspace_manager_v1, each workspace will be
// sent via the workspace event.
func NewWorkspaceManager(ctx *client.Context) *WorkspaceManager {
	extWorkspaceManagerV1 := &WorkspaceManager{}
	ctx.Register(extWorkspaceManagerV1)
	return extWorkspaceManagerV1
}

// Commit : all requests about the workspaces have been sent
//
// The client must send this request after it has finished sending other
// requests. The compositor must process a series of requests preceding a
// commit request atomically.
//
// This allows changes to the workspace properties to be seen as atomic,
// even if they happen via multiple events, and even if they involve
// multiple ext_workspace_handle_v1 objects, for example, deactivating one
// workspace and activating another.
func (i *WorkspaceManager) Commit() error {
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Stop : stop sending events
//
// Indicates the client no longer wishes to receive events for new
// workspace groups. However the compositor may emit further workspace
// events, until the finished event is emitted. The compositor is expected
// to send the finished event eventually once the stop request has been processed.
//
// The client must not send any requests after this one, doing so will raise a wl_display
// invalid_object error.
func (i *WorkspaceManager) Stop() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

func (i *WorkspaceManager) Destroy() error {
	i.Context().Unregister(i)
	return nil
}

// WorkspaceManagerWorkspaceGroupEvent : a workspace group has been created
//
// This event is emitted whenever a new workspace group has been created.
//
// All initial details of the workspace group (outputs) will be
// sent immediately after this event via the corresponding events in
// ext_workspace_group_handle_v1 and ext_workspace_handle_v1.
type WorkspaceManagerWorkspaceGroupEvent struct {
	WorkspaceGroup *WorkspaceGroupHandle
}
type WorkspaceManagerWorkspaceGroupHandlerFunc func(WorkspaceManagerWorkspaceGroupEvent)

// SetWorkspaceGroupHandler : sets handler for WorkspaceManagerWorkspaceGroupEvent
func (i *WorkspaceManager) SetWorkspaceGroupHandler(f WorkspaceManagerWorkspaceGroupHandlerFunc) {
	i.workspaceGroupHandler = f
}

// WorkspaceManagerWorkspaceEvent : workspace has been created
//
// This event is emitted whenever a new workspace has been created.
//
// All initial details of the workspace (name, coordinates, state) will
// be sent immediately after this event via the corresponding events in
// ext_workspace_handle_v1.
//
// Workspaces start off unassigned to any workspace group.
type WorkspaceManagerWorkspaceEvent struct {
	Workspace *WorkspaceHandle
}
type WorkspaceManagerWorkspaceHandlerFunc func(WorkspaceManagerWorkspaceEvent)

// SetWorkspaceHandler : sets handler for WorkspaceManagerWorkspaceEvent
func (i *WorkspaceManager) SetWorkspaceHandler(f WorkspaceManagerWorkspaceHandlerFunc) {
	i.workspaceHandler = f
}

// WorkspaceManagerDoneEvent : all information about the workspaces and workspace groups has been sent
//
// This event is sent after all changes in all workspaces and workspace groups have been
// sent.
//
// This allows changes to one or more ext_workspace_group_handle_v1
// properties and ext_workspace_handle_v1 properties
// to be seen as atomic, even if they happen via multiple events.
// In particular, an output moving from one workspace group to
// another sends an output_enter event and an output_leave event to the two
// ext_workspace_group_handle_v1 objects in question. The compositor sends
// the done event only after updating the output information in both
// workspace groups.
type WorkspaceManagerDoneEvent struct{}
type WorkspaceManagerDoneHandlerFunc func(WorkspaceManagerDoneEvent)

// SetDoneHandler : sets handler for WorkspaceManagerDoneEvent
func (i *WorkspaceManager) SetDoneHandler(f WorkspaceManagerDoneHandlerFunc) {
	i.doneHandler = f
}

// WorkspaceManagerFinishedEvent : the compositor has finished with the workspace_manager
//
// This event indicates that the compositor is done sending events to the
// ext_workspace_manager_v1. The server will destroy the object
// immediately after sending this request.
type WorkspaceManagerFinishedEvent struct{}
type WorkspaceManagerFinishedHandlerFunc func(WorkspaceManagerFinishedEvent)

// SetFinishedHandler : sets handler for WorkspaceManagerFinishedEvent
func (i *WorkspaceManager) SetFinishedHandler(f WorkspaceManagerFinishedHandlerFunc) {
	i.finishedHandler = f
}

func (i *WorkspaceManager) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		var e WorkspaceManagerWorkspaceGroupEvent
		l := 0
		e.WorkspaceGroup = new(WorkspaceGroupHandle)
		i.Context().RegisterServer(e.WorkspaceGroup, client.Uint32(data[l:l+4]))
		l += 4

		if i.workspaceGroupHandler != nil {
			i.workspaceGroupHandler(e)
		}
	case 1:
		var e WorkspaceManagerWorkspaceEvent
		l := 0
		e.Workspace = new(WorkspaceHandle)
		i.Context().RegisterServer(e.Workspace, client.Uint32(data[l:l+4]))
		l += 4

		if i.workspaceHandler != nil {
			i.workspaceHandler(e)
		}
	case 2:
		if i.doneHandler == nil {
			return
		}
		var e WorkspaceManagerDoneEvent

		i.doneHandler(e)
	case 3:
		if i.finishedHandler == nil {
			return
		}
		var e WorkspaceManagerFinishedEvent

		i.finishedHandler(e)
	}
}

// WorkspaceGroupHandle : a workspace group assigned to a set of outputs
//
// A ext_workspace_group_handle_v1 object represents a workspace group
// that is assigned a set of outputs and contains a number of workspaces.
//
// The set of outputs assigned to the workspace group is conveyed to the client via
// output_enter and output_leave events, and its workspaces are conveyed with
// workspace events.
//
// For example, a compositor which has a set of workspaces for each output may
// advertise a workspace group (and its workspaces) per output, whereas a compositor
// where a workspace spans all outputs may advertise a single workspace group for all
// outputs.
type WorkspaceGroupHandle struct {
	client.BaseProxy
	capabilitiesHandler   WorkspaceGroupHandleCapabilitiesHandlerFunc
	outputEnterHandler    WorkspaceGroupHandleOutputEnterHandlerFunc
	outputLeaveHandler    WorkspaceGroupHandleOutputLeaveHandlerFunc
	workspaceEnterHandler WorkspaceGroupHandleWorkspaceEnterHandlerFunc
	workspaceLeaveHandler WorkspaceGroupHandleWorkspaceLeaveHandlerFunc
	removedHandler        WorkspaceGroupHandleRemovedHandlerFunc
}

// NewWorkspaceGroupHandle : a workspace group assigned to a set of outputs
//
// A ext_workspace_group_handle_v1 object represents a workspace group
// that is assigned a set of outputs and contains a number of workspaces.
//
// The set of outputs assigned to the workspace group is conveyed to the client via
// output_enter and output_leave events, and its workspaces are conveyed with
// workspace events.
//
// For example, a compositor which has a set of workspaces for each output may
// advertise a workspace group (and its workspaces) per output, whereas a compositor
// where a workspace spans all outputs may advertise a single workspace group for all
// outputs.
func NewWorkspaceGroupHandle(ctx *client.Context) *WorkspaceGroupHandle {
	extWorkspaceGroupHandleV1 := &WorkspaceGroupHandle{}
	ctx.Register(extWorkspaceGroupHandleV1)
	return extWorkspaceGroupHandleV1
}

// CreateWorkspace : create a new workspace
//
// Request that the compositor create a new workspace with the given name
// and assign it to this group.
//
// There is no guarantee that the compositor will create a new workspace,
// or that the created workspace will have the provided name.
func (i *WorkspaceGroupHandle) CreateWorkspace(workspace string) error {
	const opcode = 0
	workspaceLen := client.PaddedLen(len(workspace) + 1)
	_reqBufLen := 8 + (4 + workspaceLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+workspaceLen)], workspace, workspaceLen)
	l += (4 + workspaceLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy : destroy the ext_workspace_group_handle_v1 object
//
// Destroys the ext_workspace_group_handle_v1 object.
//
// This request should be send either when the client does not want to
// use the workspace group object any more or after the removed event to finalize
// the destruction of the object.
func (i *WorkspaceGroupHandle) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type WorkspaceGroupHandleGroupCapabilities uint32

// WorkspaceGroupHandleGroupCapabilities :
const (
	// WorkspaceGroupHandleGroupCapabilitiesCreateWorkspace : create_workspace request is available
	WorkspaceGroupHandleGroupCapabilitiesCreateWorkspace WorkspaceGroupHandleGroupCapabilities = 1
)

func (e WorkspaceGroupHandleGroupCapabilities) Name() string {
	switch e {
	case WorkspaceGroupHandleGroupCapabilitiesCreateWorkspace:
		return "create_workspace"
	default:
		return ""
	}
}

func (e WorkspaceGroupHandleGroupCapabilities) Value() string {
	switch e {
	case WorkspaceGroupHandleGroupCapabilitiesCreateWorkspace:
		return "1"
	default:
		return ""
	}
}

func (e WorkspaceGroupHandleGroupCapabilities) String() string {
	return e.Name() + "=" + e.Value()
}

// WorkspaceGroupHandleCapabilitiesEvent : compositor capabilities
//
// This event advertises the capabilities supported by the compositor. If
// a capability isn't supported, clients should hide or disable the UI
// elements that expose this functionality. For instance, if the
// compositor doesn't advertise support for creating workspaces, a button
// triggering the create_workspace request should not be displayed.
//
// The compositor will ignore requests it doesn't support. For instance,
// a compositor which doesn't advertise support for creating workspaces will ignore
// create_workspace requests.
//
// Compositors must send this event once after creation of an
// ext_workspace_group_handle_v1. When the capabilities change, compositors
// must send this event again.
type WorkspaceGroupHandleCapabilitiesEvent struct {
	Capabilities uint32
}
type WorkspaceGroupHandleCapabilitiesHandlerFunc func(WorkspaceGroupHandleCapabilitiesEvent)

// SetCapabilitiesHandler : sets handler for WorkspaceGroupHandleCapabilitiesEvent
func (i *WorkspaceGroupHandle) SetCapabilitiesHandler(f WorkspaceGroupHandleCapabilitiesHandlerFunc) {
	i.capabilitiesHandler = f
}

// WorkspaceGroupHandleOutputEnterEvent : output assigned to workspace group
//
// This event is emitted whenever an output is assigned to the workspace
// group or a new `wl_output` object is bound by the client, which was already
// assigned to this workspace_group.
type WorkspaceGroupHandleOutputEnterEvent struct {
	Output *client.Output
}
type WorkspaceGroupHandleOutputEnterHandlerFunc func(WorkspaceGroupHandleOutputEnterEvent)

// SetOutputEnterHandler : sets handler for WorkspaceGroupHandleOutputEnterEvent
func (i *WorkspaceGroupHandle) SetOutputEnterHandler(f WorkspaceGroupHandleOutputEnterHandlerFunc) {
	i.outputEnterHandler = f
}

// WorkspaceGroupHandleOutputLeaveEvent : output removed from workspace group
//
// This event is emitted whenever an output is removed from the workspace
// group.
type WorkspaceGroupHandleOutputLeaveEvent struct {
	Output *client.Output
}
type WorkspaceGroupHandleOutputLeaveHandlerFunc func(WorkspaceGroupHandleOutputLeaveEvent)

// SetOutputLeaveHandler : sets handler for WorkspaceGroupHandleOutputLeaveEvent
func (i *WorkspaceGroupHandle) SetOutputLeaveHandler(f WorkspaceGroupHandleOutputLeaveHandlerFunc) {
	i.outputLeaveHandler = f
}

// WorkspaceGroupHandleWorkspaceEnterEvent : workspace added to workspace group
//
// This event is emitted whenever a workspace is assigned to this group.
// A workspace may only ever be assigned to a single group at a single point
// in time, but can be re-assigned during its lifetime.
type WorkspaceGroupHandleWorkspaceEnterEvent struct {
	Workspace *WorkspaceHandle
}
type WorkspaceGroupHandleWorkspaceEnterHandlerFunc func(WorkspaceGroupHandleWorkspaceEnterEvent)

// SetWorkspaceEnterHandler : sets handler for WorkspaceGroupHandleWorkspaceEnterEvent
func (i *WorkspaceGroupHandle) SetWorkspaceEnterHandler(f WorkspaceGroupHandleWorkspaceEnterHandlerFunc) {
	i.workspaceEnterHandler = f
}

// WorkspaceGroupHandleWorkspaceLeaveEvent : workspace removed from workspace group
//
// This event is emitted whenever a workspace is removed from this group.
type WorkspaceGroupHandleWorkspaceLeaveEvent struct {
	Workspace *WorkspaceHandle
}
type WorkspaceGroupHandleWorkspaceLeaveHandlerFunc func(WorkspaceGroupHandleWorkspaceLeaveEvent)

// SetWorkspaceLeaveHandler : sets handler for WorkspaceGroupHandleWorkspaceLeaveEvent
func (i *WorkspaceGroupHandle) SetWorkspaceLeaveHandler(f WorkspaceGroupHandleWorkspaceLeaveHandlerFunc) {
	i.workspaceLeaveHandler = f
}

// WorkspaceGroupHandleRemovedEvent : this workspace group has been removed
//
// This event is send when the group associated with the ext_workspace_group_handle_v1
// has been removed. After sending this request the compositor will immediately consider
// the object inert. Any requests will be ignored except the destroy request.
// It is guaranteed there won't be any more events referencing this
// ext_workspace_group_handle_v1.
//
// The compositor must remove all workspaces belonging to a workspace group
// via a workspace_leave event before removing the workspace group.
type WorkspaceGroupHandleRemovedEvent struct{}
type WorkspaceGroupHandleRemovedHandlerFunc func(WorkspaceGroupHandleRemovedEvent)

// SetRemovedHandler : sets handler for WorkspaceGroupHandleRemovedEvent
func (i *WorkspaceGroupHandle) SetRemovedHandler(f WorkspaceGroupHandleRemovedHandlerFunc) {
	i.removedHandler = f
}

func (i *WorkspaceGroupHandle) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.capabilitiesHandler == nil {
			return
		}
		var e WorkspaceGroupHandleCapabilitiesEvent
		l := 0
		e.Capabilities = client.Uint32(data[l : l+4])
		l += 4

		i.capabilitiesHandler(e)
	case 1:
		if i.outputEnterHandler == nil {
			return
		}
		var e WorkspaceGroupHandleOutputEnterEvent
		l := 0
		e.Output = i.Context().GetProxy(client.Uint32(data[l : l+4])).(*client.Output)
		l += 4

		i.outputEnterHandler(e)
	case 2:
		if i.outputLeaveHandler == nil {
			return
		}
		var e WorkspaceGroupHandleOutputLeaveEvent
		l := 0
		e.Output = i.Context().GetProxy(client.Uint32(data[l : l+4])).(*client.Output)
		l += 4

		i.outputLeaveHandler(e)
	case 3:
		if i.workspaceEnterHandler == nil {
			return
		}
		var e WorkspaceGroupHandleWorkspaceEnterEvent
		l := 0
		e.Workspace = i.Context().GetProxy(client.Uint32(data[l : l+4])).(*WorkspaceHandle)
		l += 4

		i.workspaceEnterHandler(e)
	case 4:
		if i.workspaceLeaveHandler == nil {
			return
		}
		var e WorkspaceGroupHandleWorkspaceLeaveEvent
		l := 0
		e.Workspace = i.Context().GetProxy(client.Uint32(data[l : l+4])).(*WorkspaceHandle)
		l += 4

		i.workspaceLeaveHandler(e)
	case 5:
		if i.removedHandler == nil {
			return
		}
		var e WorkspaceGroupHandleRemovedEvent

		i.removedHandler(e)
	}
}

// WorkspaceHandle : a workspace handing a group of surfaces
//
// A ext_workspace_handle_v1 object represents a workspace that handles a
// group of surfaces.
//
// Each workspace has:
// - a name, conveyed to the client with the name event
// - potentially an id conveyed with the id event
// - a list of states, conveyed to the client with the state event
// - and optionally a set of coordinates, conveyed to the client with the
// coordinates event
//
// The client may request that the compositor activate or deactivate the workspace.
//
// Each workspace can belong to only a single workspace group.
// Depending on the compositor policy, there might be workspaces with
// the same name in different workspace groups, but these workspaces are still
// separate (e.g. one of them might be active while the other is not).
type WorkspaceHandle struct {
	client.BaseProxy
	idHandler           WorkspaceHandleIdHandlerFunc
	nameHandler         WorkspaceHandleNameHandlerFunc
	coordinatesHandler  WorkspaceHandleCoordinatesHandlerFunc
	stateHandler        WorkspaceHandleStateHandlerFunc
	capabilitiesHandler WorkspaceHandleCapabilitiesHandlerFunc
	removedHandler      WorkspaceHandleRemovedHandlerFunc
}

// NewWorkspaceHandle : a workspace handing a group of surfaces
//
// A ext_workspace_handle_v1 object represents a workspace that handles a
// group of surfaces.
//
// Each workspace has:
// - a name, conveyed to the client with the name event
// - potentially an id conveyed with the id event
// - a list of states, conveyed to the client with the state event
// - and optionally a set of coordinates, conveyed to the client with the
// coordinates event
//
// The client may request that the compositor activate or deactivate the workspace.
//
// Each workspace can belong to only a single workspace group.
// Depending on the compositor policy, there might be workspaces with
// the same name in different workspace groups, but these workspaces are still
// separate (e.g. one of them might be active while the other is not).
func NewWorkspaceHandle(ctx *client.Context) *WorkspaceHandle {
	extWorkspaceHandleV1 := &WorkspaceHandle{}
	ctx.Register(extWorkspaceHandleV1)
	return extWorkspaceHandleV1
}

// Destroy : destroy the ext_workspace_handle_v1 object
//
// Destroys the ext_workspace_handle_v1 object.
//
// This request should be made either when the client does not want to
// use the workspace object any more or after the remove event to finalize
// the destruction of the object.
func (i *WorkspaceHandle) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Activate : activate the workspace
//
// Request that this workspace be activated.
//
// There is no guarantee the workspace will be actually activated, and
// behaviour may be compositor-dependent. For example, activating a
// workspace may or may not deactivate all other workspaces in the same
// group.
func (i *WorkspaceHandle) Activate() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Deactivate : deactivate the workspace
//
// Request that this workspace be deactivated.
//
// There is no guarantee the workspace will be actually deactivated.
func (i *WorkspaceHandle) Deactivate() error {
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Assign : assign workspace to group
//
// Requests that this workspace is assigned to the given workspace group.
//
// There is no guarantee the workspace will be assigned.
func (i *WorkspaceHandle) Assign(workspaceGroup *WorkspaceGroupHandle) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], workspaceGroup.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Remove : remove the workspace
//
// Request that this workspace be removed.
//
// There is no guarantee the workspace will be actually removed.
func (i *WorkspaceHandle) Remove() error {
	const opcode = 4
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type WorkspaceHandleState uint32

// WorkspaceHandleState : types of states on the workspace
//
// The different states that a workspace can have.
const (
	// WorkspaceHandleStateActive : the workspace is active
	WorkspaceHandleStateActive WorkspaceHandleState = 1
	// WorkspaceHandleStateUrgent : the workspace requests attention
	WorkspaceHandleStateUrgent WorkspaceHandleState = 2
	WorkspaceHandleStateHidden WorkspaceHandleState = 4
)

func (e WorkspaceHandleState) Name() string {
	switch e {
	case WorkspaceHandleStateActive:
		return "active"
	case WorkspaceHandleStateUrgent:
		return "urgent"
	case WorkspaceHandleStateHidden:
		return "hidden"
	default:
		return ""
	}
}

func (e WorkspaceHandleState) Value() string {
	switch e {
	case WorkspaceHandleStateActive:
		return "1"
	case WorkspaceHandleStateUrgent:
		return "2"
	case WorkspaceHandleStateHidden:
		return "4"
	default:
		return ""
	}
}

func (e WorkspaceHandleState) String() string {
	return e.Name() + "=" + e.Value()
}

type WorkspaceHandleWorkspaceCapabilities uint32

// WorkspaceHandleWorkspaceCapabilities :
const (
	// WorkspaceHandleWorkspaceCapabilitiesActivate : activate request is available
	WorkspaceHandleWorkspaceCapabilitiesActivate WorkspaceHandleWorkspaceCapabilities = 1
	// WorkspaceHandleWorkspaceCapabilitiesDeactivate : deactivate request is available
	WorkspaceHandleWorkspaceCapabilitiesDeactivate WorkspaceHandleWorkspaceCapabilities = 2
	// WorkspaceHandleWorkspaceCapabilitiesRemove : remove request is available
	WorkspaceHandleWorkspaceCapabilitiesRemove WorkspaceHandleWorkspaceCapabilities = 4
	// WorkspaceHandleWorkspaceCapabilitiesAssign : assign request is available
	WorkspaceHandleWorkspaceCapabilitiesAssign WorkspaceHandleWorkspaceCapabilities = 8
)

func (e WorkspaceHandleWorkspaceCapabilities) Name() string {
	switch e {
	case WorkspaceHandleWorkspaceCapabilitiesActivate:
		return "activate"
	case WorkspaceHandleWorkspaceCapabilitiesDeactivate:
		return "deactivate"
	case WorkspaceHandleWorkspaceCapabilitiesRemove:
		return "remove"
	case WorkspaceHandleWorkspaceCapabilitiesAssign:
		return "assign"
	default:
		return ""
	}
}

func (e WorkspaceHandleWorkspaceCapabilities) Value() string {
	switch e {
	case WorkspaceHandleWorkspaceCapabilitiesActivate:
		return "1"
	case WorkspaceHandleWorkspaceCapabilitiesDeactivate:
		return "2"
	case WorkspaceHandleWorkspaceCapabilitiesRemove:
		return "4"
	case WorkspaceHandleWorkspaceCapabilitiesAssign:
		return "8"
	default:
		return ""
	}
}

func (e WorkspaceHandleWorkspaceCapabilities) String() string {
	return e.Name() + "=" + e.Value()
}

// WorkspaceHandleIdEvent : workspace id
//
// If this event is emitted, it will be send immediately after the
// ext_workspace_handle_v1 is created or when an id is assigned to
// a workspace (at most once during its lifetime).
//
// An id will never change during the lifetime of the `ext_workspace_handle_v1`
// and is guaranteed to be unique during its lifetime.
//
// Ids are not human-readable and shouldn't be displayed, use `name` for that purpose.
//
// Compositors are expected to only send ids for workspaces likely stable across multiple
// sessions and can be used by clients to store preferences for workspaces. Workspaces without
// ids should be considered temporary and any data associated with them should be deleted once
// the respective object is lost.
type WorkspaceHandleIdEvent struct {
	Id string
}
type WorkspaceHandleIdHandlerFunc func(WorkspaceHandleIdEvent)

// SetIdHandler : sets handler for WorkspaceHandleIdEvent
func (i *WorkspaceHandle) SetIdHandler(f WorkspaceHandleIdHandlerFunc) {
	i.idHandler = f
}

// WorkspaceHandleNameEvent : workspace name changed
//
// This event is emitted immediately after the ext_workspace_handle_v1 is
// created and whenever the name of the workspace changes.
//
// A name is meant to be human-readable and can be displayed to a user.
// Unlike the id it is neither stable nor unique.
type WorkspaceHandleNameEvent struct {
	Name string
}
type WorkspaceHandleNameHandlerFunc func(WorkspaceHandleNameEvent)

// SetNameHandler : sets handler for WorkspaceHandleNameEvent
func (i *WorkspaceHandle) SetNameHandler(f WorkspaceHandleNameHandlerFunc) {
	i.nameHandler = f
}

// WorkspaceHandleCoordinatesEvent : workspace coordinates changed
//
// This event is used to organize workspaces into an N-dimensional grid
// within a workspace group, and if supported, is emitted immediately after
// the ext_workspace_handle_v1 is created and whenever the coordinates of
// the workspace change. Compositors may not send this event if they do not
// conceptually arrange workspaces in this way. If compositors simply
// number workspaces, without any geometric interpretation, they may send
// 1D coordinates, which clients should not interpret as implying any
// geometry. Sending an empty array means that the compositor no longer
// orders the workspace geometrically.
//
// Coordinates have an arbitrary number of dimensions N with an uint32
// position along each dimension. By convention if N > 1, the first
// dimension is X, the second Y, the third Z, and so on. The compositor may
// chose to utilize these events for a more novel workspace layout
// convention, however. No guarantee is made about the grid being filled or
// bounded; there may be a workspace at coordinate 1 and another at
// coordinate 1000 and none in between. Within a workspace group, however,
// workspaces must have unique coordinates of equal dimensionality.
type WorkspaceHandleCoordinatesEvent struct {
	Coordinates []byte
}
type WorkspaceHandleCoordinatesHandlerFunc func(WorkspaceHandleCoordinatesEvent)

// SetCoordinatesHandler : sets handler for WorkspaceHandleCoordinatesEvent
func (i *WorkspaceHandle) SetCoordinatesHandler(f WorkspaceHandleCoordinatesHandlerFunc) {
	i.coordinatesHandler = f
}

// WorkspaceHandleStateEvent : the state of the workspace changed
//
// This event is emitted immediately after the ext_workspace_handle_v1 is
// created and each time the workspace state changes, either because of a
// compositor action or because of a request in this protocol.
//
// Missing states convey the opposite meaning, e.g. an unset active bit
// means the workspace is currently inactive.
type WorkspaceHandleStateEvent struct {
	State uint32
}
type WorkspaceHandleStateHandlerFunc func(WorkspaceHandleStateEvent)

// SetStateHandler : sets handler for WorkspaceHandleStateEvent
func (i *WorkspaceHandle) SetStateHandler(f WorkspaceHandleStateHandlerFunc) {
	i.stateHandler = f
}

// WorkspaceHandleCapabilitiesEvent : compositor capabilities
//
// This event advertises the capabilities supported by the compositor. If
// a capability isn't supported, clients should hide or disable the UI
// elements that expose this functionality. For instance, if the
// compositor doesn't advertise support for removing workspaces, a button
// triggering the remove request should not be displayed.
//
// The compositor will ignore requests it doesn't support. For instance,
// a compositor which doesn't advertise support for remove will ignore
// remove requests.
//
// Compositors must send this event once after creation of an
// ext_workspace_handle_v1 . When the capabilities change, compositors
// must send this event again.
type WorkspaceHandleCapabilitiesEvent struct {
	Capabilities uint32
}
type WorkspaceHandleCapabilitiesHandlerFunc func(WorkspaceHandleCapabilitiesEvent)

// SetCapabilitiesHandler : sets handler for WorkspaceHandleCapabilitiesEvent
func (i *WorkspaceHandle) SetCapabilitiesHandler(f WorkspaceHandleCapabilitiesHandlerFunc) {
	i.capabilitiesHandler = f
}

// WorkspaceHandleRemovedEvent : this workspace has been removed
//
// This event is send when the workspace associated with the ext_workspace_handle_v1
// has been removed. After sending this request, the compositor will immediately consider
// the object inert. Any requests will be ignored except the destroy request.
//
// It is guaranteed there won't be any more events referencing this
// ext_workspace_handle_v1.
//
// The compositor must only remove a workspaces not currently belonging to any
// workspace_group.
type WorkspaceHandleRemovedEvent struct{}
type WorkspaceHandleRemovedHandlerFunc func(WorkspaceHandleRemovedEvent)

// SetRemovedHandler : sets handler for WorkspaceHandleRemovedEvent
func (i *WorkspaceHandle) SetRemovedHandler(f WorkspaceHandleRemovedHandlerFunc) {
	i.removedHandler = f
}

func (i *WorkspaceHandle) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.idHandler == nil {
			return
		}
		var e WorkspaceHandleIdEvent
		l := 0
		idLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Id = client.String(data[l : l+idLen])
		l += idLen

		i.idHandler(e)
	case 1:
		if i.nameHandler == nil {
			return
		}
		var e WorkspaceHandleNameEvent
		l := 0
		nameLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Name = client.String(data[l : l+nameLen])
		l += nameLen

		i.nameHandler(e)
	case 2:
		if i.coordinatesHandler == nil {
			return
		}
		var e WorkspaceHandleCoordinatesEvent
		l := 0
		coordinatesLen := int(client.Uint32(data[l : l+4]))
		l += 4
		e.Coordinates = make([]byte, coordinatesLen)
		copy(e.Coordinates, data[l:l+coordinatesLen])
		l += coordinatesLen

		i.coordinatesHandler(e)
	case 3:
		if i.stateHandler == nil {
			return
		}
		var e WorkspaceHandleStateEvent
		l := 0
		e.State = client.Uint32(data[l : l+4])
		l += 4

		i.stateHandler(e)
	case 4:
		if i.capabilitiesHandler == nil {
			return
		}
		var e WorkspaceHandleCapabilitiesEvent
		l := 0
		e.Capabilities = client.Uint32(data[l : l+4])
		l += 4

		i.capabilitiesHandler(e)
	case 5:
		if i.removedHandler == nil {
			return
		}
		var e WorkspaceHandleRemovedEvent

		i.removedHandler(e)
	}
}
