// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/ext-background-effect/ext-background-effect-v1.xml
//
// ext_background_effect_v1 Protocol Copyright:
//
// Copyright (C) 2015 Martin Gräßlin
// Copyright (C) 2015 Marco Martin
// Copyright (C) 2020 Vlad Zahorodnii
// Copyright (C) 2024 Xaver Hugl
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package ext_background_effect

import "github.com/SpinningVinyl/go-wayland/wayland/client"

// BackgroundEffectManager : background effect factory
//
// This protocol provides a way to improve visuals of translucent surfaces
// by applying effects like blur to the background behind them.
//
// The capabilities are send when the global is bound, and every time they
// change. Note that when the capability goes away, the corresponding effect
// is no longer applied by the compositor, even if it was set before.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type BackgroundEffectManager struct {
	client.BaseProxy
	capabilitiesHandler BackgroundEffectManagerCapabilitiesHandlerFunc
}

// NewBackgroundEffectManager : background effect factory
//
// This protocol provides a way to improve visuals of translucent surfaces
// by applying effects like blur to the background behind them.
//
// The capabilities are send when the global is bound, and every time they
// change. Note that when the capability goes away, the corresponding effect
// is no longer applied by the compositor, even if it was set before.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
func NewBackgroundEffectManager(ctx *client.Context) *BackgroundEffectManager {
	extBackgroundEffectManagerV1 := &BackgroundEffectManager{}
	ctx.Register(extBackgroundEffectManagerV1)
	return extBackgroundEffectManagerV1
}

// Destroy : destroy the background effect manager
//
// Informs the server that the client will no longer be using this
// protocol object. Existing objects created by this object are not
// affected.
func (i *BackgroundEffectManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetBackgroundEffect : get a background effects object
//
// Instantiate an interface extension for the given wl_surface to add
// effects like blur for the background behind it.
//
// If the given wl_surface already has a ext_background_effect_surface_v1
// object associated, the background_effect_exists protocol error will be
// raised.
//
//	surface: the surface
func (i *BackgroundEffectManager) GetBackgroundEffect(surface *client.Surface) (*BackgroundEffectSurface, error) {
	id := NewBackgroundEffectSurface(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

type BackgroundEffectManagerError uint32

// BackgroundEffectManagerError :
const (
	// BackgroundEffectManagerErrorBackgroundEffectExists : the surface already has a background effect object
	BackgroundEffectManagerErrorBackgroundEffectExists BackgroundEffectManagerError = 0
)

func (e BackgroundEffectManagerError) Name() string {
	switch e {
	case BackgroundEffectManagerErrorBackgroundEffectExists:
		return "background_effect_exists"
	default:
		return ""
	}
}

func (e BackgroundEffectManagerError) Value() string {
	switch e {
	case BackgroundEffectManagerErrorBackgroundEffectExists:
		return "0"
	default:
		return ""
	}
}

func (e BackgroundEffectManagerError) String() string {
	return e.Name() + "=" + e.Value()
}

type BackgroundEffectManagerCapability uint32

// BackgroundEffectManagerCapability :
const (
	// BackgroundEffectManagerCapabilityBlur : the compositor supports applying blur
	BackgroundEffectManagerCapabilityBlur BackgroundEffectManagerCapability = 1
)

func (e BackgroundEffectManagerCapability) Name() string {
	switch e {
	case BackgroundEffectManagerCapabilityBlur:
		return "blur"
	default:
		return ""
	}
}

func (e BackgroundEffectManagerCapability) Value() string {
	switch e {
	case BackgroundEffectManagerCapabilityBlur:
		return "1"
	default:
		return ""
	}
}

func (e BackgroundEffectManagerCapability) String() string {
	return e.Name() + "=" + e.Value()
}

// BackgroundEffectManagerCapabilitiesEvent : capabilities of the compositor
type BackgroundEffectManagerCapabilitiesEvent struct {
	Flags uint32
}
type BackgroundEffectManagerCapabilitiesHandlerFunc func(BackgroundEffectManagerCapabilitiesEvent)

// SetCapabilitiesHandler : sets handler for BackgroundEffectManagerCapabilitiesEvent
func (i *BackgroundEffectManager) SetCapabilitiesHandler(f BackgroundEffectManagerCapabilitiesHandlerFunc) {
	i.capabilitiesHandler = f
}

func (i *BackgroundEffectManager) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.capabilitiesHandler == nil {
			return
		}
		var e BackgroundEffectManagerCapabilitiesEvent
		l := 0
		e.Flags = client.Uint32(data[l : l+4])
		l += 4

		i.capabilitiesHandler(e)
	}
}

// BackgroundEffectSurface : background effects for a surface
//
// The background effect object provides a way to specify a region behind
// a surface that should have background effects like blur applied.
//
// If the wl_surface associated with the ext_background_effect_surface_v1
// object has been destroyed, this object becomes inert.
type BackgroundEffectSurface struct {
	client.BaseProxy
}

// NewBackgroundEffectSurface : background effects for a surface
//
// The background effect object provides a way to specify a region behind
// a surface that should have background effects like blur applied.
//
// If the wl_surface associated with the ext_background_effect_surface_v1
// object has been destroyed, this object becomes inert.
func NewBackgroundEffectSurface(ctx *client.Context) *BackgroundEffectSurface {
	extBackgroundEffectSurfaceV1 := &BackgroundEffectSurface{}
	ctx.Register(extBackgroundEffectSurfaceV1)
	return extBackgroundEffectSurfaceV1
}

// Destroy : release the blur object
//
// Informs the server that the client will no longer be using this protocol
// object. The effect regions will be removed on the next commit.
func (i *BackgroundEffectSurface) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetBlurRegion : set blur region
//
// This request sets the region of the surface that will have its
// background blurred.
//
// The blur region is specified in the surface-local coordinates, and
// clipped by the compositor to the surface size.
//
// The initial value for the blur region is empty. Setting the pending
// blur region has copy semantics, and the wl_region object can be
// destroyed immediately. A NULL wl_region removes the effect.
//
// The blur region is double-buffered state, and will be applied on
// the next wl_surface.commit.
//
// The blur algorithm is subject to compositor policies.
//
// If the associated surface has been destroyed, the surface_destroyed
// error will be raised.
//
//	region: blur region of the surface
func (i *BackgroundEffectSurface) SetBlurRegion(region *client.Region) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if region == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], region.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type BackgroundEffectSurfaceError uint32

// BackgroundEffectSurfaceError :
const (
	// BackgroundEffectSurfaceErrorSurfaceDestroyed : the associated surface has been destroyed
	BackgroundEffectSurfaceErrorSurfaceDestroyed BackgroundEffectSurfaceError = 0
)

func (e BackgroundEffectSurfaceError) Name() string {
	switch e {
	case BackgroundEffectSurfaceErrorSurfaceDestroyed:
		return "surface_destroyed"
	default:
		return ""
	}
}

func (e BackgroundEffectSurfaceError) Value() string {
	switch e {
	case BackgroundEffectSurfaceErrorSurfaceDestroyed:
		return "0"
	default:
		return ""
	}
}

func (e BackgroundEffectSurfaceError) String() string {
	return e.Name() + "=" + e.Value()
}
