// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/ext-image-capture-source/ext-image-capture-source-v1.xml
//
// ext_image_capture_source_v1 Protocol Copyright:
//
// Copyright © 2022 Andri Yngvason
// Copyright © 2024 Simon Ser
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package ext_image_capture_source

import (
	"github.com/SpinningVinyl/go-wayland/wayland/client"

	ext_foreign_toplevel_list "github.com/SpinningVinyl/go-wayland/wayland/staging/ext-foreign-toplevel-list-v1"
)

// ImageCaptureSource : opaque image capture source object
//
// The image capture source object is an opaque descriptor for a capturable
// resource.  This resource may be any sort of entity from which an image
// may be derived.
//
// Note, because ext_image_capture_source_v1 objects are created from multiple
// independent factory interfaces, the ext_image_capture_source_v1 interface is
// frozen at version 1.
type ImageCaptureSource struct {
	client.BaseProxy
}

// NewImageCaptureSource : opaque image capture source object
//
// The image capture source object is an opaque descriptor for a capturable
// resource.  This resource may be any sort of entity from which an image
// may be derived.
//
// Note, because ext_image_capture_source_v1 objects are created from multiple
// independent factory interfaces, the ext_image_capture_source_v1 interface is
// frozen at version 1.
func NewImageCaptureSource(ctx *client.Context) *ImageCaptureSource {
	extImageCaptureSourceV1 := &ImageCaptureSource{}
	ctx.Register(extImageCaptureSourceV1)
	return extImageCaptureSourceV1
}

// Destroy : delete this object
//
// Destroys the image capture source. This request may be sent at any time
// by the client.
func (i *ImageCaptureSource) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// OutputImageCaptureSourceManager : image capture source manager for outputs
//
// A manager for creating image capture source objects for wl_output objects.
type OutputImageCaptureSourceManager struct {
	client.BaseProxy
}

// NewOutputImageCaptureSourceManager : image capture source manager for outputs
//
// A manager for creating image capture source objects for wl_output objects.
func NewOutputImageCaptureSourceManager(ctx *client.Context) *OutputImageCaptureSourceManager {
	extOutputImageCaptureSourceManagerV1 := &OutputImageCaptureSourceManager{}
	ctx.Register(extOutputImageCaptureSourceManagerV1)
	return extOutputImageCaptureSourceManagerV1
}

// CreateSource : create source object for output
//
// Creates a source object for an output. Images captured from this source
// will show the same content as the output. Some elements may be omitted,
// such as cursors and overlays that have been marked as transparent to
// capturing.
func (i *OutputImageCaptureSourceManager) CreateSource(output *client.Output) (*ImageCaptureSource, error) {
	source := NewImageCaptureSource(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], source.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], output.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return source, err
}

// Destroy : delete this object
//
// Destroys the manager. This request may be sent at any time by the client
// and objects created by the manager will remain valid after its
// destruction.
func (i *OutputImageCaptureSourceManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ForeignToplevelImageCaptureSourceManager : image capture source manager for foreign toplevels
//
// A manager for creating image capture source objects for
// ext_foreign_toplevel_handle_v1 objects.
type ForeignToplevelImageCaptureSourceManager struct {
	client.BaseProxy
}

// NewForeignToplevelImageCaptureSourceManager : image capture source manager for foreign toplevels
//
// A manager for creating image capture source objects for
// ext_foreign_toplevel_handle_v1 objects.
func NewForeignToplevelImageCaptureSourceManager(ctx *client.Context) *ForeignToplevelImageCaptureSourceManager {
	extForeignToplevelImageCaptureSourceManagerV1 := &ForeignToplevelImageCaptureSourceManager{}
	ctx.Register(extForeignToplevelImageCaptureSourceManagerV1)
	return extForeignToplevelImageCaptureSourceManagerV1
}

// CreateSource : create source object for foreign toplevel
//
// Creates a source object for a foreign toplevel handle. Images captured
// from this source will show the same content as the toplevel.
func (i *ForeignToplevelImageCaptureSourceManager) CreateSource(toplevelHandle *ext_foreign_toplevel_list.ForeignToplevelHandle) (*ImageCaptureSource, error) {
	source := NewImageCaptureSource(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], source.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], toplevelHandle.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return source, err
}

// Destroy : delete this object
//
// Destroys the manager. This request may be sent at any time by the client
// and objects created by the manager will remain valid after its
// destruction.
func (i *ForeignToplevelImageCaptureSourceManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
