// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/xdg-toplevel-tag/xdg-toplevel-tag-v1.xml
//
// xdg_toplevel_tag_v1 Protocol Copyright:
//
// Copyright © 2024 Xaver Hugl
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdg_toplevel_tag

import (
	"github.com/SpinningVinyl/go-wayland/wayland/client"
	xdg_shell "github.com/SpinningVinyl/go-wayland/wayland/stable/xdg-shell"
)

// ToplevelTagManager : protocol for setting toplevel tags
//
// In order to make some window properties like position, size,
// "always on top" or user defined rules for window behavior persistent, the
// compositor needs some way to identify windows even after the application
// has been restarted.
// This protocol allows clients to make this possible by setting a tag for
// toplevels.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type ToplevelTagManager struct {
	client.BaseProxy
}

// NewToplevelTagManager : protocol for setting toplevel tags
//
// In order to make some window properties like position, size,
// "always on top" or user defined rules for window behavior persistent, the
// compositor needs some way to identify windows even after the application
// has been restarted.
// This protocol allows clients to make this possible by setting a tag for
// toplevels.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
func NewToplevelTagManager(ctx *client.Context) *ToplevelTagManager {
	xdgToplevelTagManagerV1 := &ToplevelTagManager{}
	ctx.Register(xdgToplevelTagManagerV1)
	return xdgToplevelTagManagerV1
}

// Destroy : destroy toplevel tag object
//
// Destroy this toplevel tag manager object. This request has no other
// effects.
func (i *ToplevelTagManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetToplevelTag : set tag
//
// Set a tag for a toplevel. The tag may be shown to the user in UI, so
// it's preferable for it to be human readable, but it must be suitable
// for configuration files and should not be translated.
// Suitable tags would for example be "main window", "settings",
// "e-mail composer" or similar.
//
// The tag does not need to be unique across applications, and the client
// may set the same tag for multiple windows, for example if the user has
// opened the same UI twice. How the potentially resulting conflicts are
// handled is compositor policy.
//
// The client should set the tag as part of the initial commit on the
// associated toplevel, but it may set it at any time afterwards as well,
// for example if the purpose of the toplevel changes.
//
//	tag: untranslated tag
func (i *ToplevelTagManager) SetToplevelTag(toplevel *xdg_shell.Toplevel, tag string) error {
	const opcode = 1
	tagLen := client.PaddedLen(len(tag) + 1)
	_reqBufLen := 8 + 4 + (4 + tagLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], toplevel.ID())
	l += 4
	client.PutString(_reqBuf[l:l+(4+tagLen)], tag, tagLen)
	l += (4 + tagLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// SetToplevelDescription : set description
//
// Set a description for a toplevel. This description may be shown to the
// user in UI or read by a screen reader for accessibility purposes, and
// should be translated.
// It is recommended to make the description the translation of the tag.
//
// The client should set the description as part of the initial commit on
// the associated toplevel, but it may set it at any time afterwards as
// well, for example if the purpose of the toplevel changes.
//
//	description: translated description
func (i *ToplevelTagManager) SetToplevelDescription(toplevel *xdg_shell.Toplevel, description string) error {
	const opcode = 2
	descriptionLen := client.PaddedLen(len(description) + 1)
	_reqBufLen := 8 + 4 + (4 + descriptionLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], toplevel.ID())
	l += 4
	client.PutString(_reqBuf[l:l+(4+descriptionLen)], description, descriptionLen)
	l += (4 + descriptionLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}
