// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/unstable/xwayland-keyboard-grab/xwayland-keyboard-grab-unstable-v1.xml
//
// xwayland_keyboard_grab_unstable_v1 Protocol Copyright:
//
// Copyright © 2017 Red Hat Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xwayland_keyboard_grab

import "github.com/SpinningVinyl/go-wayland/wayland/client"

// XwaylandKeyboardGrabManager : context object for keyboard grab manager
//
// A global interface used for grabbing the keyboard.
type XwaylandKeyboardGrabManager struct {
	client.BaseProxy
}

// NewXwaylandKeyboardGrabManager : context object for keyboard grab manager
//
// A global interface used for grabbing the keyboard.
func NewXwaylandKeyboardGrabManager(ctx *client.Context) *XwaylandKeyboardGrabManager {
	zwpXwaylandKeyboardGrabManagerV1 := &XwaylandKeyboardGrabManager{}
	ctx.Register(zwpXwaylandKeyboardGrabManagerV1)
	return zwpXwaylandKeyboardGrabManagerV1
}

// Destroy : destroy the keyboard grab manager
//
// Destroy the keyboard grab manager.
func (i *XwaylandKeyboardGrabManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GrabKeyboard : grab the keyboard to a surface
//
// The grab_keyboard request asks for a grab of the keyboard, forcing
// the keyboard focus for the given seat upon the given surface.
//
// The protocol provides no guarantee that the grab is ever satisfied,
// and does not require the compositor to send an error if the grab
// cannot ever be satisfied. It is thus possible to request a keyboard
// grab that will never be effective.
//
// The protocol:
//
// * does not guarantee that the grab itself is applied for a surface,
// the grab request may be silently ignored by the compositor,
// * does not guarantee that any events are sent to this client even
// if the grab is applied to a surface,
// * does not guarantee that events sent to this client are exhaustive,
// a compositor may filter some events for its own consumption,
// * does not guarantee that events sent to this client are continuous,
// a compositor may change and reroute keyboard events while the grab
// is nominally active.
//
//	surface: surface to report keyboard events to
//	seat: the seat for which the keyboard should be grabbed
func (i *XwaylandKeyboardGrabManager) GrabKeyboard(surface *client.Surface, seat *client.Seat) (*XwaylandKeyboardGrab, error) {
	id := NewXwaylandKeyboardGrab(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// XwaylandKeyboardGrab : interface for grabbing the keyboard
//
// A global interface used for grabbing the keyboard.
type XwaylandKeyboardGrab struct {
	client.BaseProxy
}

// NewXwaylandKeyboardGrab : interface for grabbing the keyboard
//
// A global interface used for grabbing the keyboard.
func NewXwaylandKeyboardGrab(ctx *client.Context) *XwaylandKeyboardGrab {
	zwpXwaylandKeyboardGrabV1 := &XwaylandKeyboardGrab{}
	ctx.Register(zwpXwaylandKeyboardGrabV1)
	return zwpXwaylandKeyboardGrabV1
}

// Destroy : destroy the grabbed keyboard object
//
// Destroy the grabbed keyboard object. If applicable, the compositor
// will ungrab the keyboard.
func (i *XwaylandKeyboardGrab) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
