// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/pointer-warp/pointer-warp-v1.xml
//
// pointer_warp_v1 Protocol Copyright:
//
// Copyright © 2024 Neal Gompa
// Copyright © 2024 Xaver Hugl
// Copyright © 2024 Matthias Klumpp
// Copyright © 2024 Vlad Zahorodnii
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package pointer_warp

import "github.com/SpinningVinyl/go-wayland/wayland/client"

// PointerWarp : reposition the pointer to a location on a surface
//
// This global interface allows applications to request the pointer to be
// moved to a position relative to a wl_surface.
//
// Note that if the desired behavior is to constrain the pointer to an area
// or lock it to a position, this protocol does not provide a reliable way
// to do that. The pointer constraint and pointer lock protocols should be
// used for those use cases instead.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type PointerWarp struct {
	client.BaseProxy
}

// NewPointerWarp : reposition the pointer to a location on a surface
//
// This global interface allows applications to request the pointer to be
// moved to a position relative to a wl_surface.
//
// Note that if the desired behavior is to constrain the pointer to an area
// or lock it to a position, this protocol does not provide a reliable way
// to do that. The pointer constraint and pointer lock protocols should be
// used for those use cases instead.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
func NewPointerWarp(ctx *client.Context) *PointerWarp {
	wpPointerWarpV1 := &PointerWarp{}
	ctx.Register(wpPointerWarpV1)
	return wpPointerWarpV1
}

// Destroy : destroy the warp manager
//
// Destroy the pointer warp manager.
func (i *PointerWarp) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WarpPointer : reposition the pointer
//
// Request the compositor to move the pointer to a surface-local position.
// Whether or not the compositor honors the request is implementation defined,
// but it should
// - honor it if the surface has pointer focus, including
// when it has an implicit pointer grab
// - reject it if the enter serial is incorrect
// - reject it if the requested position is outside of the surface
//
// Note that the enter serial is valid for any surface of the client,
// and does not have to be from the surface the pointer is warped to.
//
//	surface: surface to position the pointer on
//	pointer: the pointer that should be repositioned
//	serial: serial number of the enter event
func (i *PointerWarp) WarpPointer(surface *client.Surface, pointer *client.Pointer, x, y float64, serial uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], pointer.ID())
	l += 4
	client.PutFixed(_reqBuf[l:l+4], x)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], y)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
