// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/linux-drm-syncobj/linux-drm-syncobj-v1.xml
//
// linux_drm_syncobj_v1 Protocol Copyright:
//
// Copyright 2016 The Chromium Authors.
// Copyright 2017 Intel Corporation
// Copyright 2018 Collabora, Ltd
// Copyright 2021 Simon Ser
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package linux_drm_syncobj

import (
	"github.com/SpinningVinyl/go-wayland/wayland/client"
	"golang.org/x/sys/unix"
)

// LinuxDrmSyncobjManager : global for providing explicit synchronization
//
// This global is a factory interface, allowing clients to request
// explicit synchronization for buffers on a per-surface basis.
//
// See wp_linux_drm_syncobj_surface_v1 for more information.
type LinuxDrmSyncobjManager struct {
	client.BaseProxy
}

// NewLinuxDrmSyncobjManager : global for providing explicit synchronization
//
// This global is a factory interface, allowing clients to request
// explicit synchronization for buffers on a per-surface basis.
//
// See wp_linux_drm_syncobj_surface_v1 for more information.
func NewLinuxDrmSyncobjManager(ctx *client.Context) *LinuxDrmSyncobjManager {
	wpLinuxDrmSyncobjManagerV1 := &LinuxDrmSyncobjManager{}
	ctx.Register(wpLinuxDrmSyncobjManagerV1)
	return wpLinuxDrmSyncobjManagerV1
}

// Destroy : destroy explicit synchronization factory object
//
// Destroy this explicit synchronization factory object. Other objects
// shall not be affected by this request.
func (i *LinuxDrmSyncobjManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetSurface : extend surface interface for explicit synchronization
//
// Instantiate an interface extension for the given wl_surface to provide
// explicit synchronization.
//
// If the given wl_surface already has an explicit synchronization object
// associated, the surface_exists protocol error is raised.
//
// Graphics APIs, like EGL or Vulkan, that manage the buffer queue and
// commits of a wl_surface themselves, are likely to be using this
// extension internally. If a client is using such an API for a
// wl_surface, it should not directly use this extension on that surface,
// to avoid raising a surface_exists protocol error.
//
//	surface: the surface
func (i *LinuxDrmSyncobjManager) GetSurface(surface *client.Surface) (*LinuxDrmSyncobjSurface, error) {
	id := NewLinuxDrmSyncobjSurface(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// ImportTimeline : import a DRM syncobj timeline
//
// Import a DRM synchronization object timeline.
//
// If the FD cannot be imported, the invalid_timeline error is raised.
//
//	fd: drm_syncobj file descriptor
func (i *LinuxDrmSyncobjManager) ImportTimeline(fd int) (*LinuxDrmSyncobjTimeline, error) {
	id := NewLinuxDrmSyncobjTimeline(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	oob := unix.UnixRights(fd)
	err := i.Context().WriteMsg(_reqBuf[:], oob)
	return id, err
}

type LinuxDrmSyncobjManagerError uint32

// LinuxDrmSyncobjManagerError :
const (
	// LinuxDrmSyncobjManagerErrorSurfaceExists : the surface already has a synchronization object associated
	LinuxDrmSyncobjManagerErrorSurfaceExists LinuxDrmSyncobjManagerError = 0
	// LinuxDrmSyncobjManagerErrorInvalidTimeline : the timeline object could not be imported
	LinuxDrmSyncobjManagerErrorInvalidTimeline LinuxDrmSyncobjManagerError = 1
)

func (e LinuxDrmSyncobjManagerError) Name() string {
	switch e {
	case LinuxDrmSyncobjManagerErrorSurfaceExists:
		return "surface_exists"
	case LinuxDrmSyncobjManagerErrorInvalidTimeline:
		return "invalid_timeline"
	default:
		return ""
	}
}

func (e LinuxDrmSyncobjManagerError) Value() string {
	switch e {
	case LinuxDrmSyncobjManagerErrorSurfaceExists:
		return "0"
	case LinuxDrmSyncobjManagerErrorInvalidTimeline:
		return "1"
	default:
		return ""
	}
}

func (e LinuxDrmSyncobjManagerError) String() string {
	return e.Name() + "=" + e.Value()
}

// LinuxDrmSyncobjTimeline : synchronization object timeline
//
// This object represents an explicit synchronization object timeline
// imported by the client to the compositor.
type LinuxDrmSyncobjTimeline struct {
	client.BaseProxy
}

// NewLinuxDrmSyncobjTimeline : synchronization object timeline
//
// This object represents an explicit synchronization object timeline
// imported by the client to the compositor.
func NewLinuxDrmSyncobjTimeline(ctx *client.Context) *LinuxDrmSyncobjTimeline {
	wpLinuxDrmSyncobjTimelineV1 := &LinuxDrmSyncobjTimeline{}
	ctx.Register(wpLinuxDrmSyncobjTimelineV1)
	return wpLinuxDrmSyncobjTimelineV1
}

// Destroy : destroy the timeline
//
// Destroy the synchronization object timeline. Other objects are not
// affected by this request, in particular timeline points set by
// set_acquire_point and set_release_point are not unset.
func (i *LinuxDrmSyncobjTimeline) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// LinuxDrmSyncobjSurface : per-surface explicit synchronization
//
// This object is an add-on interface for wl_surface to enable explicit
// synchronization.
//
// Each surface can be associated with only one object of this interface at
// any time.
//
// Explicit synchronization is guaranteed to be supported for buffers
// created with any version of the linux-dmabuf protocol. Compositors are
// free to support explicit synchronization for additional buffer types.
// If at surface commit time the attached buffer does not support explicit
// synchronization, an unsupported_buffer error is raised.
//
// As long as the wp_linux_drm_syncobj_surface_v1 object is alive, the
// compositor may ignore implicit synchronization for buffers attached and
// committed to the wl_surface. The delivery of wl_buffer.release events
// for buffers attached to the surface becomes undefined.
//
// Clients must set both acquire and release points if and only if a
// non-null buffer is attached in the same surface commit. See the
// no_buffer, no_acquire_point and no_release_point protocol errors.
//
// If at surface commit time the acquire and release DRM syncobj timelines
// are identical, the acquire point value must be strictly less than the
// release point value, or else the conflicting_points protocol error is
// raised.
type LinuxDrmSyncobjSurface struct {
	client.BaseProxy
}

// NewLinuxDrmSyncobjSurface : per-surface explicit synchronization
//
// This object is an add-on interface for wl_surface to enable explicit
// synchronization.
//
// Each surface can be associated with only one object of this interface at
// any time.
//
// Explicit synchronization is guaranteed to be supported for buffers
// created with any version of the linux-dmabuf protocol. Compositors are
// free to support explicit synchronization for additional buffer types.
// If at surface commit time the attached buffer does not support explicit
// synchronization, an unsupported_buffer error is raised.
//
// As long as the wp_linux_drm_syncobj_surface_v1 object is alive, the
// compositor may ignore implicit synchronization for buffers attached and
// committed to the wl_surface. The delivery of wl_buffer.release events
// for buffers attached to the surface becomes undefined.
//
// Clients must set both acquire and release points if and only if a
// non-null buffer is attached in the same surface commit. See the
// no_buffer, no_acquire_point and no_release_point protocol errors.
//
// If at surface commit time the acquire and release DRM syncobj timelines
// are identical, the acquire point value must be strictly less than the
// release point value, or else the conflicting_points protocol error is
// raised.
func NewLinuxDrmSyncobjSurface(ctx *client.Context) *LinuxDrmSyncobjSurface {
	wpLinuxDrmSyncobjSurfaceV1 := &LinuxDrmSyncobjSurface{}
	ctx.Register(wpLinuxDrmSyncobjSurfaceV1)
	return wpLinuxDrmSyncobjSurfaceV1
}

// Destroy : destroy the surface synchronization object
//
// Destroy this surface synchronization object.
//
// Any timeline point set by this object with set_acquire_point or
// set_release_point since the last commit may be discarded by the
// compositor. Any timeline point set by this object before the last
// commit will not be affected.
func (i *LinuxDrmSyncobjSurface) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetAcquirePoint : set the acquire timeline point
//
// Set the timeline point that must be signalled before the compositor may
// sample from the buffer attached with wl_surface.attach.
//
// The 64-bit unsigned value combined from point_hi and point_lo is the
// point value.
//
// The acquire point is double-buffered state, and will be applied on the
// next wl_surface.commit request for the associated surface. Thus, it
// applies only to the buffer that is attached to the surface at commit
// time.
//
// If an acquire point has already been attached during the same commit
// cycle, the new point replaces the old one.
//
// If the associated wl_surface was destroyed, a no_surface error is
// raised.
//
// If at surface commit time there is a pending acquire timeline point set
// but no pending buffer attached, a no_buffer error is raised. If at
// surface commit time there is a pending buffer attached but no pending
// acquire timeline point set, the no_acquire_point protocol error is
// raised.
//
//	pointHi: high 32 bits of the point value
//	pointLo: low 32 bits of the point value
func (i *LinuxDrmSyncobjSurface) SetAcquirePoint(timeline *LinuxDrmSyncobjTimeline, pointHi, pointLo uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], timeline.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(pointHi))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(pointLo))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetReleasePoint : set the release timeline point
//
// Set the timeline point that must be signalled by the compositor when it
// has finished its usage of the buffer attached with wl_surface.attach
// for the relevant commit.
//
// Once the timeline point is signaled, and assuming the associated buffer
// is not pending release from other wl_surface.commit requests, no
// additional explicit or implicit synchronization with the compositor is
// required to safely re-use the buffer.
//
// Note that clients cannot rely on the release point being always
// signaled after the acquire point: compositors may release buffers
// without ever reading from them. In addition, the compositor may use
// different presentation paths for different commits, which may have
// different release behavior. As a result, the compositor may signal the
// release points in a different order than the client committed them.
//
// Because signaling a timeline point also signals every previous point,
// it is generally not safe to use the same timeline object for the
// release points of multiple buffers. The out-of-order signaling
// described above may lead to a release point being signaled before the
// compositor has finished reading. To avoid this, it is strongly
// recommended that each buffer should use a separate timeline for its
// release points.
//
// The 64-bit unsigned value combined from point_hi and point_lo is the
// point value.
//
// The release point is double-buffered state, and will be applied on the
// next wl_surface.commit request for the associated surface. Thus, it
// applies only to the buffer that is attached to the surface at commit
// time.
//
// If a release point has already been attached during the same commit
// cycle, the new point replaces the old one.
//
// If the associated wl_surface was destroyed, a no_surface error is
// raised.
//
// If at surface commit time there is a pending release timeline point set
// but no pending buffer attached, a no_buffer error is raised. If at
// surface commit time there is a pending buffer attached but no pending
// release timeline point set, the no_release_point protocol error is
// raised.
//
//	pointHi: high 32 bits of the point value
//	pointLo: low 32 bits of the point value
func (i *LinuxDrmSyncobjSurface) SetReleasePoint(timeline *LinuxDrmSyncobjTimeline, pointHi, pointLo uint32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], timeline.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(pointHi))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(pointLo))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type LinuxDrmSyncobjSurfaceError uint32

// LinuxDrmSyncobjSurfaceError :
const (
	// LinuxDrmSyncobjSurfaceErrorNoSurface : the associated wl_surface was destroyed
	LinuxDrmSyncobjSurfaceErrorNoSurface LinuxDrmSyncobjSurfaceError = 1
	// LinuxDrmSyncobjSurfaceErrorUnsupportedBuffer : the buffer does not support explicit synchronization
	LinuxDrmSyncobjSurfaceErrorUnsupportedBuffer LinuxDrmSyncobjSurfaceError = 2
	// LinuxDrmSyncobjSurfaceErrorNoBuffer : no buffer was attached
	LinuxDrmSyncobjSurfaceErrorNoBuffer LinuxDrmSyncobjSurfaceError = 3
	// LinuxDrmSyncobjSurfaceErrorNoAcquirePoint : no acquire timeline point was set
	LinuxDrmSyncobjSurfaceErrorNoAcquirePoint LinuxDrmSyncobjSurfaceError = 4
	// LinuxDrmSyncobjSurfaceErrorNoReleasePoint : no release timeline point was set
	LinuxDrmSyncobjSurfaceErrorNoReleasePoint LinuxDrmSyncobjSurfaceError = 5
	// LinuxDrmSyncobjSurfaceErrorConflictingPoints : acquire and release timeline points are in conflict
	LinuxDrmSyncobjSurfaceErrorConflictingPoints LinuxDrmSyncobjSurfaceError = 6
)

func (e LinuxDrmSyncobjSurfaceError) Name() string {
	switch e {
	case LinuxDrmSyncobjSurfaceErrorNoSurface:
		return "no_surface"
	case LinuxDrmSyncobjSurfaceErrorUnsupportedBuffer:
		return "unsupported_buffer"
	case LinuxDrmSyncobjSurfaceErrorNoBuffer:
		return "no_buffer"
	case LinuxDrmSyncobjSurfaceErrorNoAcquirePoint:
		return "no_acquire_point"
	case LinuxDrmSyncobjSurfaceErrorNoReleasePoint:
		return "no_release_point"
	case LinuxDrmSyncobjSurfaceErrorConflictingPoints:
		return "conflicting_points"
	default:
		return ""
	}
}

func (e LinuxDrmSyncobjSurfaceError) Value() string {
	switch e {
	case LinuxDrmSyncobjSurfaceErrorNoSurface:
		return "1"
	case LinuxDrmSyncobjSurfaceErrorUnsupportedBuffer:
		return "2"
	case LinuxDrmSyncobjSurfaceErrorNoBuffer:
		return "3"
	case LinuxDrmSyncobjSurfaceErrorNoAcquirePoint:
		return "4"
	case LinuxDrmSyncobjSurfaceErrorNoReleasePoint:
		return "5"
	case LinuxDrmSyncobjSurfaceErrorConflictingPoints:
		return "6"
	default:
		return ""
	}
}

func (e LinuxDrmSyncobjSurfaceError) String() string {
	return e.Name() + "=" + e.Value()
}
