// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/xdg-toplevel-drag/xdg-toplevel-drag-v1.xml
//
// xdg_toplevel_drag_v1 Protocol Copyright:
//
// Copyright 2023 David Redondo
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdg_toplevel_drag

import (
	"github.com/SpinningVinyl/go-wayland/wayland/client"
	xdg_shell "github.com/SpinningVinyl/go-wayland/wayland/stable/xdg-shell"
)

// ToplevelDragManager : Move a window during a drag
//
// This protocol enhances normal drag and drop with the ability to move a
// window at the same time. This allows having detachable parts of a window
// that when dragged out of it become a new window and can be dragged over
// an existing window to be reattached.
//
// A typical workflow would be when the user starts dragging on top of a
// detachable part of a window, the client would create a wl_data_source and
// a xdg_toplevel_drag_v1 object and start the drag as normal via
// wl_data_device.start_drag. Once the client determines that the detachable
// window contents should be detached from the originating window, it creates
// a new xdg_toplevel with these contents and issues a
// xdg_toplevel_drag_v1.attach request before mapping it. From now on the new
// window is moved by the compositor during the drag as if the client called
// xdg_toplevel.move.
//
// Dragging an existing window is similar. The client creates a
// xdg_toplevel_drag_v1 object and attaches the existing toplevel before
// starting the drag.
//
// Clients use the existing drag and drop mechanism to detect when a window
// can be docked or undocked. If the client wants to snap a window into a
// parent window it should delete or unmap the dragged top-level. If the
// contents should be detached again it attaches a new toplevel as described
// above. If a drag operation is cancelled without being dropped, clients
// should revert to the previous state, deleting any newly created windows
// as appropriate. When a drag operation ends as indicated by
// wl_data_source.dnd_drop_performed the dragged toplevel window's final
// position is determined as if a xdg_toplevel_move operation ended.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type ToplevelDragManager struct {
	client.BaseProxy
}

// NewToplevelDragManager : Move a window during a drag
//
// This protocol enhances normal drag and drop with the ability to move a
// window at the same time. This allows having detachable parts of a window
// that when dragged out of it become a new window and can be dragged over
// an existing window to be reattached.
//
// A typical workflow would be when the user starts dragging on top of a
// detachable part of a window, the client would create a wl_data_source and
// a xdg_toplevel_drag_v1 object and start the drag as normal via
// wl_data_device.start_drag. Once the client determines that the detachable
// window contents should be detached from the originating window, it creates
// a new xdg_toplevel with these contents and issues a
// xdg_toplevel_drag_v1.attach request before mapping it. From now on the new
// window is moved by the compositor during the drag as if the client called
// xdg_toplevel.move.
//
// Dragging an existing window is similar. The client creates a
// xdg_toplevel_drag_v1 object and attaches the existing toplevel before
// starting the drag.
//
// Clients use the existing drag and drop mechanism to detect when a window
// can be docked or undocked. If the client wants to snap a window into a
// parent window it should delete or unmap the dragged top-level. If the
// contents should be detached again it attaches a new toplevel as described
// above. If a drag operation is cancelled without being dropped, clients
// should revert to the previous state, deleting any newly created windows
// as appropriate. When a drag operation ends as indicated by
// wl_data_source.dnd_drop_performed the dragged toplevel window's final
// position is determined as if a xdg_toplevel_move operation ended.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
func NewToplevelDragManager(ctx *client.Context) *ToplevelDragManager {
	xdgToplevelDragManagerV1 := &ToplevelDragManager{}
	ctx.Register(xdgToplevelDragManagerV1)
	return xdgToplevelDragManagerV1
}

// Destroy : destroy the xdg_toplevel_drag_manager_v1 object
//
// Destroy this xdg_toplevel_drag_manager_v1 object. Other objects,
// including xdg_toplevel_drag_v1 objects created by this factory, are not
// affected by this request.
func (i *ToplevelDragManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetXdgToplevelDrag : get an xdg_toplevel_drag for a wl_data_source
//
// Create an xdg_toplevel_drag for a drag and drop operation that is going
// to be started with data_source.
//
// This request can only be made on sources used in drag-and-drop, so it
// must be performed before wl_data_device.start_drag. Attempting to use
// the source other than for drag-and-drop such as in
// wl_data_device.set_selection will raise an invalid_source error.
//
// Destroying data_source while a toplevel is attached to the
// xdg_toplevel_drag is undefined.
func (i *ToplevelDragManager) GetXdgToplevelDrag(dataSource *client.DataSource) (*ToplevelDrag, error) {
	id := NewToplevelDrag(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], dataSource.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

type ToplevelDragManagerError uint32

// ToplevelDragManagerError :
const (
	// ToplevelDragManagerErrorInvalidSource : data_source already used for toplevel drag
	ToplevelDragManagerErrorInvalidSource ToplevelDragManagerError = 0
)

func (e ToplevelDragManagerError) Name() string {
	switch e {
	case ToplevelDragManagerErrorInvalidSource:
		return "invalid_source"
	default:
		return ""
	}
}

func (e ToplevelDragManagerError) Value() string {
	switch e {
	case ToplevelDragManagerErrorInvalidSource:
		return "0"
	default:
		return ""
	}
}

func (e ToplevelDragManagerError) String() string {
	return e.Name() + "=" + e.Value()
}

// ToplevelDrag : Object representing a toplevel move during a drag
type ToplevelDrag struct {
	client.BaseProxy
}

// NewToplevelDrag : Object representing a toplevel move during a drag
func NewToplevelDrag(ctx *client.Context) *ToplevelDrag {
	xdgToplevelDragV1 := &ToplevelDrag{}
	ctx.Register(xdgToplevelDragV1)
	return xdgToplevelDragV1
}

// Destroy : destroy an xdg_toplevel_drag_v1 object
//
// Destroy this xdg_toplevel_drag_v1 object. This request must only be
// called after the underlying wl_data_source drag has ended, as indicated
// by the dnd_drop_performed or cancelled events. In any other case an
// ongoing_drag error is raised.
func (i *ToplevelDrag) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Attach : Move a toplevel with the drag operation
//
// Request that the window will be moved with the cursor during the drag
// operation. The offset is a hint to the compositor how the toplevel
// should be positioned relative to the cursor hotspot in surface local
// coordinates and relative to the geometry of the toplevel being attached.
// See xdg_surface.set_window_geometry. For example it might only
// be used when an unmapped window is attached. The attached window
// does not participate in the selection of the drag target.
//
// If the toplevel is unmapped while it is attached, it is automatically
// detached from the drag. In this case this request has to be called again
// if the window should be attached after it is remapped.
//
// This request can be called multiple times but issuing it while a
// toplevel with an active role is attached raises a toplevel_attached
// error.
//
//	xOffset: dragged surface x offset
//	yOffset: dragged surface y offset
func (i *ToplevelDrag) Attach(toplevel *xdg_shell.Toplevel, xOffset, yOffset int32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], toplevel.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(xOffset))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(yOffset))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ToplevelDragError uint32

// ToplevelDragError :
const (
	// ToplevelDragErrorToplevelAttached : valid toplevel already attached
	ToplevelDragErrorToplevelAttached ToplevelDragError = 0
	// ToplevelDragErrorOngoingDrag : drag has not ended
	ToplevelDragErrorOngoingDrag ToplevelDragError = 1
)

func (e ToplevelDragError) Name() string {
	switch e {
	case ToplevelDragErrorToplevelAttached:
		return "toplevel_attached"
	case ToplevelDragErrorOngoingDrag:
		return "ongoing_drag"
	default:
		return ""
	}
}

func (e ToplevelDragError) Value() string {
	switch e {
	case ToplevelDragErrorToplevelAttached:
		return "0"
	case ToplevelDragErrorOngoingDrag:
		return "1"
	default:
		return ""
	}
}

func (e ToplevelDragError) String() string {
	return e.Name() + "=" + e.Value()
}
