// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/color-representation/color-representation-v1.xml
//
// color_representation_v1 Protocol Copyright:
//
// Copyright 2022 Simon Ser
// Copyright 2022 Red Hat, Inc.
// Copyright 2022 Collabora, Ltd.
// Copyright 2022-2025 Red Hat, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package color_representation

import "github.com/SpinningVinyl/go-wayland/wayland/client"

// ColorRepresentationManager : color representation manager singleton
//
// A singleton global interface used for getting color representation
// extensions for wl_surface. The extension interfaces allow setting the
// color representation of surfaces.
//
// Compositors should never remove this global.
type ColorRepresentationManager struct {
	client.BaseProxy
	supportedAlphaModeHandler             ColorRepresentationManagerSupportedAlphaModeHandlerFunc
	supportedCoefficientsAndRangesHandler ColorRepresentationManagerSupportedCoefficientsAndRangesHandlerFunc
	doneHandler                           ColorRepresentationManagerDoneHandlerFunc
}

// NewColorRepresentationManager : color representation manager singleton
//
// A singleton global interface used for getting color representation
// extensions for wl_surface. The extension interfaces allow setting the
// color representation of surfaces.
//
// Compositors should never remove this global.
func NewColorRepresentationManager(ctx *client.Context) *ColorRepresentationManager {
	wpColorRepresentationManagerV1 := &ColorRepresentationManager{}
	ctx.Register(wpColorRepresentationManagerV1)
	return wpColorRepresentationManagerV1
}

// Destroy : destroy the manager
//
// Destroy the wp_color_representation_manager_v1 object. This does not
// affect any other objects in any way.
func (i *ColorRepresentationManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetSurface : create a color representation interface for a wl_surface
//
// If a wp_color_representation_surface_v1 object already exists for the
// given wl_surface, the protocol error surface_exists is raised.
//
// This creates a new color wp_color_representation_surface_v1 object for
// the given wl_surface.
//
// See the wp_color_representation_surface_v1 interface for more details.
func (i *ColorRepresentationManager) GetSurface(surface *client.Surface) (*ColorRepresentationSurface, error) {
	id := NewColorRepresentationSurface(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

type ColorRepresentationManagerError uint32

// ColorRepresentationManagerError : protocol errors
const (
	// ColorRepresentationManagerErrorSurfaceExists : color representation surface exists already
	ColorRepresentationManagerErrorSurfaceExists ColorRepresentationManagerError = 1
)

func (e ColorRepresentationManagerError) Name() string {
	switch e {
	case ColorRepresentationManagerErrorSurfaceExists:
		return "surface_exists"
	default:
		return ""
	}
}

func (e ColorRepresentationManagerError) Value() string {
	switch e {
	case ColorRepresentationManagerErrorSurfaceExists:
		return "1"
	default:
		return ""
	}
}

func (e ColorRepresentationManagerError) String() string {
	return e.Name() + "=" + e.Value()
}

// ColorRepresentationManagerSupportedAlphaModeEvent : supported alpha modes
//
// When this object is created, it shall immediately send this event once
// for each alpha mode the compositor supports.
//
// For the definition of the supported values, see the
// wp_color_representation_surface_v1::alpha_mode enum.
type ColorRepresentationManagerSupportedAlphaModeEvent struct {
	AlphaMode uint32
}
type ColorRepresentationManagerSupportedAlphaModeHandlerFunc func(ColorRepresentationManagerSupportedAlphaModeEvent)

// SetSupportedAlphaModeHandler : sets handler for ColorRepresentationManagerSupportedAlphaModeEvent
func (i *ColorRepresentationManager) SetSupportedAlphaModeHandler(f ColorRepresentationManagerSupportedAlphaModeHandlerFunc) {
	i.supportedAlphaModeHandler = f
}

// ColorRepresentationManagerSupportedCoefficientsAndRangesEvent : supported matrix coefficients and ranges
//
// When this object is created, it shall immediately send this event once
// for each matrix coefficient and color range combination the compositor
// supports.
//
// For the definition of the supported values, see the
// wp_color_representation_surface_v1::coefficients and
// wp_color_representation_surface_v1::range enums.
type ColorRepresentationManagerSupportedCoefficientsAndRangesEvent struct {
	Coefficients uint32
	Range        uint32
}
type ColorRepresentationManagerSupportedCoefficientsAndRangesHandlerFunc func(ColorRepresentationManagerSupportedCoefficientsAndRangesEvent)

// SetSupportedCoefficientsAndRangesHandler : sets handler for ColorRepresentationManagerSupportedCoefficientsAndRangesEvent
func (i *ColorRepresentationManager) SetSupportedCoefficientsAndRangesHandler(f ColorRepresentationManagerSupportedCoefficientsAndRangesHandlerFunc) {
	i.supportedCoefficientsAndRangesHandler = f
}

// ColorRepresentationManagerDoneEvent : all features have been sent
//
// This event is sent when all supported features have been sent.
type ColorRepresentationManagerDoneEvent struct{}
type ColorRepresentationManagerDoneHandlerFunc func(ColorRepresentationManagerDoneEvent)

// SetDoneHandler : sets handler for ColorRepresentationManagerDoneEvent
func (i *ColorRepresentationManager) SetDoneHandler(f ColorRepresentationManagerDoneHandlerFunc) {
	i.doneHandler = f
}

func (i *ColorRepresentationManager) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.supportedAlphaModeHandler == nil {
			return
		}
		var e ColorRepresentationManagerSupportedAlphaModeEvent
		l := 0
		e.AlphaMode = client.Uint32(data[l : l+4])
		l += 4

		i.supportedAlphaModeHandler(e)
	case 1:
		if i.supportedCoefficientsAndRangesHandler == nil {
			return
		}
		var e ColorRepresentationManagerSupportedCoefficientsAndRangesEvent
		l := 0
		e.Coefficients = client.Uint32(data[l : l+4])
		l += 4
		e.Range = client.Uint32(data[l : l+4])
		l += 4

		i.supportedCoefficientsAndRangesHandler(e)
	case 2:
		if i.doneHandler == nil {
			return
		}
		var e ColorRepresentationManagerDoneEvent

		i.doneHandler(e)
	}
}

// ColorRepresentationSurface : color representation extension to a surface
//
// A wp_color_representation_surface_v1 allows the client to set the color
// representation metadata of a surface.
//
// By default, a surface does not have any color representation metadata set.
// The reconstruction of R, G, B signals on such surfaces is compositor
// implementation defined. The alpha mode is assumed to be
// premultiplied_electrical when the alpha mode is unset.
//
// If the wl_surface associated with the wp_color_representation_surface_v1
// is destroyed, the wp_color_representation_surface_v1 object becomes inert.
type ColorRepresentationSurface struct {
	client.BaseProxy
}

// NewColorRepresentationSurface : color representation extension to a surface
//
// A wp_color_representation_surface_v1 allows the client to set the color
// representation metadata of a surface.
//
// By default, a surface does not have any color representation metadata set.
// The reconstruction of R, G, B signals on such surfaces is compositor
// implementation defined. The alpha mode is assumed to be
// premultiplied_electrical when the alpha mode is unset.
//
// If the wl_surface associated with the wp_color_representation_surface_v1
// is destroyed, the wp_color_representation_surface_v1 object becomes inert.
func NewColorRepresentationSurface(ctx *client.Context) *ColorRepresentationSurface {
	wpColorRepresentationSurfaceV1 := &ColorRepresentationSurface{}
	ctx.Register(wpColorRepresentationSurfaceV1)
	return wpColorRepresentationSurfaceV1
}

// Destroy : destroy the color representation
//
// Destroy the wp_color_representation_surface_v1 object.
//
// Destroying this object unsets all the color representation metadata from
// the surface. See the wp_color_representation_surface_v1 interface
// description for how a compositor handles a surface without color
// representation metadata. Unsetting is double-buffered state, see
// wl_surface.commit.
func (i *ColorRepresentationSurface) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetAlphaMode : set the surface alpha mode
//
// If this protocol object is inert, the protocol error inert is raised.
//
// Assuming an alpha channel exists, it is always linear. The alpha mode
// determines whether and how the color channels include pre-multiplied
// alpha. Using straight alpha might have performance benefits.
//
// Only alpha modes advertised by the compositor are allowed to be used as
// argument for this request. The "alpha_mode" protocol error is raised
// otherwise.
//
// Alpha mode is double buffered, see wl_surface.commit.
//
//	alphaMode: alpha mode
func (i *ColorRepresentationSurface) SetAlphaMode(alphaMode uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(alphaMode))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetCoefficientsAndRange : set the matrix coefficients and range
//
// If this protocol object is inert, the protocol error inert is raised.
//
// Set the matrix coefficients and video range which defines the formula
// and the related constants used to derive red, green and blue signals.
// Usually coefficients correspond to MatrixCoefficients code points in
// H.273.
//
// Only combinations advertised by the compositor are allowed to be used as
// argument for this request. The "coefficients" protocol error is raised
// otherwise.
//
// A call to wl_surface.commit verifies that the pixel format and the
// coefficients-range combination in the committed surface contents are
// compatible, if contents exist. The "pixel_format" protocol error is
// raised otherwise.
//
// A pixel format is compatible with the coefficients-range combination if
// the related equations and conventions as defined in H.273 can produce
// the color channels (RGB or YCbCr) of the pixel format.
//
// For the definition of the supported combination, see the
// wp_color_representation_surface_v1::coefficients and
// wp_color_representation_surface_v1::range enums.
//
// The coefficients-range combination is double-buffered, see
// wl_surface.commit.
//
//	coefficients: matrix coefficients
//	_range: range
func (i *ColorRepresentationSurface) SetCoefficientsAndRange(coefficients, _range uint32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(coefficients))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_range))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetChromaLocation : set the chroma location
//
// If this protocol object is inert, the protocol error inert is raised.
//
// Set the chroma location type which defines the position of downsampled
// chroma samples, corresponding to Chroma420SampleLocType code points in
// H.273.
//
// An invalid chroma location enum value raises the "chroma_location"
// protocol error.
//
// A call to wl_surface.commit verifies that the pixel format and chroma
// location type in the committed surface contents are compatible, if
// contents exist. The "pixel_format" protocol error is raised otherwise.
//
// For the definition of the supported chroma location types, see the
// wp_color_representation_surface_v1::chroma_location enum.
//
// The chroma location type is double-buffered, see wl_surface.commit.
//
//	chromaLocation: chroma sample location
func (i *ColorRepresentationSurface) SetChromaLocation(chromaLocation uint32) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(chromaLocation))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ColorRepresentationSurfaceError uint32

// ColorRepresentationSurfaceError : protocol errors
const (
	// ColorRepresentationSurfaceErrorAlphaMode : unsupported alpha mode
	ColorRepresentationSurfaceErrorAlphaMode ColorRepresentationSurfaceError = 1
	// ColorRepresentationSurfaceErrorCoefficients : unsupported coefficients
	ColorRepresentationSurfaceErrorCoefficients ColorRepresentationSurfaceError = 2
	// ColorRepresentationSurfaceErrorPixelFormat : the pixel format and a set value are incompatible
	ColorRepresentationSurfaceErrorPixelFormat ColorRepresentationSurfaceError = 3
	// ColorRepresentationSurfaceErrorInert : forbidden request on inert object
	ColorRepresentationSurfaceErrorInert ColorRepresentationSurfaceError = 4
	// ColorRepresentationSurfaceErrorChromaLocation : invalid chroma location
	ColorRepresentationSurfaceErrorChromaLocation ColorRepresentationSurfaceError = 5
)

func (e ColorRepresentationSurfaceError) Name() string {
	switch e {
	case ColorRepresentationSurfaceErrorAlphaMode:
		return "alpha_mode"
	case ColorRepresentationSurfaceErrorCoefficients:
		return "coefficients"
	case ColorRepresentationSurfaceErrorPixelFormat:
		return "pixel_format"
	case ColorRepresentationSurfaceErrorInert:
		return "inert"
	case ColorRepresentationSurfaceErrorChromaLocation:
		return "chroma_location"
	default:
		return ""
	}
}

func (e ColorRepresentationSurfaceError) Value() string {
	switch e {
	case ColorRepresentationSurfaceErrorAlphaMode:
		return "1"
	case ColorRepresentationSurfaceErrorCoefficients:
		return "2"
	case ColorRepresentationSurfaceErrorPixelFormat:
		return "3"
	case ColorRepresentationSurfaceErrorInert:
		return "4"
	case ColorRepresentationSurfaceErrorChromaLocation:
		return "5"
	default:
		return ""
	}
}

func (e ColorRepresentationSurfaceError) String() string {
	return e.Name() + "=" + e.Value()
}

type ColorRepresentationSurfaceAlphaMode uint32

// ColorRepresentationSurfaceAlphaMode : alpha mode
//
// Specifies how the alpha channel affects the color channels.
const (
	ColorRepresentationSurfaceAlphaModePremultipliedElectrical ColorRepresentationSurfaceAlphaMode = 0
	ColorRepresentationSurfaceAlphaModePremultipliedOptical    ColorRepresentationSurfaceAlphaMode = 1
	ColorRepresentationSurfaceAlphaModeStraight                ColorRepresentationSurfaceAlphaMode = 2
)

func (e ColorRepresentationSurfaceAlphaMode) Name() string {
	switch e {
	case ColorRepresentationSurfaceAlphaModePremultipliedElectrical:
		return "premultiplied_electrical"
	case ColorRepresentationSurfaceAlphaModePremultipliedOptical:
		return "premultiplied_optical"
	case ColorRepresentationSurfaceAlphaModeStraight:
		return "straight"
	default:
		return ""
	}
}

func (e ColorRepresentationSurfaceAlphaMode) Value() string {
	switch e {
	case ColorRepresentationSurfaceAlphaModePremultipliedElectrical:
		return "0"
	case ColorRepresentationSurfaceAlphaModePremultipliedOptical:
		return "1"
	case ColorRepresentationSurfaceAlphaModeStraight:
		return "2"
	default:
		return ""
	}
}

func (e ColorRepresentationSurfaceAlphaMode) String() string {
	return e.Name() + "=" + e.Value()
}

type ColorRepresentationSurfaceCoefficients uint32

// ColorRepresentationSurfaceCoefficients : named coefficients
//
// Named matrix coefficients used to encode well-known sets of
// coefficients. H.273 is the authority, when it comes to the exact values
// of coefficients and authoritative specifications, where an equivalent
// code point exists.
//
// A value of 0 is invalid and will never be present in the list of enums.
//
// Descriptions do list the specifications for convenience.
const (
	ColorRepresentationSurfaceCoefficientsIdentity ColorRepresentationSurfaceCoefficients = 1
	ColorRepresentationSurfaceCoefficientsBt709    ColorRepresentationSurfaceCoefficients = 2
	ColorRepresentationSurfaceCoefficientsFcc      ColorRepresentationSurfaceCoefficients = 3
	ColorRepresentationSurfaceCoefficientsBt601    ColorRepresentationSurfaceCoefficients = 4
	ColorRepresentationSurfaceCoefficientsSmpte240 ColorRepresentationSurfaceCoefficients = 5
	ColorRepresentationSurfaceCoefficientsBt2020   ColorRepresentationSurfaceCoefficients = 6
	ColorRepresentationSurfaceCoefficientsBt2020Cl ColorRepresentationSurfaceCoefficients = 7
	ColorRepresentationSurfaceCoefficientsIctcp    ColorRepresentationSurfaceCoefficients = 8
)

func (e ColorRepresentationSurfaceCoefficients) Name() string {
	switch e {
	case ColorRepresentationSurfaceCoefficientsIdentity:
		return "identity"
	case ColorRepresentationSurfaceCoefficientsBt709:
		return "bt709"
	case ColorRepresentationSurfaceCoefficientsFcc:
		return "fcc"
	case ColorRepresentationSurfaceCoefficientsBt601:
		return "bt601"
	case ColorRepresentationSurfaceCoefficientsSmpte240:
		return "smpte240"
	case ColorRepresentationSurfaceCoefficientsBt2020:
		return "bt2020"
	case ColorRepresentationSurfaceCoefficientsBt2020Cl:
		return "bt2020_cl"
	case ColorRepresentationSurfaceCoefficientsIctcp:
		return "ictcp"
	default:
		return ""
	}
}

func (e ColorRepresentationSurfaceCoefficients) Value() string {
	switch e {
	case ColorRepresentationSurfaceCoefficientsIdentity:
		return "1"
	case ColorRepresentationSurfaceCoefficientsBt709:
		return "2"
	case ColorRepresentationSurfaceCoefficientsFcc:
		return "3"
	case ColorRepresentationSurfaceCoefficientsBt601:
		return "4"
	case ColorRepresentationSurfaceCoefficientsSmpte240:
		return "5"
	case ColorRepresentationSurfaceCoefficientsBt2020:
		return "6"
	case ColorRepresentationSurfaceCoefficientsBt2020Cl:
		return "7"
	case ColorRepresentationSurfaceCoefficientsIctcp:
		return "8"
	default:
		return ""
	}
}

func (e ColorRepresentationSurfaceCoefficients) String() string {
	return e.Name() + "=" + e.Value()
}

type ColorRepresentationSurfaceRange uint32

// ColorRepresentationSurfaceRange : Color range values
//
// Possible color range values.
//
// A value of 0 is invalid and will never be present in the list of enums.
const (
	// ColorRepresentationSurfaceRangeFull : Full color range
	ColorRepresentationSurfaceRangeFull ColorRepresentationSurfaceRange = 1
	// ColorRepresentationSurfaceRangeLimited : Limited color range
	ColorRepresentationSurfaceRangeLimited ColorRepresentationSurfaceRange = 2
)

func (e ColorRepresentationSurfaceRange) Name() string {
	switch e {
	case ColorRepresentationSurfaceRangeFull:
		return "full"
	case ColorRepresentationSurfaceRangeLimited:
		return "limited"
	default:
		return ""
	}
}

func (e ColorRepresentationSurfaceRange) Value() string {
	switch e {
	case ColorRepresentationSurfaceRangeFull:
		return "1"
	case ColorRepresentationSurfaceRangeLimited:
		return "2"
	default:
		return ""
	}
}

func (e ColorRepresentationSurfaceRange) String() string {
	return e.Name() + "=" + e.Value()
}

type ColorRepresentationSurfaceChromaLocation uint32

// ColorRepresentationSurfaceChromaLocation : Chroma sample location for 4:2:0 YCbCr
//
// Chroma sample location as defined by H.273 Chroma420SampleLocType.
//
// A value of 0 is invalid and will never be present in the list of enums.
//
// The descriptions list the matching Vulkan VkChromaLocation combinations
// for convenience.
const (
	ColorRepresentationSurfaceChromaLocationType0 ColorRepresentationSurfaceChromaLocation = 1
	ColorRepresentationSurfaceChromaLocationType1 ColorRepresentationSurfaceChromaLocation = 2
	ColorRepresentationSurfaceChromaLocationType2 ColorRepresentationSurfaceChromaLocation = 3
	ColorRepresentationSurfaceChromaLocationType3 ColorRepresentationSurfaceChromaLocation = 4
	ColorRepresentationSurfaceChromaLocationType4 ColorRepresentationSurfaceChromaLocation = 5
	ColorRepresentationSurfaceChromaLocationType5 ColorRepresentationSurfaceChromaLocation = 6
)

func (e ColorRepresentationSurfaceChromaLocation) Name() string {
	switch e {
	case ColorRepresentationSurfaceChromaLocationType0:
		return "type_0"
	case ColorRepresentationSurfaceChromaLocationType1:
		return "type_1"
	case ColorRepresentationSurfaceChromaLocationType2:
		return "type_2"
	case ColorRepresentationSurfaceChromaLocationType3:
		return "type_3"
	case ColorRepresentationSurfaceChromaLocationType4:
		return "type_4"
	case ColorRepresentationSurfaceChromaLocationType5:
		return "type_5"
	default:
		return ""
	}
}

func (e ColorRepresentationSurfaceChromaLocation) Value() string {
	switch e {
	case ColorRepresentationSurfaceChromaLocationType0:
		return "1"
	case ColorRepresentationSurfaceChromaLocationType1:
		return "2"
	case ColorRepresentationSurfaceChromaLocationType2:
		return "3"
	case ColorRepresentationSurfaceChromaLocationType3:
		return "4"
	case ColorRepresentationSurfaceChromaLocationType4:
		return "5"
	case ColorRepresentationSurfaceChromaLocationType5:
		return "6"
	default:
		return ""
	}
}

func (e ColorRepresentationSurfaceChromaLocation) String() string {
	return e.Name() + "=" + e.Value()
}
