// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/ext-foreign-toplevel-list/ext-foreign-toplevel-list-v1.xml
//
// ext_foreign_toplevel_list_v1 Protocol Copyright:
//
// Copyright © 2018 Ilia Bozhinov
// Copyright © 2020 Isaac Freund
// Copyright © 2022 wb9688
// Copyright © 2023 i509VCB
//
// Permission to use, copy, modify, distribute, and sell this
// software and its documentation for any purpose is hereby granted
// without fee, provided that the above copyright notice appear in
// all copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// the copyright holders not be used in advertising or publicity
// pertaining to distribution of the software without specific,
// written prior permission.  The copyright holders make no
// representations about the suitability of this software for any
// purpose.  It is provided "as is" without express or implied
// warranty.
//
// THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
// SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
// SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
// AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
// THIS SOFTWARE.

package ext_foreign_toplevel_list

import "github.com/SpinningVinyl/go-wayland/wayland/client"

// ForeignToplevelList : list toplevels
//
// A toplevel is defined as a surface with a role similar to xdg_toplevel.
// XWayland surfaces may be treated like toplevels in this protocol.
//
// After a client binds the ext_foreign_toplevel_list_v1, each mapped
// toplevel window will be sent using the ext_foreign_toplevel_list_v1.toplevel
// event.
//
// Clients which only care about the current state can perform a roundtrip after
// binding this global.
//
// For each instance of ext_foreign_toplevel_list_v1, the compositor must
// create a new ext_foreign_toplevel_handle_v1 object for each mapped toplevel.
//
// If a compositor implementation sends the ext_foreign_toplevel_list_v1.finished
// event after the global is bound, the compositor must not send any
// ext_foreign_toplevel_list_v1.toplevel events.
type ForeignToplevelList struct {
	client.BaseProxy
	toplevelHandler ForeignToplevelListToplevelHandlerFunc
	finishedHandler ForeignToplevelListFinishedHandlerFunc
}

// NewForeignToplevelList : list toplevels
//
// A toplevel is defined as a surface with a role similar to xdg_toplevel.
// XWayland surfaces may be treated like toplevels in this protocol.
//
// After a client binds the ext_foreign_toplevel_list_v1, each mapped
// toplevel window will be sent using the ext_foreign_toplevel_list_v1.toplevel
// event.
//
// Clients which only care about the current state can perform a roundtrip after
// binding this global.
//
// For each instance of ext_foreign_toplevel_list_v1, the compositor must
// create a new ext_foreign_toplevel_handle_v1 object for each mapped toplevel.
//
// If a compositor implementation sends the ext_foreign_toplevel_list_v1.finished
// event after the global is bound, the compositor must not send any
// ext_foreign_toplevel_list_v1.toplevel events.
func NewForeignToplevelList(ctx *client.Context) *ForeignToplevelList {
	extForeignToplevelListV1 := &ForeignToplevelList{}
	ctx.Register(extForeignToplevelListV1)
	return extForeignToplevelListV1
}

// Stop : stop sending events
//
// This request indicates that the client no longer wishes to receive
// events for new toplevels.
//
// The Wayland protocol is asynchronous, meaning the compositor may send
// further toplevel events until the stop request is processed.
// The client should wait for a ext_foreign_toplevel_list_v1.finished
// event before destroying this object.
func (i *ForeignToplevelList) Stop() error {
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy : destroy the ext_foreign_toplevel_list_v1 object
//
// This request should be called either when the client will no longer
// use the ext_foreign_toplevel_list_v1 or after the finished event
// has been received to allow destruction of the object.
//
// If a client wishes to destroy this object it should send a
// ext_foreign_toplevel_list_v1.stop request and wait for a ext_foreign_toplevel_list_v1.finished
// event, then destroy the handles and then this object.
func (i *ForeignToplevelList) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ForeignToplevelListToplevelEvent : a toplevel has been created
//
// This event is emitted whenever a new toplevel window is created. It is
// emitted for all toplevels, regardless of the app that has created them.
//
// All initial properties of the toplevel (identifier, title, app_id) will be sent
// immediately after this event using the corresponding events for
// ext_foreign_toplevel_handle_v1. The compositor will use the
// ext_foreign_toplevel_handle_v1.done event to indicate when all data has
// been sent.
type ForeignToplevelListToplevelEvent struct {
	Toplevel *ForeignToplevelHandle
}
type ForeignToplevelListToplevelHandlerFunc func(ForeignToplevelListToplevelEvent)

// SetToplevelHandler : sets handler for ForeignToplevelListToplevelEvent
func (i *ForeignToplevelList) SetToplevelHandler(f ForeignToplevelListToplevelHandlerFunc) {
	i.toplevelHandler = f
}

// ForeignToplevelListFinishedEvent : the compositor has finished with the toplevel manager
//
// This event indicates that the compositor is done sending events
// to this object. The client should destroy the object.
// See ext_foreign_toplevel_list_v1.destroy for more information.
//
// The compositor must not send any more toplevel events after this event.
type ForeignToplevelListFinishedEvent struct{}
type ForeignToplevelListFinishedHandlerFunc func(ForeignToplevelListFinishedEvent)

// SetFinishedHandler : sets handler for ForeignToplevelListFinishedEvent
func (i *ForeignToplevelList) SetFinishedHandler(f ForeignToplevelListFinishedHandlerFunc) {
	i.finishedHandler = f
}

func (i *ForeignToplevelList) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		var e ForeignToplevelListToplevelEvent
		l := 0
		e.Toplevel = new(ForeignToplevelHandle)
		i.Context().RegisterServer(e.Toplevel, client.Uint32(data[l:l+4]))
		l += 4

		if i.toplevelHandler != nil {
			i.toplevelHandler(e)
		}
	case 1:
		if i.finishedHandler == nil {
			return
		}
		var e ForeignToplevelListFinishedEvent

		i.finishedHandler(e)
	}
}

// ForeignToplevelHandle : a mapped toplevel
//
// A ext_foreign_toplevel_handle_v1 object represents a mapped toplevel
// window. A single app may have multiple mapped toplevels.
type ForeignToplevelHandle struct {
	client.BaseProxy
	closedHandler     ForeignToplevelHandleClosedHandlerFunc
	doneHandler       ForeignToplevelHandleDoneHandlerFunc
	titleHandler      ForeignToplevelHandleTitleHandlerFunc
	appIdHandler      ForeignToplevelHandleAppIdHandlerFunc
	identifierHandler ForeignToplevelHandleIdentifierHandlerFunc
}

// NewForeignToplevelHandle : a mapped toplevel
//
// A ext_foreign_toplevel_handle_v1 object represents a mapped toplevel
// window. A single app may have multiple mapped toplevels.
func NewForeignToplevelHandle(ctx *client.Context) *ForeignToplevelHandle {
	extForeignToplevelHandleV1 := &ForeignToplevelHandle{}
	ctx.Register(extForeignToplevelHandleV1)
	return extForeignToplevelHandleV1
}

// Destroy : destroy the ext_foreign_toplevel_handle_v1 object
//
// This request should be used when the client will no longer use the handle
// or after the closed event has been received to allow destruction of the
// object.
//
// When a handle is destroyed, a new handle may not be created by the server
// until the toplevel is unmapped and then remapped. Destroying a toplevel handle
// is not recommended unless the client is cleaning up child objects
// before destroying the ext_foreign_toplevel_list_v1 object, the toplevel
// was closed or the toplevel handle will not be used in the future.
//
// Other protocols which extend the ext_foreign_toplevel_handle_v1
// interface should require destructors for extension interfaces be
// called before allowing the toplevel handle to be destroyed.
func (i *ForeignToplevelHandle) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ForeignToplevelHandleClosedEvent : the toplevel has been closed
//
// The server will emit no further events on the ext_foreign_toplevel_handle_v1
// after this event. Any requests received aside from the destroy request must
// be ignored. Upon receiving this event, the client should destroy the handle.
//
// Other protocols which extend the ext_foreign_toplevel_handle_v1
// interface must also ignore requests other than destructors.
type ForeignToplevelHandleClosedEvent struct{}
type ForeignToplevelHandleClosedHandlerFunc func(ForeignToplevelHandleClosedEvent)

// SetClosedHandler : sets handler for ForeignToplevelHandleClosedEvent
func (i *ForeignToplevelHandle) SetClosedHandler(f ForeignToplevelHandleClosedHandlerFunc) {
	i.closedHandler = f
}

// ForeignToplevelHandleDoneEvent : all information about the toplevel has been sent
//
// This event is sent after all changes in the toplevel state have
// been sent.
//
// This allows changes to the ext_foreign_toplevel_handle_v1 properties
// to be atomically applied. Other protocols which extend the
// ext_foreign_toplevel_handle_v1 interface may use this event to also
// atomically apply any pending state.
//
// This event must not be sent after the ext_foreign_toplevel_handle_v1.closed
// event.
type ForeignToplevelHandleDoneEvent struct{}
type ForeignToplevelHandleDoneHandlerFunc func(ForeignToplevelHandleDoneEvent)

// SetDoneHandler : sets handler for ForeignToplevelHandleDoneEvent
func (i *ForeignToplevelHandle) SetDoneHandler(f ForeignToplevelHandleDoneHandlerFunc) {
	i.doneHandler = f
}

// ForeignToplevelHandleTitleEvent : title change
//
// The title of the toplevel has changed.
//
// The configured state must not be applied immediately. See
// ext_foreign_toplevel_handle_v1.done for details.
type ForeignToplevelHandleTitleEvent struct {
	Title string
}
type ForeignToplevelHandleTitleHandlerFunc func(ForeignToplevelHandleTitleEvent)

// SetTitleHandler : sets handler for ForeignToplevelHandleTitleEvent
func (i *ForeignToplevelHandle) SetTitleHandler(f ForeignToplevelHandleTitleHandlerFunc) {
	i.titleHandler = f
}

// ForeignToplevelHandleAppIdEvent : app_id change
//
// The app id of the toplevel has changed.
//
// The configured state must not be applied immediately. See
// ext_foreign_toplevel_handle_v1.done for details.
type ForeignToplevelHandleAppIdEvent struct {
	AppId string
}
type ForeignToplevelHandleAppIdHandlerFunc func(ForeignToplevelHandleAppIdEvent)

// SetAppIdHandler : sets handler for ForeignToplevelHandleAppIdEvent
func (i *ForeignToplevelHandle) SetAppIdHandler(f ForeignToplevelHandleAppIdHandlerFunc) {
	i.appIdHandler = f
}

// ForeignToplevelHandleIdentifierEvent : a stable identifier for a toplevel
//
// This identifier is used to check if two or more toplevel handles belong
// to the same toplevel.
//
// The identifier is useful for command line tools or privileged clients
// which may need to reference an exact toplevel across processes or
// instances of the ext_foreign_toplevel_list_v1 global.
//
// The compositor must only send this event when the handle is created.
//
// The identifier must be unique per toplevel and its handles. Two different
// toplevels must not have the same identifier. The identifier is only valid
// as long as the toplevel is mapped. If the toplevel is unmapped the identifier
// must not be reused. An identifier must not be reused by the compositor to
// ensure there are no races when sharing identifiers between processes.
//
// An identifier is a string that contains up to 32 printable ASCII bytes.
// An identifier must not be an empty string. It is recommended that a
// compositor includes an opaque generation value in identifiers. How the
// generation value is used when generating the identifier is implementation
// dependent.
type ForeignToplevelHandleIdentifierEvent struct {
	Identifier string
}
type ForeignToplevelHandleIdentifierHandlerFunc func(ForeignToplevelHandleIdentifierEvent)

// SetIdentifierHandler : sets handler for ForeignToplevelHandleIdentifierEvent
func (i *ForeignToplevelHandle) SetIdentifierHandler(f ForeignToplevelHandleIdentifierHandlerFunc) {
	i.identifierHandler = f
}

func (i *ForeignToplevelHandle) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.closedHandler == nil {
			return
		}
		var e ForeignToplevelHandleClosedEvent

		i.closedHandler(e)
	case 1:
		if i.doneHandler == nil {
			return
		}
		var e ForeignToplevelHandleDoneEvent

		i.doneHandler(e)
	case 2:
		if i.titleHandler == nil {
			return
		}
		var e ForeignToplevelHandleTitleEvent
		l := 0
		titleLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Title = client.String(data[l : l+titleLen])
		l += titleLen

		i.titleHandler(e)
	case 3:
		if i.appIdHandler == nil {
			return
		}
		var e ForeignToplevelHandleAppIdEvent
		l := 0
		appIdLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.AppId = client.String(data[l : l+appIdLen])
		l += appIdLen

		i.appIdHandler(e)
	case 4:
		if i.identifierHandler == nil {
			return
		}
		var e ForeignToplevelHandleIdentifierEvent
		l := 0
		identifierLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Identifier = client.String(data[l : l+identifierLen])
		l += identifierLen

		i.identifierHandler(e)
	}
}
