// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/ext-transient-seat/ext-transient-seat-v1.xml
//
// ext_transient_seat_v1 Protocol Copyright:
//
// Copyright © 2020 - 2023 Andri Yngvason
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package ext_transient_seat

import "github.com/SpinningVinyl/go-wayland/wayland/client"

// TransientSeatManager : transient seat manager
//
// The transient seat manager creates short-lived seats.
type TransientSeatManager struct {
	client.BaseProxy
}

// NewTransientSeatManager : transient seat manager
//
// The transient seat manager creates short-lived seats.
func NewTransientSeatManager(ctx *client.Context) *TransientSeatManager {
	extTransientSeatManagerV1 := &TransientSeatManager{}
	ctx.Register(extTransientSeatManagerV1)
	return extTransientSeatManagerV1
}

// Create : create a transient seat
//
// Create a new seat that is removed when the client side transient seat
// object is destroyed.
//
// The actual seat may be removed sooner, in which case the transient seat
// object shall become inert.
func (i *TransientSeatManager) Create() (*TransientSeat, error) {
	seat := NewTransientSeat(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return seat, err
}

// Destroy : destroy the manager
//
// Destroy the manager.
//
// All objects created by the manager will remain valid until they are
// destroyed themselves.
func (i *TransientSeatManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// TransientSeat : transient seat handle
//
// When the transient seat handle is destroyed, the seat itself will also be
// destroyed.
type TransientSeat struct {
	client.BaseProxy
	readyHandler  TransientSeatReadyHandlerFunc
	deniedHandler TransientSeatDeniedHandlerFunc
}

// NewTransientSeat : transient seat handle
//
// When the transient seat handle is destroyed, the seat itself will also be
// destroyed.
func NewTransientSeat(ctx *client.Context) *TransientSeat {
	extTransientSeatV1 := &TransientSeat{}
	ctx.Register(extTransientSeatV1)
	return extTransientSeatV1
}

// Destroy : destroy transient seat
//
// When the transient seat object is destroyed by the client, the
// associated seat created by the compositor is also destroyed.
func (i *TransientSeat) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// TransientSeatReadyEvent : transient seat is ready
//
// This event advertises the global name for the wl_seat to be used with
// wl_registry_bind.
//
// It is sent exactly once, immediately after the transient seat is created
// and the new "wl_seat" global is advertised, if and only if the creation
// of the transient seat was allowed.
type TransientSeatReadyEvent struct {
	GlobalName uint32
}
type TransientSeatReadyHandlerFunc func(TransientSeatReadyEvent)

// SetReadyHandler : sets handler for TransientSeatReadyEvent
func (i *TransientSeat) SetReadyHandler(f TransientSeatReadyHandlerFunc) {
	i.readyHandler = f
}

// TransientSeatDeniedEvent : transient seat creation denied
//
// The event informs the client that the compositor denied its request to
// create a transient seat.
//
// It is sent exactly once, immediately after the transient seat object is
// created, if and only if the creation of the transient seat was denied.
//
// After receiving this event, the client should destroy the object.
type TransientSeatDeniedEvent struct{}
type TransientSeatDeniedHandlerFunc func(TransientSeatDeniedEvent)

// SetDeniedHandler : sets handler for TransientSeatDeniedEvent
func (i *TransientSeat) SetDeniedHandler(f TransientSeatDeniedHandlerFunc) {
	i.deniedHandler = f
}

func (i *TransientSeat) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.readyHandler == nil {
			return
		}
		var e TransientSeatReadyEvent
		l := 0
		e.GlobalName = client.Uint32(data[l : l+4])
		l += 4

		i.readyHandler(e)
	case 1:
		if i.deniedHandler == nil {
			return
		}
		var e TransientSeatDeniedEvent

		i.deniedHandler(e)
	}
}
