// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/commit-timing/commit-timing-v1.xml
//
// commit_timing_v1 Protocol Copyright:
//
// Copyright © 2023 Valve Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package commit_timing

import "github.com/SpinningVinyl/go-wayland/wayland/client"

// CommitTimingManager : commit timing
//
// When a compositor latches on to new content updates it will check for
// any number of requirements of the available content updates (such as
// fences of all buffers being signalled) to consider the update ready.
//
// This protocol provides a method for adding a time constraint to surface
// content. This constraint indicates to the compositor that a content
// update should be presented as closely as possible to, but not before,
// a specified time.
//
// This protocol does not change the Wayland property that content
// updates are applied in the order they are received, even when some
// content updates contain timestamps and others do not.
//
// To provide timestamps, this global factory interface must be used to
// acquire a wp_commit_timing_v1 object for a surface, which may then be
// used to provide timestamp information for commits.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type CommitTimingManager struct {
	client.BaseProxy
}

// NewCommitTimingManager : commit timing
//
// When a compositor latches on to new content updates it will check for
// any number of requirements of the available content updates (such as
// fences of all buffers being signalled) to consider the update ready.
//
// This protocol provides a method for adding a time constraint to surface
// content. This constraint indicates to the compositor that a content
// update should be presented as closely as possible to, but not before,
// a specified time.
//
// This protocol does not change the Wayland property that content
// updates are applied in the order they are received, even when some
// content updates contain timestamps and others do not.
//
// To provide timestamps, this global factory interface must be used to
// acquire a wp_commit_timing_v1 object for a surface, which may then be
// used to provide timestamp information for commits.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
func NewCommitTimingManager(ctx *client.Context) *CommitTimingManager {
	wpCommitTimingManagerV1 := &CommitTimingManager{}
	ctx.Register(wpCommitTimingManagerV1)
	return wpCommitTimingManagerV1
}

// Destroy : unbind from the commit timing interface
//
// Informs the server that the client will no longer be using
// this protocol object. Existing objects created by this object
// are not affected.
func (i *CommitTimingManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetTimer : request commit timer interface for surface
//
// Establish a timing controller for a surface.
//
// Only one commit timer can be created for a surface, or a
// commit_timer_exists protocol error will be generated.
func (i *CommitTimingManager) GetTimer(surface *client.Surface) (*CommitTimer, error) {
	id := NewCommitTimer(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

type CommitTimingManagerError uint32

// CommitTimingManagerError :
const (
	// CommitTimingManagerErrorCommitTimerExists : commit timer already exists for surface
	CommitTimingManagerErrorCommitTimerExists CommitTimingManagerError = 0
)

func (e CommitTimingManagerError) Name() string {
	switch e {
	case CommitTimingManagerErrorCommitTimerExists:
		return "commit_timer_exists"
	default:
		return ""
	}
}

func (e CommitTimingManagerError) Value() string {
	switch e {
	case CommitTimingManagerErrorCommitTimerExists:
		return "0"
	default:
		return ""
	}
}

func (e CommitTimingManagerError) String() string {
	return e.Name() + "=" + e.Value()
}

// CommitTimer : Surface commit timer
//
// An object to set a time constraint for a content update on a surface.
type CommitTimer struct {
	client.BaseProxy
}

// NewCommitTimer : Surface commit timer
//
// An object to set a time constraint for a content update on a surface.
func NewCommitTimer(ctx *client.Context) *CommitTimer {
	wpCommitTimerV1 := &CommitTimer{}
	ctx.Register(wpCommitTimerV1)
	return wpCommitTimerV1
}

// SetTimestamp : Specify time the following commit takes effect
//
// Provide a timing constraint for a surface content update.
//
// A set_timestamp request may be made before a wl_surface.commit to
// tell the compositor that the content is intended to be presented
// as closely as possible to, but not before, the specified time.
// The time is in the domain of the compositor's presentation clock.
//
// An invalid_timestamp error will be generated for invalid tv_nsec.
//
// If a timestamp already exists on the surface, a timestamp_exists
// error is generated.
//
// Requesting set_timestamp after the commit_timer object's surface is
// destroyed will generate a "surface_destroyed" error.
//
//	tvSecHi: high 32 bits of the seconds part of target time
//	tvSecLo: low 32 bits of the seconds part of target time
//	tvNsec: nanoseconds part of target time
func (i *CommitTimer) SetTimestamp(tvSecHi, tvSecLo, tvNsec uint32) error {
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(tvSecHi))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(tvSecLo))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(tvNsec))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy : Destroy the timer
//
// Informs the server that the client will no longer be using
// this protocol object.
//
// Existing timing constraints are not affected by the destruction.
func (i *CommitTimer) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type CommitTimerError uint32

// CommitTimerError :
const (
	// CommitTimerErrorInvalidTimestamp : timestamp contains an invalid value
	CommitTimerErrorInvalidTimestamp CommitTimerError = 0
	// CommitTimerErrorTimestampExists : timestamp exists
	CommitTimerErrorTimestampExists CommitTimerError = 1
	// CommitTimerErrorSurfaceDestroyed : the associated surface no longer exists
	CommitTimerErrorSurfaceDestroyed CommitTimerError = 2
)

func (e CommitTimerError) Name() string {
	switch e {
	case CommitTimerErrorInvalidTimestamp:
		return "invalid_timestamp"
	case CommitTimerErrorTimestampExists:
		return "timestamp_exists"
	case CommitTimerErrorSurfaceDestroyed:
		return "surface_destroyed"
	default:
		return ""
	}
}

func (e CommitTimerError) Value() string {
	switch e {
	case CommitTimerErrorInvalidTimestamp:
		return "0"
	case CommitTimerErrorTimestampExists:
		return "1"
	case CommitTimerErrorSurfaceDestroyed:
		return "2"
	default:
		return ""
	}
}

func (e CommitTimerError) String() string {
	return e.Name() + "=" + e.Value()
}
