// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/xdg-session-management/xdg-session-management-v1.xml
//
// xdg_session_management_v1 Protocol Copyright:
//
// Copyright 2018 Mike Blumenkrantz
// Copyright 2018 Samsung Electronics Co., Ltd
// Copyright 2018 Red Hat Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdg_session_management

import (
	"github.com/SpinningVinyl/go-wayland/wayland/client"
	xdg_shell "github.com/SpinningVinyl/go-wayland/wayland/stable/xdg-shell"
)

// SessionManager : manage sessions for applications
//
// The xdg_session_manager_v1 interface defines base requests for creating and
// managing a session for an application. Sessions persist across application
// and compositor restarts unless explicitly destroyed. A session is created
// for the purpose of maintaining an application's xdg_toplevel surfaces
// across compositor or application restarts. The compositor should remember
// as many states as possible for surfaces in a given session, but there is
// no requirement for which states must be remembered.
//
// Policies such as cache eviction are declared an implementation detail of
// the compositor. Clients should account for no longer existing sessions.
type SessionManager struct {
	client.BaseProxy
}

// NewSessionManager : manage sessions for applications
//
// The xdg_session_manager_v1 interface defines base requests for creating and
// managing a session for an application. Sessions persist across application
// and compositor restarts unless explicitly destroyed. A session is created
// for the purpose of maintaining an application's xdg_toplevel surfaces
// across compositor or application restarts. The compositor should remember
// as many states as possible for surfaces in a given session, but there is
// no requirement for which states must be remembered.
//
// Policies such as cache eviction are declared an implementation detail of
// the compositor. Clients should account for no longer existing sessions.
func NewSessionManager(ctx *client.Context) *SessionManager {
	xdgSessionManagerV1 := &SessionManager{}
	ctx.Register(xdgSessionManagerV1)
	return xdgSessionManagerV1
}

// Destroy : Destroy this object
//
// Destroy the manager object. The existing session objects will be
// unaffected.
func (i *SessionManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetSession : create or restore a session
//
// Create a session object corresponding to either an existing session
// identified by the given session identifier string or a new session.
// While the session object exists, the session is considered to be "in
// use".
//
// If an identifier string represents a session that is currently actively
// in use by the the same client, an 'in_use' error is raised. If some
// other client is currently using the same session, the new session will
// replace managing the associated state.
//
// If the reason is not a valid enum entry, the 'invalid_reason' protocol
// error is raised.
//
// NULL is passed to initiate a new session. If a session_id is passed
// which does not represent a valid session, the compositor treats it as if
// NULL had been passed.
//
// The session id string must be UTF-8 encoded. It is also limited by the
// maximum length of wayland messages (around 4KB). The 'invalid_session_id'
// protocol error will be raised if an invalid string is provided.
//
// A client is allowed to have any number of in use sessions at the same
// time.
//
//	reason: reason for session
//	sessionId: the session to restore
func (i *SessionManager) GetSession(reason uint32, sessionId string) (*Session, error) {
	id := NewSession(i.Context())
	const opcode = 1
	sessionIdLen := client.PaddedLen(len(sessionId) + 1)
	_reqBufLen := 8 + 4 + 4 + (4 + sessionIdLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(reason))
	l += 4
	client.PutString(_reqBuf[l:l+(4+sessionIdLen)], sessionId, sessionIdLen)
	l += (4 + sessionIdLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return id, err
}

type SessionManagerError uint32

// SessionManagerError :
const (
	// SessionManagerErrorInUse : a requested session is already in use
	SessionManagerErrorInUse SessionManagerError = 1
	// SessionManagerErrorInvalidSessionId : invalid session identifier
	SessionManagerErrorInvalidSessionId SessionManagerError = 2
	// SessionManagerErrorInvalidReason : invalid reason
	SessionManagerErrorInvalidReason SessionManagerError = 3
)

func (e SessionManagerError) Name() string {
	switch e {
	case SessionManagerErrorInUse:
		return "in_use"
	case SessionManagerErrorInvalidSessionId:
		return "invalid_session_id"
	case SessionManagerErrorInvalidReason:
		return "invalid_reason"
	default:
		return ""
	}
}

func (e SessionManagerError) Value() string {
	switch e {
	case SessionManagerErrorInUse:
		return "1"
	case SessionManagerErrorInvalidSessionId:
		return "2"
	case SessionManagerErrorInvalidReason:
		return "3"
	default:
		return ""
	}
}

func (e SessionManagerError) String() string {
	return e.Name() + "=" + e.Value()
}

type SessionManagerReason uint32

// SessionManagerReason : reason for getting a session
//
// The reason may determine in what way a session restores the window
// management state of associated toplevels.
//
// For example newly launched applications might be launched on the active
// workspace with restored size and position, while a recovered
// application might restore additional state such as active workspace and
// stacking order.
const (
	SessionManagerReasonLaunch         SessionManagerReason = 1
	SessionManagerReasonRecover        SessionManagerReason = 2
	SessionManagerReasonSessionRestore SessionManagerReason = 3
)

func (e SessionManagerReason) Name() string {
	switch e {
	case SessionManagerReasonLaunch:
		return "launch"
	case SessionManagerReasonRecover:
		return "recover"
	case SessionManagerReasonSessionRestore:
		return "session_restore"
	default:
		return ""
	}
}

func (e SessionManagerReason) Value() string {
	switch e {
	case SessionManagerReasonLaunch:
		return "1"
	case SessionManagerReasonRecover:
		return "2"
	case SessionManagerReasonSessionRestore:
		return "3"
	default:
		return ""
	}
}

func (e SessionManagerReason) String() string {
	return e.Name() + "=" + e.Value()
}

// Session : A session for an application
//
// A xdg_session_v1 object represents a session for an application. While the
// object exists, all surfaces which have been added to the session will
// have states stored by the compositor which can be reapplied at a later
// time. Two sessions cannot exist for the same identifier string.
//
// States for surfaces added to a session are automatically updated by the
// compositor when they are changed.
type Session struct {
	client.BaseProxy
	createdHandler  SessionCreatedHandlerFunc
	restoredHandler SessionRestoredHandlerFunc
	replacedHandler SessionReplacedHandlerFunc
}

// NewSession : A session for an application
//
// A xdg_session_v1 object represents a session for an application. While the
// object exists, all surfaces which have been added to the session will
// have states stored by the compositor which can be reapplied at a later
// time. Two sessions cannot exist for the same identifier string.
//
// States for surfaces added to a session are automatically updated by the
// compositor when they are changed.
func NewSession(ctx *client.Context) *Session {
	xdgSessionV1 := &Session{}
	ctx.Register(xdgSessionV1)
	return xdgSessionV1
}

// Destroy : Destroy the session
//
// Destroy a session object, preserving the current state but not continuing
// to make further updates if state changes occur. This makes the associated
// xdg_toplevel_session_v1 objects inert.
func (i *Session) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Remove : Remove the session
//
// Remove the session, making it no longer available for restoration. A
// compositor should in response to this request remove the data related to
// this session from its storage.
func (i *Session) Remove() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// AddToplevel : add a new surface to the session
//
// Attempt to add a given surface to the session. The passed name is used
// to identify what window is being restored, and may be used to store
// window specific state within the session.
//
// The name given to the toplevel must not correspond to any previously
// existing toplevel names in the session. If the name matches an already
// known toplevel name in the session, a 'name_in_use' protocol error will
// be raised.
//
// The toplevel object must not be added more than once to any session
// created by the client, otherwise the 'already_added' protocol error
// will be raised.
//
// This request will return a xdg_toplevel_session_v1 for later
// manipulation. As this resource is created from an empty initial state,
// compositors must not emit a xdg_toplevel_session_v1.restored event for
// resources created through this request.
//
// The name string must be UTF-8 encoded. It is also limited by the maximum
// length of wayland messages (around 4KB). The 'invalid_name' protocol
// error will be raised if an invalid string is provided.
//
//	name: name identifying the toplevel
func (i *Session) AddToplevel(toplevel *xdg_shell.Toplevel, name string) (*ToplevelSession, error) {
	id := NewToplevelSession(i.Context())
	const opcode = 2
	nameLen := client.PaddedLen(len(name) + 1)
	_reqBufLen := 8 + 4 + 4 + (4 + nameLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], toplevel.ID())
	l += 4
	client.PutString(_reqBuf[l:l+(4+nameLen)], name, nameLen)
	l += (4 + nameLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return id, err
}

// RestoreToplevel : restore a surface state
//
// Inform the compositor that the toplevel associated with the passed name
// should have its window management state restored.
//
// If the toplevel name was previously granted to another xdg_toplevel,
// the 'name_in_use' protocol error will be raised.
//
// The toplevel object must not be added more than once to any session
// created by the client, otherwise the 'already_added' protocol error
// will be raised.
//
// This request must be called prior to the first commit on the associated
// wl_surface after creating the toplevel, otherwise an 'already_mapped'
// error is raised.
//
// As part of the initial configure sequence, if the toplevel was
// successfully restored, a xdg_toplevel_session_v1.restored event is
// emitted. If the toplevel name was not known in the session, this request
// will be equivalent to the xdg_toplevel_session_v1.add_toplevel request,
// and no such event will be emitted. See the xdg_toplevel_session_v1.restored
// event for further details.
//
// The name string must be UTF-8 encoded. It is also limited by the maximum
// length of wayland messages (around 4KB). The 'invalid_name' protocol
// error will be raised if an invalid string is provided.
//
//	name: name identifying the toplevel
func (i *Session) RestoreToplevel(toplevel *xdg_shell.Toplevel, name string) (*ToplevelSession, error) {
	id := NewToplevelSession(i.Context())
	const opcode = 3
	nameLen := client.PaddedLen(len(name) + 1)
	_reqBufLen := 8 + 4 + 4 + (4 + nameLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], toplevel.ID())
	l += 4
	client.PutString(_reqBuf[l:l+(4+nameLen)], name, nameLen)
	l += (4 + nameLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return id, err
}

// RemoveToplevel : remove a surface from the session
//
// Remove a specified surface from the session and render any related
// xdg_toplevel_session_v1 object inert. The compositor should remove any
// data related to the toplevel in the corresponding session from its internal
// storage.
//
// The window is specified by its name in the session. The name string
// must be encoded in UTF-8, and it is limited in size by the maximum
// length of wayland messages (around 4KB).
//
//	name: name identifying the toplevel
func (i *Session) RemoveToplevel(name string) error {
	const opcode = 4
	nameLen := client.PaddedLen(len(name) + 1)
	_reqBufLen := 8 + (4 + nameLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+nameLen)], name, nameLen)
	l += (4 + nameLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

type SessionError uint32

// SessionError :
const (
	// SessionErrorNameInUse : toplevel name is already in use
	SessionErrorNameInUse SessionError = 1
	// SessionErrorAlreadyMapped : toplevel was already mapped when restored
	SessionErrorAlreadyMapped SessionError = 2
	// SessionErrorInvalidName : provided toplevel name is invalid
	SessionErrorInvalidName SessionError = 3
	// SessionErrorAlreadyAdded : toplevel already added
	SessionErrorAlreadyAdded SessionError = 4
)

func (e SessionError) Name() string {
	switch e {
	case SessionErrorNameInUse:
		return "name_in_use"
	case SessionErrorAlreadyMapped:
		return "already_mapped"
	case SessionErrorInvalidName:
		return "invalid_name"
	case SessionErrorAlreadyAdded:
		return "already_added"
	default:
		return ""
	}
}

func (e SessionError) Value() string {
	switch e {
	case SessionErrorNameInUse:
		return "1"
	case SessionErrorAlreadyMapped:
		return "2"
	case SessionErrorInvalidName:
		return "3"
	case SessionErrorAlreadyAdded:
		return "4"
	default:
		return ""
	}
}

func (e SessionError) String() string {
	return e.Name() + "=" + e.Value()
}

// SessionCreatedEvent : newly-created session id
//
// Emitted at most once some time after getting a new session object. It
// means that no previous state was restored, and a new session was created.
// The passed id can be persistently stored and used to restore previous
// sessions.
type SessionCreatedEvent struct {
	SessionId string
}
type SessionCreatedHandlerFunc func(SessionCreatedEvent)

// SetCreatedHandler : sets handler for SessionCreatedEvent
func (i *Session) SetCreatedHandler(f SessionCreatedHandlerFunc) {
	i.createdHandler = f
}

// SessionRestoredEvent : the session has been restored
//
// Emitted at most once some time after getting a new session object. It
// means that previous state was at least partially restored. The same id
// can again be used to restore previous sessions.
type SessionRestoredEvent struct{}
type SessionRestoredHandlerFunc func(SessionRestoredEvent)

// SetRestoredHandler : sets handler for SessionRestoredEvent
func (i *Session) SetRestoredHandler(f SessionRestoredHandlerFunc) {
	i.restoredHandler = f
}

// SessionReplacedEvent : the session has been replaced
//
// Emitted at most once, if the session was taken over by some other
// client. When this happens, the session and all its toplevel session
// objects become inert, and should be destroyed.
type SessionReplacedEvent struct{}
type SessionReplacedHandlerFunc func(SessionReplacedEvent)

// SetReplacedHandler : sets handler for SessionReplacedEvent
func (i *Session) SetReplacedHandler(f SessionReplacedHandlerFunc) {
	i.replacedHandler = f
}

func (i *Session) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.createdHandler == nil {
			return
		}
		var e SessionCreatedEvent
		l := 0
		sessionIdLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.SessionId = client.String(data[l : l+sessionIdLen])
		l += sessionIdLen

		i.createdHandler(e)
	case 1:
		if i.restoredHandler == nil {
			return
		}
		var e SessionRestoredEvent

		i.restoredHandler(e)
	case 2:
		if i.replacedHandler == nil {
			return
		}
		var e SessionReplacedEvent

		i.replacedHandler(e)
	}
}

// ToplevelSession : A session for an application
//
// A xdg_toplevel_session_v1 resource acts as a handle for the given
// toplevel in the session. It allows for receiving events after a
// toplevel state was restored, and has the requests to manage them.
type ToplevelSession struct {
	client.BaseProxy
	restoredHandler ToplevelSessionRestoredHandlerFunc
}

// NewToplevelSession : A session for an application
//
// A xdg_toplevel_session_v1 resource acts as a handle for the given
// toplevel in the session. It allows for receiving events after a
// toplevel state was restored, and has the requests to manage them.
func NewToplevelSession(ctx *client.Context) *ToplevelSession {
	xdgToplevelSessionV1 := &ToplevelSession{}
	ctx.Register(xdgToplevelSessionV1)
	return xdgToplevelSessionV1
}

// Destroy : Destroy the object
//
// Destroy the object. This has no effect over window management of the
// associated toplevel.
func (i *ToplevelSession) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Rename : change the name of toplevel session
//
// Renames the toplevel session. The new name can be used in subsequent requests
// to identify this session object. The state associated with this toplevel
// session will be preserved.
//
// If the xdg_session_v1 already contains a toplevel with the specified name,
// the 'name_in_use' protocol error will be raised.
//
//	name: new name to identify the toplevel
func (i *ToplevelSession) Rename(name string) error {
	const opcode = 1
	nameLen := client.PaddedLen(len(name) + 1)
	_reqBufLen := 8 + (4 + nameLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+nameLen)], name, nameLen)
	l += (4 + nameLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// ToplevelSessionRestoredEvent : a toplevel's session has been restored
//
// The "restored" event is emitted prior to the first
// xdg_toplevel.configure for the toplevel. It will only be emitted after
// xdg_session_v1.restore_toplevel, and the initial empty surface state has
// been applied, and it indicates that the surface's session is being
// restored with this configure event.
type ToplevelSessionRestoredEvent struct{}
type ToplevelSessionRestoredHandlerFunc func(ToplevelSessionRestoredEvent)

// SetRestoredHandler : sets handler for ToplevelSessionRestoredEvent
func (i *ToplevelSession) SetRestoredHandler(f ToplevelSessionRestoredHandlerFunc) {
	i.restoredHandler = f
}

func (i *ToplevelSession) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.restoredHandler == nil {
			return
		}
		var e ToplevelSessionRestoredEvent

		i.restoredHandler(e)
	}
}
