// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/ext-data-control/ext-data-control-v1.xml
//
// ext_data_control_v1 Protocol Copyright:
//
// Copyright © 2018 Simon Ser
// Copyright © 2019 Ivan Molodetskikh
// Copyright © 2024 Neal Gompa
//
// Permission to use, copy, modify, distribute, and sell this
// software and its documentation for any purpose is hereby granted
// without fee, provided that the above copyright notice appear in
// all copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// the copyright holders not be used in advertising or publicity
// pertaining to distribution of the software without specific,
// written prior permission.  The copyright holders make no
// representations about the suitability of this software for any
// purpose.  It is provided "as is" without express or implied
// warranty.
//
// THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
// SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
// SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
// AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
// THIS SOFTWARE.

package ext_data_control

import (
	"github.com/SpinningVinyl/go-wayland/wayland/client"
	"golang.org/x/sys/unix"
)

// DataControlManager : manager to control data devices
//
// This interface is a manager that allows creating per-seat data device
// controls.
type DataControlManager struct {
	client.BaseProxy
}

// NewDataControlManager : manager to control data devices
//
// This interface is a manager that allows creating per-seat data device
// controls.
func NewDataControlManager(ctx *client.Context) *DataControlManager {
	extDataControlManagerV1 := &DataControlManager{}
	ctx.Register(extDataControlManagerV1)
	return extDataControlManagerV1
}

// CreateDataSource : create a new data source
//
// Create a new data source.
func (i *DataControlManager) CreateDataSource() (*DataControlSource, error) {
	id := NewDataControlSource(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GetDataDevice : get a data device for a seat
//
// Create a data device that can be used to manage a seat's selection.
func (i *DataControlManager) GetDataDevice(seat *client.Seat) (*DataControlDevice, error) {
	id := NewDataControlDevice(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// Destroy : destroy the manager
//
// All objects created by the manager will still remain valid, until their
// appropriate destroy request has been called.
func (i *DataControlManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// DataControlDevice : manage a data device for a seat
//
// This interface allows a client to manage a seat's selection.
//
// When the seat is destroyed, this object becomes inert.
type DataControlDevice struct {
	client.BaseProxy
	dataOfferHandler        DataControlDeviceDataOfferHandlerFunc
	selectionHandler        DataControlDeviceSelectionHandlerFunc
	finishedHandler         DataControlDeviceFinishedHandlerFunc
	primarySelectionHandler DataControlDevicePrimarySelectionHandlerFunc
}

// NewDataControlDevice : manage a data device for a seat
//
// This interface allows a client to manage a seat's selection.
//
// When the seat is destroyed, this object becomes inert.
func NewDataControlDevice(ctx *client.Context) *DataControlDevice {
	extDataControlDeviceV1 := &DataControlDevice{}
	ctx.Register(extDataControlDeviceV1)
	return extDataControlDeviceV1
}

// SetSelection : copy data to the selection
//
// This request asks the compositor to set the selection to the data from
// the source on behalf of the client.
//
// The given source may not be used in any further set_selection or
// set_primary_selection requests. Attempting to use a previously used
// source triggers the used_source protocol error.
//
// To unset the selection, set the source to NULL.
func (i *DataControlDevice) SetSelection(source *DataControlSource) error {
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if source == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], source.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy : destroy this data device
//
// Destroys the data device object.
func (i *DataControlDevice) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetPrimarySelection : copy data to the primary selection
//
// This request asks the compositor to set the primary selection to the
// data from the source on behalf of the client.
//
// The given source may not be used in any further set_selection or
// set_primary_selection requests. Attempting to use a previously used
// source triggers the used_source protocol error.
//
// To unset the primary selection, set the source to NULL.
//
// The compositor will ignore this request if it does not support primary
// selection.
func (i *DataControlDevice) SetPrimarySelection(source *DataControlSource) error {
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if source == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], source.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type DataControlDeviceError uint32

// DataControlDeviceError :
const (
	// DataControlDeviceErrorUsedSource : source given to set_selection or set_primary_selection was already used before
	DataControlDeviceErrorUsedSource DataControlDeviceError = 1
)

func (e DataControlDeviceError) Name() string {
	switch e {
	case DataControlDeviceErrorUsedSource:
		return "used_source"
	default:
		return ""
	}
}

func (e DataControlDeviceError) Value() string {
	switch e {
	case DataControlDeviceErrorUsedSource:
		return "1"
	default:
		return ""
	}
}

func (e DataControlDeviceError) String() string {
	return e.Name() + "=" + e.Value()
}

// DataControlDeviceDataOfferEvent : introduce a new ext_data_control_offer
//
// The data_offer event introduces a new ext_data_control_offer object,
// which will subsequently be used in either the
// ext_data_control_device.selection event (for the regular clipboard
// selections) or the ext_data_control_device.primary_selection event (for
// the primary clipboard selections). Immediately following the
// ext_data_control_device.data_offer event, the new data_offer object
// will send out ext_data_control_offer.offer events to describe the MIME
// types it offers.
type DataControlDeviceDataOfferEvent struct {
	Id *DataControlOffer
}
type DataControlDeviceDataOfferHandlerFunc func(DataControlDeviceDataOfferEvent)

// SetDataOfferHandler : sets handler for DataControlDeviceDataOfferEvent
func (i *DataControlDevice) SetDataOfferHandler(f DataControlDeviceDataOfferHandlerFunc) {
	i.dataOfferHandler = f
}

// DataControlDeviceSelectionEvent : advertise new selection
//
// The selection event is sent out to notify the client of a new
// ext_data_control_offer for the selection for this device. The
// ext_data_control_device.data_offer and the ext_data_control_offer.offer
// events are sent out immediately before this event to introduce the data
// offer object. The selection event is sent to a client when a new
// selection is set. The ext_data_control_offer is valid until a new
// ext_data_control_offer or NULL is received. The client must destroy the
// previous selection ext_data_control_offer, if any, upon receiving this
// event. Regardless, the previous selection will be ignored once a new
// selection ext_data_control_offer is received.
//
// The first selection event is sent upon binding the
// ext_data_control_device object.
type DataControlDeviceSelectionEvent struct {
	Id *DataControlOffer
}
type DataControlDeviceSelectionHandlerFunc func(DataControlDeviceSelectionEvent)

// SetSelectionHandler : sets handler for DataControlDeviceSelectionEvent
func (i *DataControlDevice) SetSelectionHandler(f DataControlDeviceSelectionHandlerFunc) {
	i.selectionHandler = f
}

// DataControlDeviceFinishedEvent : this data control is no longer valid
//
// This data control object is no longer valid and should be destroyed by
// the client.
type DataControlDeviceFinishedEvent struct{}
type DataControlDeviceFinishedHandlerFunc func(DataControlDeviceFinishedEvent)

// SetFinishedHandler : sets handler for DataControlDeviceFinishedEvent
func (i *DataControlDevice) SetFinishedHandler(f DataControlDeviceFinishedHandlerFunc) {
	i.finishedHandler = f
}

// DataControlDevicePrimarySelectionEvent : advertise new primary selection
//
// The primary_selection event is sent out to notify the client of a new
// ext_data_control_offer for the primary selection for this device. The
// ext_data_control_device.data_offer and the ext_data_control_offer.offer
// events are sent out immediately before this event to introduce the data
// offer object. The primary_selection event is sent to a client when a
// new primary selection is set. The ext_data_control_offer is valid until
// a new ext_data_control_offer or NULL is received. The client must
// destroy the previous primary selection ext_data_control_offer, if any,
// upon receiving this event. Regardless, the previous primary selection
// will be ignored once a new primary selection ext_data_control_offer is
// received.
//
// If the compositor supports primary selection, the first
// primary_selection event is sent upon binding the
// ext_data_control_device object.
type DataControlDevicePrimarySelectionEvent struct {
	Id *DataControlOffer
}
type DataControlDevicePrimarySelectionHandlerFunc func(DataControlDevicePrimarySelectionEvent)

// SetPrimarySelectionHandler : sets handler for DataControlDevicePrimarySelectionEvent
func (i *DataControlDevice) SetPrimarySelectionHandler(f DataControlDevicePrimarySelectionHandlerFunc) {
	i.primarySelectionHandler = f
}

func (i *DataControlDevice) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		var e DataControlDeviceDataOfferEvent
		l := 0
		e.Id = new(DataControlOffer)
		i.Context().RegisterServer(e.Id, client.Uint32(data[l:l+4]))
		l += 4

		if i.dataOfferHandler != nil {
			i.dataOfferHandler(e)
		}
	case 1:
		if i.selectionHandler == nil {
			return
		}
		var e DataControlDeviceSelectionEvent
		l := 0
		e.Id = i.Context().GetProxy(client.Uint32(data[l : l+4])).(*DataControlOffer)
		l += 4

		i.selectionHandler(e)
	case 2:
		if i.finishedHandler == nil {
			return
		}
		var e DataControlDeviceFinishedEvent

		i.finishedHandler(e)
	case 3:
		if i.primarySelectionHandler == nil {
			return
		}
		var e DataControlDevicePrimarySelectionEvent
		l := 0
		e.Id = i.Context().GetProxy(client.Uint32(data[l : l+4])).(*DataControlOffer)
		l += 4

		i.primarySelectionHandler(e)
	}
}

// DataControlSource : offer to transfer data
//
// The ext_data_control_source object is the source side of a
// ext_data_control_offer. It is created by the source client in a data
// transfer and provides a way to describe the offered data and a way to
// respond to requests to transfer the data.
type DataControlSource struct {
	client.BaseProxy
	sendHandler      DataControlSourceSendHandlerFunc
	cancelledHandler DataControlSourceCancelledHandlerFunc
}

// NewDataControlSource : offer to transfer data
//
// The ext_data_control_source object is the source side of a
// ext_data_control_offer. It is created by the source client in a data
// transfer and provides a way to describe the offered data and a way to
// respond to requests to transfer the data.
func NewDataControlSource(ctx *client.Context) *DataControlSource {
	extDataControlSourceV1 := &DataControlSource{}
	ctx.Register(extDataControlSourceV1)
	return extDataControlSourceV1
}

// Offer : add an offered MIME type
//
// This request adds a MIME type to the set of MIME types advertised to
// targets. Can be called several times to offer multiple types.
//
// Calling this after ext_data_control_device.set_selection is a protocol
// error.
//
//	mimeType: MIME type offered by the data source
func (i *DataControlSource) Offer(mimeType string) error {
	const opcode = 0
	mimeTypeLen := client.PaddedLen(len(mimeType) + 1)
	_reqBufLen := 8 + (4 + mimeTypeLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+mimeTypeLen)], mimeType, mimeTypeLen)
	l += (4 + mimeTypeLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy : destroy this source
//
// Destroys the data source object.
func (i *DataControlSource) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type DataControlSourceError uint32

// DataControlSourceError :
const (
	// DataControlSourceErrorInvalidOffer : offer sent after ext_data_control_device.set_selection
	DataControlSourceErrorInvalidOffer DataControlSourceError = 1
)

func (e DataControlSourceError) Name() string {
	switch e {
	case DataControlSourceErrorInvalidOffer:
		return "invalid_offer"
	default:
		return ""
	}
}

func (e DataControlSourceError) Value() string {
	switch e {
	case DataControlSourceErrorInvalidOffer:
		return "1"
	default:
		return ""
	}
}

func (e DataControlSourceError) String() string {
	return e.Name() + "=" + e.Value()
}

// DataControlSourceSendEvent : send the data
//
// Request for data from the client. Send the data as the specified MIME
// type over the passed file descriptor, then close it.
type DataControlSourceSendEvent struct {
	MimeType string
	Fd       int
}
type DataControlSourceSendHandlerFunc func(DataControlSourceSendEvent)

// SetSendHandler : sets handler for DataControlSourceSendEvent
func (i *DataControlSource) SetSendHandler(f DataControlSourceSendHandlerFunc) {
	i.sendHandler = f
}

// DataControlSourceCancelledEvent : selection was cancelled
//
// This data source is no longer valid. The data source has been replaced
// by another data source.
//
// The client should clean up and destroy this data source.
type DataControlSourceCancelledEvent struct{}
type DataControlSourceCancelledHandlerFunc func(DataControlSourceCancelledEvent)

// SetCancelledHandler : sets handler for DataControlSourceCancelledEvent
func (i *DataControlSource) SetCancelledHandler(f DataControlSourceCancelledHandlerFunc) {
	i.cancelledHandler = f
}

func (i *DataControlSource) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.sendHandler == nil {
			if fd != -1 {
				unix.Close(fd)
			}
			return
		}
		var e DataControlSourceSendEvent
		l := 0
		mimeTypeLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.MimeType = client.String(data[l : l+mimeTypeLen])
		l += mimeTypeLen
		e.Fd = fd

		i.sendHandler(e)
	case 1:
		if i.cancelledHandler == nil {
			return
		}
		var e DataControlSourceCancelledEvent

		i.cancelledHandler(e)
	}
}

func (i *DataControlSource) TakesFD(opcode uint32) bool {
	switch opcode {
	case 0:
		return true
	}
	return false
}

// DataControlOffer : offer to transfer data
//
// A ext_data_control_offer represents a piece of data offered for transfer
// by another client (the source client). The offer describes the different
// MIME types that the data can be converted to and provides the mechanism
// for transferring the data directly from the source client.
type DataControlOffer struct {
	client.BaseProxy
	offerHandler DataControlOfferOfferHandlerFunc
}

// NewDataControlOffer : offer to transfer data
//
// A ext_data_control_offer represents a piece of data offered for transfer
// by another client (the source client). The offer describes the different
// MIME types that the data can be converted to and provides the mechanism
// for transferring the data directly from the source client.
func NewDataControlOffer(ctx *client.Context) *DataControlOffer {
	extDataControlOfferV1 := &DataControlOffer{}
	ctx.Register(extDataControlOfferV1)
	return extDataControlOfferV1
}

// Receive : request that the data is transferred
//
// To transfer the offered data, the client issues this request and
// indicates the MIME type it wants to receive. The transfer happens
// through the passed file descriptor (typically created with the pipe
// system call). The source client writes the data in the MIME type
// representation requested and then closes the file descriptor.
//
// The receiving client reads from the read end of the pipe until EOF and
// then closes its end, at which point the transfer is complete.
//
// This request may happen multiple times for different MIME types.
//
//	mimeType: MIME type desired by receiver
//	fd: file descriptor for data transfer
func (i *DataControlOffer) Receive(mimeType string, fd int) error {
	const opcode = 0
	mimeTypeLen := client.PaddedLen(len(mimeType) + 1)
	_reqBufLen := 8 + (4 + mimeTypeLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+mimeTypeLen)], mimeType, mimeTypeLen)
	l += (4 + mimeTypeLen)
	oob := unix.UnixRights(fd)
	err := i.Context().WriteMsg(_reqBuf, oob)
	return err
}

// Destroy : destroy this offer
//
// Destroys the data offer object.
func (i *DataControlOffer) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// DataControlOfferOfferEvent : advertise offered MIME type
//
// Sent immediately after creating the ext_data_control_offer object.
// One event per offered MIME type.
type DataControlOfferOfferEvent struct {
	MimeType string
}
type DataControlOfferOfferHandlerFunc func(DataControlOfferOfferEvent)

// SetOfferHandler : sets handler for DataControlOfferOfferEvent
func (i *DataControlOffer) SetOfferHandler(f DataControlOfferOfferHandlerFunc) {
	i.offerHandler = f
}

func (i *DataControlOffer) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.offerHandler == nil {
			return
		}
		var e DataControlOfferOfferEvent
		l := 0
		mimeTypeLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.MimeType = client.String(data[l : l+mimeTypeLen])
		l += mimeTypeLen

		i.offerHandler(e)
	}
}
