// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/cursor-shape/cursor-shape-v1.xml
//
// cursor_shape_v1 Protocol Copyright:
//
// Copyright 2018 The Chromium Authors
// Copyright 2023 Simon Ser
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package cursor_shape

import (
	"github.com/SpinningVinyl/go-wayland/wayland/client"

	tablet "github.com/SpinningVinyl/go-wayland/wayland/stable/tablet-v2"
)

// CursorShapeManager : cursor shape manager
//
// This global offers an alternative, optional way to set cursor images. This
// new way uses enumerated cursors instead of a wl_surface like
// wl_pointer.set_cursor does.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type CursorShapeManager struct {
	client.BaseProxy
}

// NewCursorShapeManager : cursor shape manager
//
// This global offers an alternative, optional way to set cursor images. This
// new way uses enumerated cursors instead of a wl_surface like
// wl_pointer.set_cursor does.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
func NewCursorShapeManager(ctx *client.Context) *CursorShapeManager {
	wpCursorShapeManagerV1 := &CursorShapeManager{}
	ctx.Register(wpCursorShapeManagerV1)
	return wpCursorShapeManagerV1
}

// Destroy : destroy the manager
//
// Destroy the cursor shape manager.
func (i *CursorShapeManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetPointer : manage the cursor shape of a pointer device
//
// Obtain a wp_cursor_shape_device_v1 for a wl_pointer object.
//
// When the pointer capability is removed from the wl_seat, the
// wp_cursor_shape_device_v1 object becomes inert.
func (i *CursorShapeManager) GetPointer(pointer *client.Pointer) (*CursorShapeDevice, error) {
	cursorShapeDevice := NewCursorShapeDevice(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], cursorShapeDevice.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], pointer.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return cursorShapeDevice, err
}

// GetTabletToolV2 : manage the cursor shape of a tablet tool device
//
// Obtain a wp_cursor_shape_device_v1 for a zwp_tablet_tool_v2 object.
//
// When the zwp_tablet_tool_v2 is removed, the wp_cursor_shape_device_v1
// object becomes inert.
func (i *CursorShapeManager) GetTabletToolV2(tabletTool *tablet.TabletTool) (*CursorShapeDevice, error) {
	cursorShapeDevice := NewCursorShapeDevice(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], cursorShapeDevice.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], tabletTool.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return cursorShapeDevice, err
}

// CursorShapeDevice : cursor shape for a device
//
// This interface allows clients to set the cursor shape.
type CursorShapeDevice struct {
	client.BaseProxy
}

// NewCursorShapeDevice : cursor shape for a device
//
// This interface allows clients to set the cursor shape.
func NewCursorShapeDevice(ctx *client.Context) *CursorShapeDevice {
	wpCursorShapeDeviceV1 := &CursorShapeDevice{}
	ctx.Register(wpCursorShapeDeviceV1)
	return wpCursorShapeDeviceV1
}

// Destroy : destroy the cursor shape device
//
// Destroy the cursor shape device.
//
// The device cursor shape remains unchanged.
func (i *CursorShapeDevice) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetShape : set device cursor to the shape
//
// Sets the device cursor to the specified shape. The compositor will
// change the cursor image based on the specified shape.
//
// The cursor actually changes only if the input device focus is one of
// the requesting client's surfaces. If any, the previous cursor image
// (surface or shape) is replaced.
//
// The "shape" argument must be a valid enum entry, otherwise the
// invalid_shape protocol error is raised.
//
// This is similar to the wl_pointer.set_cursor and
// zwp_tablet_tool_v2.set_cursor requests, but this request accepts a
// shape instead of contents in the form of a surface. Clients can mix
// set_cursor and set_shape requests.
//
// The serial parameter must match the latest wl_pointer.enter or
// zwp_tablet_tool_v2.proximity_in serial number sent to the client.
// Otherwise the request will be ignored.
//
//	serial: serial number of the enter event
func (i *CursorShapeDevice) SetShape(serial, shape uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(shape))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type CursorShapeDeviceShape uint32

// CursorShapeDeviceShape : cursor shapes
//
// This enum describes cursor shapes.
//
// The names are taken from the CSS W3C specification:
// https://w3c.github.io/csswg-drafts/css-ui/#cursor
// with a few additions.
//
// Note that there are some groups of cursor shapes that are related:
// The first group is drag-and-drop cursors which are used to indicate
// the selected action during dnd operations. The second group is resize
// cursors which are used to indicate resizing and moving possibilities
// on window borders. It is recommended that the shapes in these groups
// should use visually compatible images and metaphors.
const (
	// CursorShapeDeviceShapeDefault : default cursor
	CursorShapeDeviceShapeDefault CursorShapeDeviceShape = 1
	// CursorShapeDeviceShapeContextMenu : a context menu is available for the object under the cursor
	CursorShapeDeviceShapeContextMenu CursorShapeDeviceShape = 2
	// CursorShapeDeviceShapeHelp : help is available for the object under the cursor
	CursorShapeDeviceShapeHelp CursorShapeDeviceShape = 3
	// CursorShapeDeviceShapePointer : pointer that indicates a link or another interactive element
	CursorShapeDeviceShapePointer CursorShapeDeviceShape = 4
	// CursorShapeDeviceShapeProgress : progress indicator
	CursorShapeDeviceShapeProgress CursorShapeDeviceShape = 5
	// CursorShapeDeviceShapeWait : program is busy, user should wait
	CursorShapeDeviceShapeWait CursorShapeDeviceShape = 6
	// CursorShapeDeviceShapeCell : a cell or set of cells may be selected
	CursorShapeDeviceShapeCell CursorShapeDeviceShape = 7
	// CursorShapeDeviceShapeCrosshair : simple crosshair
	CursorShapeDeviceShapeCrosshair CursorShapeDeviceShape = 8
	// CursorShapeDeviceShapeText : text may be selected
	CursorShapeDeviceShapeText CursorShapeDeviceShape = 9
	// CursorShapeDeviceShapeVerticalText : vertical text may be selected
	CursorShapeDeviceShapeVerticalText CursorShapeDeviceShape = 10
	// CursorShapeDeviceShapeAlias : drag-and-drop: alias of/shortcut to something is to be created
	CursorShapeDeviceShapeAlias CursorShapeDeviceShape = 11
	// CursorShapeDeviceShapeCopy : drag-and-drop: something is to be copied
	CursorShapeDeviceShapeCopy CursorShapeDeviceShape = 12
	// CursorShapeDeviceShapeMove : drag-and-drop: something is to be moved
	CursorShapeDeviceShapeMove CursorShapeDeviceShape = 13
	// CursorShapeDeviceShapeNoDrop : drag-and-drop: the dragged item cannot be dropped at the current cursor location
	CursorShapeDeviceShapeNoDrop CursorShapeDeviceShape = 14
	// CursorShapeDeviceShapeNotAllowed : drag-and-drop: the requested action will not be carried out
	CursorShapeDeviceShapeNotAllowed CursorShapeDeviceShape = 15
	// CursorShapeDeviceShapeGrab : drag-and-drop: something can be grabbed
	CursorShapeDeviceShapeGrab CursorShapeDeviceShape = 16
	// CursorShapeDeviceShapeGrabbing : drag-and-drop: something is being grabbed
	CursorShapeDeviceShapeGrabbing CursorShapeDeviceShape = 17
	// CursorShapeDeviceShapeEResize : resizing: the east border is to be moved
	CursorShapeDeviceShapeEResize CursorShapeDeviceShape = 18
	// CursorShapeDeviceShapeNResize : resizing: the north border is to be moved
	CursorShapeDeviceShapeNResize CursorShapeDeviceShape = 19
	// CursorShapeDeviceShapeNeResize : resizing: the north-east corner is to be moved
	CursorShapeDeviceShapeNeResize CursorShapeDeviceShape = 20
	// CursorShapeDeviceShapeNwResize : resizing: the north-west corner is to be moved
	CursorShapeDeviceShapeNwResize CursorShapeDeviceShape = 21
	// CursorShapeDeviceShapeSResize : resizing: the south border is to be moved
	CursorShapeDeviceShapeSResize CursorShapeDeviceShape = 22
	// CursorShapeDeviceShapeSeResize : resizing: the south-east corner is to be moved
	CursorShapeDeviceShapeSeResize CursorShapeDeviceShape = 23
	// CursorShapeDeviceShapeSwResize : resizing: the south-west corner is to be moved
	CursorShapeDeviceShapeSwResize CursorShapeDeviceShape = 24
	// CursorShapeDeviceShapeWResize : resizing: the west border is to be moved
	CursorShapeDeviceShapeWResize CursorShapeDeviceShape = 25
	// CursorShapeDeviceShapeEwResize : resizing: the east and west borders are to be moved
	CursorShapeDeviceShapeEwResize CursorShapeDeviceShape = 26
	// CursorShapeDeviceShapeNsResize : resizing: the north and south borders are to be moved
	CursorShapeDeviceShapeNsResize CursorShapeDeviceShape = 27
	// CursorShapeDeviceShapeNeswResize : resizing: the north-east and south-west corners are to be moved
	CursorShapeDeviceShapeNeswResize CursorShapeDeviceShape = 28
	// CursorShapeDeviceShapeNwseResize : resizing: the north-west and south-east corners are to be moved
	CursorShapeDeviceShapeNwseResize CursorShapeDeviceShape = 29
	// CursorShapeDeviceShapeColResize : resizing: that the item/column can be resized horizontally
	CursorShapeDeviceShapeColResize CursorShapeDeviceShape = 30
	// CursorShapeDeviceShapeRowResize : resizing: that the item/row can be resized vertically
	CursorShapeDeviceShapeRowResize CursorShapeDeviceShape = 31
	// CursorShapeDeviceShapeAllScroll : something can be scrolled in any direction
	CursorShapeDeviceShapeAllScroll CursorShapeDeviceShape = 32
	// CursorShapeDeviceShapeZoomIn : something can be zoomed in
	CursorShapeDeviceShapeZoomIn CursorShapeDeviceShape = 33
	// CursorShapeDeviceShapeZoomOut : something can be zoomed out
	CursorShapeDeviceShapeZoomOut CursorShapeDeviceShape = 34
	// CursorShapeDeviceShapeDndAsk : drag-and-drop: the user will select which action will be carried out (non-css value)
	CursorShapeDeviceShapeDndAsk CursorShapeDeviceShape = 35
	// CursorShapeDeviceShapeAllResize : resizing: something can be moved or resized in any direction (non-css value)
	CursorShapeDeviceShapeAllResize CursorShapeDeviceShape = 36
)

func (e CursorShapeDeviceShape) Name() string {
	switch e {
	case CursorShapeDeviceShapeDefault:
		return "default"
	case CursorShapeDeviceShapeContextMenu:
		return "context_menu"
	case CursorShapeDeviceShapeHelp:
		return "help"
	case CursorShapeDeviceShapePointer:
		return "pointer"
	case CursorShapeDeviceShapeProgress:
		return "progress"
	case CursorShapeDeviceShapeWait:
		return "wait"
	case CursorShapeDeviceShapeCell:
		return "cell"
	case CursorShapeDeviceShapeCrosshair:
		return "crosshair"
	case CursorShapeDeviceShapeText:
		return "text"
	case CursorShapeDeviceShapeVerticalText:
		return "vertical_text"
	case CursorShapeDeviceShapeAlias:
		return "alias"
	case CursorShapeDeviceShapeCopy:
		return "copy"
	case CursorShapeDeviceShapeMove:
		return "move"
	case CursorShapeDeviceShapeNoDrop:
		return "no_drop"
	case CursorShapeDeviceShapeNotAllowed:
		return "not_allowed"
	case CursorShapeDeviceShapeGrab:
		return "grab"
	case CursorShapeDeviceShapeGrabbing:
		return "grabbing"
	case CursorShapeDeviceShapeEResize:
		return "e_resize"
	case CursorShapeDeviceShapeNResize:
		return "n_resize"
	case CursorShapeDeviceShapeNeResize:
		return "ne_resize"
	case CursorShapeDeviceShapeNwResize:
		return "nw_resize"
	case CursorShapeDeviceShapeSResize:
		return "s_resize"
	case CursorShapeDeviceShapeSeResize:
		return "se_resize"
	case CursorShapeDeviceShapeSwResize:
		return "sw_resize"
	case CursorShapeDeviceShapeWResize:
		return "w_resize"
	case CursorShapeDeviceShapeEwResize:
		return "ew_resize"
	case CursorShapeDeviceShapeNsResize:
		return "ns_resize"
	case CursorShapeDeviceShapeNeswResize:
		return "nesw_resize"
	case CursorShapeDeviceShapeNwseResize:
		return "nwse_resize"
	case CursorShapeDeviceShapeColResize:
		return "col_resize"
	case CursorShapeDeviceShapeRowResize:
		return "row_resize"
	case CursorShapeDeviceShapeAllScroll:
		return "all_scroll"
	case CursorShapeDeviceShapeZoomIn:
		return "zoom_in"
	case CursorShapeDeviceShapeZoomOut:
		return "zoom_out"
	case CursorShapeDeviceShapeDndAsk:
		return "dnd_ask"
	case CursorShapeDeviceShapeAllResize:
		return "all_resize"
	default:
		return ""
	}
}

func (e CursorShapeDeviceShape) Value() string {
	switch e {
	case CursorShapeDeviceShapeDefault:
		return "1"
	case CursorShapeDeviceShapeContextMenu:
		return "2"
	case CursorShapeDeviceShapeHelp:
		return "3"
	case CursorShapeDeviceShapePointer:
		return "4"
	case CursorShapeDeviceShapeProgress:
		return "5"
	case CursorShapeDeviceShapeWait:
		return "6"
	case CursorShapeDeviceShapeCell:
		return "7"
	case CursorShapeDeviceShapeCrosshair:
		return "8"
	case CursorShapeDeviceShapeText:
		return "9"
	case CursorShapeDeviceShapeVerticalText:
		return "10"
	case CursorShapeDeviceShapeAlias:
		return "11"
	case CursorShapeDeviceShapeCopy:
		return "12"
	case CursorShapeDeviceShapeMove:
		return "13"
	case CursorShapeDeviceShapeNoDrop:
		return "14"
	case CursorShapeDeviceShapeNotAllowed:
		return "15"
	case CursorShapeDeviceShapeGrab:
		return "16"
	case CursorShapeDeviceShapeGrabbing:
		return "17"
	case CursorShapeDeviceShapeEResize:
		return "18"
	case CursorShapeDeviceShapeNResize:
		return "19"
	case CursorShapeDeviceShapeNeResize:
		return "20"
	case CursorShapeDeviceShapeNwResize:
		return "21"
	case CursorShapeDeviceShapeSResize:
		return "22"
	case CursorShapeDeviceShapeSeResize:
		return "23"
	case CursorShapeDeviceShapeSwResize:
		return "24"
	case CursorShapeDeviceShapeWResize:
		return "25"
	case CursorShapeDeviceShapeEwResize:
		return "26"
	case CursorShapeDeviceShapeNsResize:
		return "27"
	case CursorShapeDeviceShapeNeswResize:
		return "28"
	case CursorShapeDeviceShapeNwseResize:
		return "29"
	case CursorShapeDeviceShapeColResize:
		return "30"
	case CursorShapeDeviceShapeRowResize:
		return "31"
	case CursorShapeDeviceShapeAllScroll:
		return "32"
	case CursorShapeDeviceShapeZoomIn:
		return "33"
	case CursorShapeDeviceShapeZoomOut:
		return "34"
	case CursorShapeDeviceShapeDndAsk:
		return "35"
	case CursorShapeDeviceShapeAllResize:
		return "36"
	default:
		return ""
	}
}

func (e CursorShapeDeviceShape) String() string {
	return e.Name() + "=" + e.Value()
}

type CursorShapeDeviceError uint32

// CursorShapeDeviceError :
const (
	// CursorShapeDeviceErrorInvalidShape : the specified shape value is invalid
	CursorShapeDeviceErrorInvalidShape CursorShapeDeviceError = 1
)

func (e CursorShapeDeviceError) Name() string {
	switch e {
	case CursorShapeDeviceErrorInvalidShape:
		return "invalid_shape"
	default:
		return ""
	}
}

func (e CursorShapeDeviceError) Value() string {
	switch e {
	case CursorShapeDeviceErrorInvalidShape:
		return "1"
	default:
		return ""
	}
}

func (e CursorShapeDeviceError) String() string {
	return e.Name() + "=" + e.Value()
}
