// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/xdg-toplevel-icon/xdg-toplevel-icon-v1.xml
//
// xdg_toplevel_icon_v1 Protocol Copyright:
//
// Copyright © 2023-2024 Matthias Klumpp
// Copyright ©      2024 David Edmundson
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdg_toplevel_icon

import (
	"github.com/SpinningVinyl/go-wayland/wayland/client"
	xdg_shell "github.com/SpinningVinyl/go-wayland/wayland/stable/xdg-shell"
)

// ToplevelIconManager : interface to manage toplevel icons
//
// This interface allows clients to create toplevel window icons and set
// them on toplevel windows to be displayed to the user.
type ToplevelIconManager struct {
	client.BaseProxy
	iconSizeHandler ToplevelIconManagerIconSizeHandlerFunc
	doneHandler     ToplevelIconManagerDoneHandlerFunc
}

// NewToplevelIconManager : interface to manage toplevel icons
//
// This interface allows clients to create toplevel window icons and set
// them on toplevel windows to be displayed to the user.
func NewToplevelIconManager(ctx *client.Context) *ToplevelIconManager {
	xdgToplevelIconManagerV1 := &ToplevelIconManager{}
	ctx.Register(xdgToplevelIconManagerV1)
	return xdgToplevelIconManagerV1
}

// Destroy : destroy the toplevel icon manager
//
// Destroy the toplevel icon manager.
// This does not destroy objects created with the manager.
func (i *ToplevelIconManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// CreateIcon : create a new icon instance
//
// Creates a new icon object. This icon can then be attached to a
// xdg_toplevel via the 'set_icon' request.
func (i *ToplevelIconManager) CreateIcon() (*ToplevelIcon, error) {
	id := NewToplevelIcon(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// SetIcon : set an icon on a toplevel window
//
// This request assigns the icon 'icon' to 'toplevel', or clears the
// toplevel icon if 'icon' was null.
// This state is double-buffered and is applied on the next
// wl_surface.commit of the toplevel.
//
// After making this call, the xdg_toplevel_icon_v1 provided as 'icon'
// can be destroyed by the client without 'toplevel' losing its icon.
// The xdg_toplevel_icon_v1 is immutable from this point, and any
// future attempts to change it must raise the
// 'xdg_toplevel_icon_v1.immutable' protocol error.
//
// The compositor must set the toplevel icon from either the pixel data
// the icon provides, or by loading a stock icon using the icon name.
// See the description of 'xdg_toplevel_icon_v1' for details.
//
// If 'icon' is set to null, the icon of the respective toplevel is reset
// to its default icon (usually the icon of the application, derived from
// its desktop-entry file, or a placeholder icon).
// If this request is passed an icon with no pixel buffers or icon name
// assigned, the icon must be reset just like if 'icon' was null.
//
//	toplevel: the toplevel to act on
func (i *ToplevelIconManager) SetIcon(toplevel *xdg_shell.Toplevel, icon *ToplevelIcon) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], toplevel.ID())
	l += 4
	if icon == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], icon.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ToplevelIconManagerIconSizeEvent : describes a supported & preferred icon size
//
// This event indicates an icon size the compositor prefers to be
// available if the client has scalable icons and can render to any size.
//
// When the 'xdg_toplevel_icon_manager_v1' object is created, the
// compositor may send one or more 'icon_size' events to describe the list
// of preferred icon sizes. If the compositor has no size preference, it
// may not send any 'icon_size' event, and it is up to the client to
// decide a suitable icon size.
//
// A sequence of 'icon_size' events must be finished with a 'done' event.
// If the compositor has no size preferences, it must still send the
// 'done' event, without any preceding 'icon_size' events.
type ToplevelIconManagerIconSizeEvent struct {
	Size int32
}
type ToplevelIconManagerIconSizeHandlerFunc func(ToplevelIconManagerIconSizeEvent)

// SetIconSizeHandler : sets handler for ToplevelIconManagerIconSizeEvent
func (i *ToplevelIconManager) SetIconSizeHandler(f ToplevelIconManagerIconSizeHandlerFunc) {
	i.iconSizeHandler = f
}

// ToplevelIconManagerDoneEvent : all information has been sent
//
// This event is sent after all 'icon_size' events have been sent.
type ToplevelIconManagerDoneEvent struct{}
type ToplevelIconManagerDoneHandlerFunc func(ToplevelIconManagerDoneEvent)

// SetDoneHandler : sets handler for ToplevelIconManagerDoneEvent
func (i *ToplevelIconManager) SetDoneHandler(f ToplevelIconManagerDoneHandlerFunc) {
	i.doneHandler = f
}

func (i *ToplevelIconManager) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.iconSizeHandler == nil {
			return
		}
		var e ToplevelIconManagerIconSizeEvent
		l := 0
		e.Size = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.iconSizeHandler(e)
	case 1:
		if i.doneHandler == nil {
			return
		}
		var e ToplevelIconManagerDoneEvent

		i.doneHandler(e)
	}
}

// ToplevelIcon : a toplevel window icon
//
// This interface defines a toplevel icon.
// An icon can have a name, and multiple buffers.
// In order to be applied, the icon must have either a name, or at least
// one buffer assigned. Applying an empty icon (with no buffer or name) to
// a toplevel should reset its icon to the default icon.
//
// It is up to compositor policy whether to prefer using a buffer or loading
// an icon via its name. See 'set_name' and 'add_buffer' for details.
type ToplevelIcon struct {
	client.BaseProxy
}

// NewToplevelIcon : a toplevel window icon
//
// This interface defines a toplevel icon.
// An icon can have a name, and multiple buffers.
// In order to be applied, the icon must have either a name, or at least
// one buffer assigned. Applying an empty icon (with no buffer or name) to
// a toplevel should reset its icon to the default icon.
//
// It is up to compositor policy whether to prefer using a buffer or loading
// an icon via its name. See 'set_name' and 'add_buffer' for details.
func NewToplevelIcon(ctx *client.Context) *ToplevelIcon {
	xdgToplevelIconV1 := &ToplevelIcon{}
	ctx.Register(xdgToplevelIconV1)
	return xdgToplevelIconV1
}

// Destroy : destroy the icon object
//
// Destroys the 'xdg_toplevel_icon_v1' object.
// The icon must still remain set on every toplevel it was assigned to,
// until the toplevel icon is reset explicitly.
func (i *ToplevelIcon) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetName : set an icon name
//
// This request assigns an icon name to this icon.
// Any previously set name is overridden.
//
// The compositor must resolve 'icon_name' according to the lookup rules
// described in the XDG icon theme specification[1] using the
// environment's current icon theme.
//
// If the compositor does not support icon names or cannot resolve
// 'icon_name' according to the XDG icon theme specification it must
// fall back to using pixel buffer data instead.
//
// If this request is made after the icon has been assigned to a toplevel
// via 'set_icon', an 'immutable' error must be raised.
//
// [1]: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
func (i *ToplevelIcon) SetName(iconName string) error {
	const opcode = 1
	iconNameLen := client.PaddedLen(len(iconName) + 1)
	_reqBufLen := 8 + (4 + iconNameLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+iconNameLen)], iconName, iconNameLen)
	l += (4 + iconNameLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// AddBuffer : add icon data from a pixel buffer
//
// This request adds pixel data supplied as wl_buffer to the icon.
//
// The client should add pixel data for all icon sizes and scales that
// it can provide, or which are explicitly requested by the compositor
// via 'icon_size' events on xdg_toplevel_icon_manager_v1.
//
// The wl_buffer supplying pixel data as 'buffer' must be backed by wl_shm
// and must be a square (width and height being equal).
// If any of these buffer requirements are not fulfilled, a 'invalid_buffer'
// error must be raised.
//
// If this icon instance already has a buffer of the same size and scale
// from a previous 'add_buffer' request, data from the last request
// overrides the preexisting pixel data.
//
// The wl_buffer must be kept alive for as long as the xdg_toplevel_icon
// it is associated with is not destroyed, otherwise a 'no_buffer' error
// is raised. The buffer contents must not be modified after it was
// assigned to the icon. As a result, the region of the wl_shm_pool's
// backing storage used for the wl_buffer must not be modified after this
// request is sent. The wl_buffer.release event is unused.
//
// If this request is made after the icon has been assigned to a toplevel
// via 'set_icon', an 'immutable' error must be raised.
//
//	scale: the scaling factor of the icon, e.g.
func (i *ToplevelIcon) AddBuffer(buffer *client.Buffer, scale int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], buffer.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(scale))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ToplevelIconError uint32

// ToplevelIconError :
const (
	// ToplevelIconErrorInvalidBuffer : the provided buffer does not satisfy requirements
	ToplevelIconErrorInvalidBuffer ToplevelIconError = 1
	// ToplevelIconErrorImmutable : the icon has already been assigned to a toplevel and must not be changed
	ToplevelIconErrorImmutable ToplevelIconError = 2
	// ToplevelIconErrorNoBuffer : the provided buffer has been destroyed before the toplevel icon
	ToplevelIconErrorNoBuffer ToplevelIconError = 3
)

func (e ToplevelIconError) Name() string {
	switch e {
	case ToplevelIconErrorInvalidBuffer:
		return "invalid_buffer"
	case ToplevelIconErrorImmutable:
		return "immutable"
	case ToplevelIconErrorNoBuffer:
		return "no_buffer"
	default:
		return ""
	}
}

func (e ToplevelIconError) Value() string {
	switch e {
	case ToplevelIconErrorInvalidBuffer:
		return "1"
	case ToplevelIconErrorImmutable:
		return "2"
	case ToplevelIconErrorNoBuffer:
		return "3"
	default:
		return ""
	}
}

func (e ToplevelIconError) String() string {
	return e.Name() + "=" + e.Value()
}
