// Generated by go-wayland-scanner
// https://github.com/SpinningVinyl/go-wayland/cmd/go-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/1.49/staging/xdg-dialog/xdg-dialog-v1.xml
//
// xdg_dialog_v1 Protocol Copyright:
//
// Copyright © 2023 Carlos Garnacho
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdg_dialog

import (
	"github.com/SpinningVinyl/go-wayland/wayland/client"
	xdg_shell "github.com/SpinningVinyl/go-wayland/wayland/stable/xdg-shell"
)

// WmDialog : create dialogs related to other toplevels
//
// The xdg_wm_dialog_v1 interface is exposed as a global object allowing
// to register surfaces with a xdg_toplevel role as "dialogs" relative to
// another toplevel.
//
// The compositor may let this relation influence how the surface is
// placed, displayed or interacted with.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type WmDialog struct {
	client.BaseProxy
}

// NewWmDialog : create dialogs related to other toplevels
//
// The xdg_wm_dialog_v1 interface is exposed as a global object allowing
// to register surfaces with a xdg_toplevel role as "dialogs" relative to
// another toplevel.
//
// The compositor may let this relation influence how the surface is
// placed, displayed or interacted with.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
func NewWmDialog(ctx *client.Context) *WmDialog {
	xdgWmDialogV1 := &WmDialog{}
	ctx.Register(xdgWmDialogV1)
	return xdgWmDialogV1
}

// Destroy : destroy the dialog manager object
//
// Destroys the xdg_wm_dialog_v1 object. This does not affect
// the xdg_dialog_v1 objects generated through it.
func (i *WmDialog) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetXdgDialog : create a dialog object
//
// Creates a xdg_dialog_v1 object for the given toplevel. See the interface
// description for more details.
//
// Compositors must raise an already_used error if clients attempt to
// create multiple xdg_dialog_v1 objects for the same xdg_toplevel.
func (i *WmDialog) GetXdgDialog(toplevel *xdg_shell.Toplevel) (*Dialog, error) {
	id := NewDialog(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], toplevel.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

type WmDialogError uint32

// WmDialogError :
const (
	// WmDialogErrorAlreadyUsed : the xdg_toplevel object has already been used to create a xdg_dialog_v1
	WmDialogErrorAlreadyUsed WmDialogError = 0
)

func (e WmDialogError) Name() string {
	switch e {
	case WmDialogErrorAlreadyUsed:
		return "already_used"
	default:
		return ""
	}
}

func (e WmDialogError) Value() string {
	switch e {
	case WmDialogErrorAlreadyUsed:
		return "0"
	default:
		return ""
	}
}

func (e WmDialogError) String() string {
	return e.Name() + "=" + e.Value()
}

// Dialog : dialog object
//
// A xdg_dialog_v1 object is an ancillary object tied to a xdg_toplevel. Its
// purpose is hinting the compositor that the toplevel is a "dialog" (e.g. a
// temporary window) relative to another toplevel (see
// xdg_toplevel.set_parent). If the xdg_toplevel is destroyed, the xdg_dialog_v1
// becomes inert.
//
// Through this object, the client may provide additional hints about
// the purpose of the secondary toplevel. This interface has no effect
// on toplevels that are not attached to a parent toplevel.
type Dialog struct {
	client.BaseProxy
}

// NewDialog : dialog object
//
// A xdg_dialog_v1 object is an ancillary object tied to a xdg_toplevel. Its
// purpose is hinting the compositor that the toplevel is a "dialog" (e.g. a
// temporary window) relative to another toplevel (see
// xdg_toplevel.set_parent). If the xdg_toplevel is destroyed, the xdg_dialog_v1
// becomes inert.
//
// Through this object, the client may provide additional hints about
// the purpose of the secondary toplevel. This interface has no effect
// on toplevels that are not attached to a parent toplevel.
func NewDialog(ctx *client.Context) *Dialog {
	xdgDialogV1 := &Dialog{}
	ctx.Register(xdgDialogV1)
	return xdgDialogV1
}

// Destroy : destroy the dialog object
//
// Destroys the xdg_dialog_v1 object. If this object is destroyed
// before the related xdg_toplevel, the compositor should unapply its
// effects.
func (i *Dialog) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetModal : mark dialog as modal
//
// Hints that the dialog has "modal" behavior. Modal dialogs typically
// require to be fully addressed by the user (i.e. closed) before resuming
// interaction with the parent toplevel, and may require a distinct
// presentation.
//
// Clients must implement the logic to filter events in the parent
// toplevel on their own.
//
// Compositors may choose any policy in event delivery to the parent
// toplevel, from delivering all events unfiltered to using them for
// internal consumption.
func (i *Dialog) SetModal() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// UnsetModal : mark dialog as not modal
//
// Drops the hint that this dialog has "modal" behavior. See
// xdg_dialog_v1.set_modal for more details.
func (i *Dialog) UnsetModal() error {
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
